### ISSUE TITLE
Helpers should pass provided blocks on to Airbrake.notify

### ISSUE THREAD

**Issue by derikson** [airbrake/airbrake#1008]
* Airbrake version: 9.4.3
* Ruby version: 2.4.4
* Framework name & version: Rails 4.2.11
#### Airbrake config

```ruby
Airbrake.configure do |c|
  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.project_key = ENV['AIRBRAKE_API_KEY']
  c.root_directory = Rails.root
  c.logger = Rails.logger
  c.environment = Rails.env
  c.ignore_environments = [:test, :development]
  c.blacklist_keys = [/password/i, /token/i]
end
```

#### Description

The `#notify_airbrake` helper should accept a block to be passed to `Airbrake.notify`. The following code still generates a notification with severity `'error'`:

```ruby
notify_airbrake('debug test') do |notice|
  notice[:context][:severity] = 'debug'
end
```

**Comment by kyrylo** [comment]
Good point, I overlooked that.
