### ISSUE TITLE
Can't integrate with errbit

### ISSUE THREAD

**Issue by piotrpietrusewicz** [airbrake/airbrake#1020]
I haven't account on airbrake just have only api key from Errbit app. I upgraded rails to 5.2.3 and it forced me to upgrade airbrake from 4.3.8 to 9.4.5 and now airbrake prompt me to pass project_id. What should I pass to that option ? Should it be only integer ?

Thanks.

**Comment by kyrylo** [comment]
We used to accept only API key, but now we also need project id. I would try to search in your project's setting or copy it from the URL.

P.S. I'm not very familiar with Errbit. It's probably better to ask here https://github.com/errbit/errbit
