### ISSUE TITLE
Rails: query_stats is checked before airbrake can be configured leading to AR exception

### ISSUE THREAD

**Issue by grosser** [airbrake/airbrake#1022]
- We run `assets:precompile` without a database
 - lib/airbrake/rails/railtie.rb:112 needs a connection to work
 - it is run before our config/initializers/airbrake.rb is loaded
 - [boom](https://travis-ci.org/zendesk/samson/jobs/613360582?utm_medium=notification&utm_source=github_status) `ActiveRecord::ConnectionNotEstablished: ActiveRecord::ConnectionNotEstablished`

workaround:
```ruby
  # for https://github.com/airbrake/airbrake/issues/1022
  ar = ActiveRecord::Base
  def ar.connection_config
    {}
  end
```

**Comment by kyrylo** [comment]
Thanks for the bug report. I have to admit I didn't expect that a call such as `connection_config` can raise this kind of exception. I thought we queried static data here. Even the [docs](https://apidock.com/rails/ActiveRecord/ConnectionHandling/connection_config) don't mention that it can raise.

**Comment by kyrylo** [comment]
The code in question doesn't really require a database connection. All we need is the adapter name, so that we filter out sensitive SQL according to the app's dialect.

Perhaps, we could just parse `database.yml`?

```rb
YAML.load_file('config/database.yml')[::Rails.env]['adapter'] #=> 'postgresql'
```

Can you see any pitfalls with this naive but simple approach?

**Comment by grosser** [comment]
That's not reliable either since the file might not exist when someone uses `DATABASE_URL` env var.
I'm kinda fine with it blowing up since we are doing uncommon database foobar anyway, I am more concerned with that it checks the airbrake config before the config was able to initialize, so the check does nothing 🤷‍♂

**Comment by kyrylo** [comment]
I see what you mean. Since the initializer is not loaded, is this really an Airbrake bug? What if you just manually require the initializer before precompiling? 

To be honest, I'm not sure how we can work around this in the library since we use standard Railtie APIs. I imagine a possible fix could be delaying this configuration but I'm not sure where to put the code that checks `query_stats`.

Any ideas are welcome but I feel reluctant to the change because it works for 99% of cases.

**Comment by grosser** [comment]
Yeah not a blocker, so meh ... just wanted to call out that the patter of config/initializers runs after builting initializers vs builtin initializers check settings from config/initializers does not work :)
