### ISSUE TITLE
SignalException: SIGTERM on every Heroku deploy

### ISSUE THREAD

**Issue by aspiers** [airbrake/airbrake#1025]
By default deploying to Heroku causes a `SignalException: SIGTERM` error.  Airbrake should be able to recognise this case and ignore it, but even with this configuration it is still not ignored and I have no idea why:

```
noisy_errors = [SignalException]

Airbrake.add_filter do |notice|
  next unless noisy_errors.include?(notice.stash[:exception])
  notice.ignore!
end
```

**Comment by kyrylo** [comment]
What's your version of airbrake & airbrake-ruby?

**Comment by aspiers** [comment]
From `Gemfile.lock`:

    airbrake (9.5.0)
    airbrake-ruby (4.8.0)

**Comment by kyrylo** [comment]
I believe the filter you wrote is wrong. `notice.stash[:exception]` contains an instance of an exception. `noisy_errors` contains classes of exceptions. Therefore, you're comparing apples to oranges. I would recommend to rewrite the filter. 

I haven't tested, but here are two versions that should work:

```rb
Airbrake.add_filter do |notice|
  notice.ignore! if notice[:errors].first[:type] == 'SignalException' # or SIGHUP or whatever you want
end
```

```rb
Airbrake.add_filter do |notice|
  notice.ignore! if notice.stash[:exception].is_a?(SignalException)
end
```

**Comment by aspiers** [comment]
Doh, of course! Thanks so much!

**Comment by aspiers** [comment]
But where is the documentation on what goes in `notice[:errors]` and `notice.stash`?  I couldn't find it.

**Comment by kyrylo** [comment]
👍 

`notice[:errors]` is documented here: https://github.com/airbrake/airbrake-ruby#notice--notice
`notice.stash` is documented here: https://github.com/airbrake/airbrake-ruby#noticestash--noticestash

The best place for consulting how filters work is to check official filters. For example:
https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/filters/system_exit_filter.rb

**Comment by aspiers** [comment]
Thanks, very helpful!  Although I don't see anything mentioning `notice.stash[:exception]` specifically?

**Comment by kyrylo** [comment]
It's documented here (second example): https://github.com/airbrake/airbrake-ruby#airbrakeadd_filter

**Comment by aspiers** [comment]
Sorry, I didn't phrase that question right. I did see that example, but I was wondering  if there was anything explaining in general what else, other than `notice.stash[:exception]` and `notice.stash[:request]`, can be expected in `notice.stash` (if anything)?  You pointed at https://github.com/airbrake/airbrake-ruby#noticestash--noticestash as the documentation for `notice.stash`, but that doesn't cover what can be expected in it by default.

Similarly, you pointed at https://github.com/airbrake/airbrake-ruby#notice--notice for documentation on `notice[:errors]`, but that doesn't say anything about its contents.  For example the `:type` attribute in your `notice[:errors].first[:type]` example code is not mentioned anywhere as far as I can see.

Furthermore it's not clear to me why there is both `notice[:errors]` *and* `notice.stash[:exception]`, and why the former is plural whereas the latter is singular.  Does this mean there can be multiple errors reported at once?  If so, which one ends up in `notice.stash[:exception]`?

Thanks again, and sorry to be asking yet more questions.  The documentation is already excellent, and I could well be missing something but it feels like it's not quite 100% complete yet.

**Comment by kyrylo** [comment]
>  I was wondering if there was anything explaining in general what else, other than notice.stash[:exception] and notice.stash[:request]

IIRC we don't store anything else in the stash by default. That said, your app can store any objects you want and access them in your filters.

> the documentation for notice.stash, but that doesn't cover what can be expected in it by default.

Makes sense, I'll update the doc to reflect what I said above.

> Similarly, you pointed at https://github.com/airbrake/airbrake-ruby#notice--notice for documentation on notice[:errors], but that doesn't say anything about its contents

We document the contents here: https://airbrake.io/docs/api/#create-notice-v3
There's too much information to document that's why it's not in the README. I'd recommend dropping a `binding.pry` inside a filter and inspect the notice object by yourself.

Reading source code also makes it clear-ish: https://github.com/airbrake/airbrake-ruby/blob/06c28d6fcab82a0469e2cc091e3d2c97ff13c7c9/lib/airbrake-ruby/notice.rb#L59-L67

> Furthermore it's not clear to me why there is both notice[:errors] and notice.stash[:exception], and why the former is plural whereas the latter is singular

`notice[:errors]` contains JSONable data. The stash contains real exception objects, so that you can call methods on them. This is made for convenience to cover all possible use cases.

>  Does this mean there can be multiple errors reported at once? If so, which one ends up in notice.stash[:exception]?

Yes, there can be multiple exceptions if your exception is nested. In that case `notice.stash[:exception]` will be an exception that has a non-nil `cause`: `notice.stash[:exception].cause` will return another exception.

> Thanks again, and sorry to be asking yet more questions. The documentation is already excellent, and I could well be missing something but it feels like it's not quite 100% complete yet.

No worries and thanks for helping 👍

**Comment by aspiers** [comment]
What a great answer, thanks so much for the amazing support!
