### ISSUE TITLE
delayed_job performance issues with Airbrake version 10.0.1

### ISSUE THREAD

**Issue by Jackiesan** [airbrake/airbrake#1081]
* Airbrake version: 10.0.1
* Ruby version: 2.5.3
* delayed_job_active_record gem version: 4.1
* Rails version: 5.2.4

#### Description

Upgrading from Airbrake version 9.5.5 to 10.0.1 causes a slowdown in one of our delayed job workers. These performance issues were introduced when we upgraded to version 10.0.1, downgrading to 9.5.5 fixed the issue.

Job durations used to take on average 0.20 ms and with upgrade have spiked up to 15+ seconds. 

Are there any changes that were introduced with v 10.0.1 that changed the interaction between Airbrake and delayed_job_active_record that could have caused these issues?

**Comment by kyrylo** [comment]
Yeah, we started monitoring your job execution timing and sending that to Airbrake. What tool do you use to monitor your job durations now?

**Comment by Jackiesan** [comment]
We have a dashboard in Sumo monitoring the job durations that are logged by ActiveJob. https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/activejob/lib/active_job/logging.rb#L86

**Comment by kyrylo** [comment]
I suspect this might be due to the fact that we send our statistics synchrnously:
https://github.com/airbrake/airbrake/blob/d14ec9a8c71f630838a2bb22910dbd36ef79f5d4/lib/airbrake/delayed_job.rb#L31

I will check if we can use async delivery.

**Comment by kyrylo** [comment]
@Jackiesan can you please update the library and let me know if this is resolved for you now?
