### ISSUE TITLE
It seems that v10 breaks sequel/sequel-rails initialization

### ISSUE THREAD

**Issue by ohmycto** [airbrake/airbrake#1086]
Hi,

After upgrading from v9.5 to v10 we've faced with the following issue: we have `SequelRails::Migrations.pending_migrations?` in one of our initializers and this line fails with very strange message:
```
Sequel::Error:
  No database associated with Sequel::Model: have you called Sequel.connect or Sequel::Model.db= ?
# ./local/ruby/2.6.0/gems/sequel-5.31.0/lib/sequel/model/base.rb:353:in `db'
# ./local/ruby/2.6.0/gems/sequel-rails-1.1.0/lib/sequel_rails/migrations.rb:22:in `pending_migrations?'
# ./config/initializers/pending_migrations.rb:7:in `<top (required)>'
...
```
This didn't happen on v9.5 and this happens *only* during initialization. If I comment this line out and launch Rails console, then code `SequelRails::Migrations.pending_migrations?` works good.

We have two independent projects with Sequel and updating Airbrake to v10 breaks both. I can't figure out what's happening, do you have any ideas?

Thanks!

**Comment by kyrylo** [comment]
Hi, can you specify exact versions you upgraded from and to (Including airbrake-ruby versions)?

**Comment by kyrylo** [comment]
FWIW, what's the Rails version you are running?

**Comment by ohmycto** [comment]
Hi @kyrylo, after some investigation it turned out that everything breaks when updating airbrake gem from 10.0.0 to 10.0.1.

Here's my environment: 
```
rails (6.0.2.2)

airbrake (10.0.1)  # version 10.0.0 works!
airbrake-ruby (4.14.1)

sequel (5.31.0)
sequel-rails (1.1.0)
```

Ruby version: `ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux-musl]`

**Comment by kyrylo** [comment]
Our latest version of `airbrake` is 10.0.3. Could you test against it?

Also, can you confirm that `airbrake (10.0.0)` with `airbrake-ruby (4.14.1)` works, but  `airbrake (10.0.1)` with `airbrake-ruby (4.14.1)` doesn't? I am trying to understand whether the issue is with `airbrake` or `airbrake-ruby`.

**Comment by kyrylo** [comment]
Have you seen https://github.com/TalentBox/sequel-rails/issues/158 ? Speaks of the same issue, perhaps Airbrake is not to blame (yet 😄).

**Comment by ohmycto** [comment]
> Our latest version of airbrake is 10.0.3. Could you test against it?

I did, it also doesn't work.

> Also, can you confirm that airbrake (10.0.0) with airbrake-ruby (4.14.1) works, but airbrake (10.0.1) with airbrake-ruby (4.14.1) doesn't? 

Yes, I confirm this.

> Have you seen TalentBox/sequel-rails#158 ? 

Yeah, the error message seems to be the same, but this is not my case, since I have another background.

**Comment by ohmycto** [comment]
@kyrylo Ok I figured out: this exact line is the culprit: https://github.com/airbrake/airbrake/blob/v10.0.1/lib/airbrake/rails/railtie.rb#L9

In version 10.0.1 `after: :load_config_initializers` was added and that somehow causes this issue. I'm trying to understand the reason.

**Comment by kyrylo** [comment]
Nice one, that's helpful.

I can see this comment mentions the faulty initializer:
https://github.com/TalentBox/sequel-rails/issues/158#issuecomment-383326935

Probably that's the reason. We can test that with:

`config.sequel.skip_connect = true` (via https://github.com/TalentBox/sequel-rails/issues/158#issuecomment-390995133)

**Comment by ohmycto** [comment]
That is the problem: I can't skip connect because the purpose of the initializer is to check if an app has some pending migrations:
```ruby
# config/initializers/pending_migrations.rb

if SequelRails::Migrations.pending_migrations?
  raise "Migrations are pending"
end
```

It can't be done without a database connection obviously.

**Comment by kyrylo** [comment]
Can you tweak your initializer to run after you have a DB connection?

```rb
Rails.application.config.after_initialize do
  # initialization code goes here
end
```

FWIW, I don't understand why this library is messing things up for you. My hunch is that this invocation is somehow affecting your initializers:

https://github.com/airbrake/airbrake/blame/v10.0.1/lib/airbrake/rails/railtie.rb#L27

**Comment by ohmycto** [comment]
@kyrylo That helped, thanks!
