### ISSUE TITLE
EOFError: end of file reached

### ISSUE THREAD

**Issue by fury252** [airbrake/airbrake#1094]
* Airbrake version: 10.0.3
* Ruby version: 2.4.10
* Framework name & version: Rails 5.1.7

#### Airbrake config
```ruby
Airbrake.configure do |config|
  config.project_id = ...
  config.project_key = ...
  config.environment = Rails.env
  config.ignore_environments = %w[development test]
  config.root_directory = Rails.root
  config.blacklist_keys = %w[...]
end

Airbrake.add_filter do |notice|
  notice[:context][:environment_host] = ENV["HOST"]
  if notice[:errors].any?{ |error| %w[SignalException ActiveRecord::RecordNotFound].include?(error[:type]) }
    notice.ignore!
  end
end

ActiveSupport::Notifications.subscribe("deprecation.rails") do |_name, _start, _finish, _id, payload|
  Airbrake.notify(
    error_class:   "DEPRECATION WARNING",
    error_message: payload[:message]
  )
end
```
#### Description

We are observing dozens to hundreds of errors per day on Datadog of which we believe are related with the Airbrake gem because it's the only gem we use that uses the PUT HTTP method. This error doesn't appear in Airbrake. The number of errors like this is also positively correlated with the number of requests we have in the server. Do you have any idea what this might be? We've been seeing this error for some months now and at least since Airbrake version 9.5.1 and Rails 5 (the errors could be there before these versions).

<img width="1220" alt="Screenshot 2020-05-25 at 17 20 21" src="https://user-images.githubusercontent.com/1846632/82830015-8586f800-9eac-11ea-9e00-7fa661f42618.png">
<img width="1230" alt="Screenshot 2020-05-25 at 17 20 59" src="https://user-images.githubusercontent.com/1846632/82830026-8ae44280-9eac-11ea-8927-b2011edb8148.png">

**Comment by kyrylo** [comment]
Do you use the APM feature? Does Datadog report what URL is being hit? Our notifier uses `PUT` requests to send APM-related data. You might try disabling it for debug purposes and observe logs:

```rb
config.performance_stats = false
```

Can you please email me your project id? `kyrylo@airbrake.io`

**Comment by kyrylo** [comment]
Why does your screenshot say "PUT" in the Resource column? Shouldn't it be in the Method column? There's also no Status Code. Is that normal/expected?
