### ISSUE TITLE
URGENT: ssl verification failed

### ISSUE THREAD

**Issue by silva96** [airbrake/airbrake#1095]
RAILS_ENV=production bundle exec rake airbrake:test
Error: **Airbrake: HTTP error: SSL_connect returned=1 errno=0 state=error: certificate verify failed

Tested on multiple projects with different versions, all fail.

This is important because our deploy pipeline includes notifying airbrake of the deploy, when it fails, deploy fails too.

It works from my local machine though. My servers are in aws.

**Comment by phumpal** [comment]
@silva96 it looks like the root certificate in our certificate chain expires today (2020.05.30). I've deployed an update the chain with the new Root CA Cert.

Can you please try again?

**Comment by silva96** [comment]
It works, thanks.
