### ISSUE TITLE
Rails renders wrong view format after 10.0.1

### ISSUE THREAD

**Issue by Jakanapes** [airbrake/airbrake#1096]
We have an old application that is currently Rails 5.2.4.3, using ruby 2.6.5

Recently tried to upgrade from Airbrake 10.0.0 and are having an issue with some of the older controller actions trying to render the wrong format view.

It's a very simple action.

```ruby
def index
end
```

There is both an index.haml and an index.rjson

The logs indicate that it is being requested as HTML and inspecting the `request.format` confirms that.

The only thing that changes is bumping Airbrake to 10.0.1.

Any insight is appreciated.

**Comment by Jakanapes** [comment]
appears to be this line

https://github.com/airbrake/airbrake/compare/v10.0.0...v10.0.1#diff-3c838235fb95dc5744dd528c6e7896a5R9

If I edit the source and remove the `after:` param, it works as expected.  Not sure why, just yet

**Comment by Jakanapes** [comment]
We have this line in  our rjson initializer

```ruby
ActionView::Template.register_template_handler :rjson, RJSON::Handler
```

If that line gets commented out, then it chooses the haml correctly.

**Comment by kyrylo** [comment]
We've had a [similar report](https://github.com/airbrake/airbrake/issues/1086) a month ago. Can you try wrapping your initializer code in `Rails.application.config.after_initialize do`? That should do the trick:

```rb
Rails.application.config.after_initialize do
  # initialization code goes here
end
```

**Comment by kyrylo** [comment]
Btw any explanation to this is appreciated. I haven't been able to replicate this issue myself and I am not 100% sure it's something that Airbrake needs to fix.

**Comment by kyrylo** [comment]
Gentle ping.

**Comment by Jakanapes** [comment]
Apologies, meant to respond and got distracted.  Wrapping the call in the initializer with the `Rails.application.config.after_initialize` did the trick.

Spent some time trying to figure out the root cause, but haven't been successful.  It would be nice to know why that solution worked, but it's not 100% required right now.
