### ISSUE TITLE
App fails to initialize with 10.0.1+

### ISSUE THREAD

**Issue by cgriego** [airbrake/airbrake#1105]
After upgrading to any version of Airbrake starting with 10.0.1, our app fails to boot and initialize properly. I tracked the issue down to this pull request. https://github.com/airbrake/airbrake/pull/1069

Because of the way railties work, and also a side effect of Airbrake starting with the first letter of the alphabet, this causes a cascading change in the way the app and other gems initialize. See this diff of the output of `rake initializers` with prepended comment with the Airbrake version, which is the only difference in the app code.

```diff
--- /Users/cgriego/Desktop/initializers-10.0.0.txt	2020-07-02 08:51:32.000000000 -0500
+++ /Users/cgriego/Desktop/initializers-10.0.1.txt	2020-07-02 08:51:39.000000000 -0500
@@ -1,4 +1,4 @@
-# Airbrake 10.0.0
+# Airbrake 10.0.1
 ActionView::Railtie.set_load_path
 Bootstrap::Rails::Engine.set_load_path
 Coffee::Rails::Engine.set_load_path
@@ -165,43 +165,8 @@
 ActionPack::XmlParser::Railtie.actionpack-xml_parser.configure
 ActiveAttr::Railtie.active_attr.logger
 ActiveAttr::Railtie.active_attr.attributes
-Airbrake::Rails::Railtie.airbrake.middleware
-Airbrake::Rails::Railtie.airbrake.action_controller
-Airbrake::Rails::Railtie.airbrake.active_record
-Airbrake::Rails::Railtie.airbrake.active_job
-Airbrake::Rails::Railtie.airbrake.action_cable
-CarrierWave::Railtie.carrierwave.setup_paths
-CarrierWave::Railtie.carrierwave.active_record
-Rails::Mongoid::Railtie.mongoid.load-config
-Rails::Mongoid::Railtie.mongoid.preload-models
-Rails::Mongoid::Railtie.mongoid.runtime-metric
-Config::Integrations::Rails::Railtie.config_reload_on_development
-Responders::Railtie.responders.flash_responder
-RequestStore::Railtie.request_store.insert_middleware
-Draper::Railtie.draper.setup_action_controller
-Draper::Railtie.draper.setup_action_mailer
-Draper::Railtie.draper.setup_orm
-Draper::Railtie.draper.minitest-rails_integration
 Geocoder::Railtie.geocoder.insert_into_active_record
-HttpAcceptLanguage::Railtie.http_accept_language.add_middleware
-Jbuilder::Railtie.jbuilder
-Kaminari::Railtie.kaminari
 NewRelic::Railtie.newrelic_rpm.start_plugin
-RailsI18n::Railtie.rails-i18n
-SecureHeaders::Railtie.secure_headers.middleware
-SecureHeaders::Railtie.secure_headers.action_controller
-Hashie::Railtie.hashie.configure_logger
-WebConsole::Railtie.web_console.initialize
-WebConsole::Railtie.web_console.development_only
-WebConsole::Railtie.web_console.insert_middleware
-WebConsole::Railtie.web_console.mount_point
-WebConsole::Railtie.web_console.template_paths
-WebConsole::Railtie.web_console.whitelisted_ips
-WebConsole::Railtie.web_console.whiny_requests
-WebConsole::Railtie.i18n.load_path
-FactoryBotRails::Railtie.factory_bot.set_fixture_replacement
-FactoryBotRails::Railtie.factory_bot.set_factory_paths
-FactoryBotRails::Railtie.factory_bot.register_reloader
 ActionView::Railtie.prepend_helpers_path
 Bootstrap::Rails::Engine.prepend_helpers_path
 Coffee::Rails::Engine.prepend_helpers_path
@@ -236,6 +201,41 @@
 Kaminari::Engine.load_config_initializers
 OkComputer::Engine.load_config_initializers
 MyApp::Application.load_config_initializers
+Airbrake::Rails::Railtie.airbrake.middleware
+Airbrake::Rails::Railtie.airbrake.action_controller
+Airbrake::Rails::Railtie.airbrake.active_record
+Airbrake::Rails::Railtie.airbrake.active_job
+Airbrake::Rails::Railtie.airbrake.action_cable
+CarrierWave::Railtie.carrierwave.setup_paths
+CarrierWave::Railtie.carrierwave.active_record
+Rails::Mongoid::Railtie.mongoid.load-config
+Rails::Mongoid::Railtie.mongoid.preload-models
+Rails::Mongoid::Railtie.mongoid.runtime-metric
+Config::Integrations::Rails::Railtie.config_reload_on_development
+Responders::Railtie.responders.flash_responder
+RequestStore::Railtie.request_store.insert_middleware
+Draper::Railtie.draper.setup_action_controller
+Draper::Railtie.draper.setup_action_mailer
+Draper::Railtie.draper.setup_orm
+Draper::Railtie.draper.minitest-rails_integration
+HttpAcceptLanguage::Railtie.http_accept_language.add_middleware
+Jbuilder::Railtie.jbuilder
+Kaminari::Railtie.kaminari
+RailsI18n::Railtie.rails-i18n
+SecureHeaders::Railtie.secure_headers.middleware
+SecureHeaders::Railtie.secure_headers.action_controller
+Hashie::Railtie.hashie.configure_logger
+WebConsole::Railtie.web_console.initialize
+WebConsole::Railtie.web_console.development_only
+WebConsole::Railtie.web_console.insert_middleware
+WebConsole::Railtie.web_console.mount_point
+WebConsole::Railtie.web_console.template_paths
+WebConsole::Railtie.web_console.whitelisted_ips
+WebConsole::Railtie.web_console.whiny_requests
+WebConsole::Railtie.i18n.load_path
+FactoryBotRails::Railtie.factory_bot.set_fixture_replacement
+FactoryBotRails::Railtie.factory_bot.set_factory_paths
+FactoryBotRails::Railtie.factory_bot.register_reloader
 ActionView::Railtie.engines_blank_point
 Bootstrap::Rails::Engine.engines_blank_point
 Coffee::Rails::Engine.engines_blank_point
```

All of these other libraries now have their initializers run after `load_config_initializers`, which means they're not initialized when I try to use them in our custom initializers, such as the Mongoid connection.

The `initializer` method in Rails seems to set a default for `:after` of the last initializer registered if one isn't provided. Since the pull request changes the "airbrake.middleware" initializer to run after the config initializers, each initializer registered after "airbrake.middleware" is appended to run after it which means they all run after config initializers.

https://github.com/rails/rails/blob/fbe2433be6e052a1acac63c7faf287c52ed3c5ba/railties/lib/rails/initializable.rb#L88-L92

I'm not sure what the best fix for this is. Maybe there's a different hook rather than `initializer` that can be used to run code after config initializers but before the middleware stack is prepared. Another option is to define an Airbrake initializer before "airbrake.middleware", then define the "airbrake.middleware" initializer as-is to run after config initializers, then define the next initializers to run after "airbrake.middleware" to reset the ordering. The Geocoder and NewRelic initializers specify `before: :load_config_initializers` so that may also be enough to reset the ordering, but if I try to set `before: :load_config_initializers` on "airbrake.action_controller" then I cause a "TSort::Cyclic: topological sort failed" error.

**Comment by kyrylo** [comment]
Thanks for digging into that. I haven't dug into the details yet, but one quick thing to try that comes to my mind is to try and use wrap all of the Airbrake config into `Rails.application.config.after_initialize`.

```rb
Rails.application.config.after_initialize do
  Airbrake.configure do ...
end
```

Could you please try this and let me know how it affects the initialisation process? Btw, what's your Rails version?

**Comment by cgriego** [comment]
Hi @kyrylo, first off the Rails version is 6.0.3.2.

I tried it, but wrapping my `Airbrake.configure` block didn't change much, since the initialization order is already out of whack by the time the config initializers run.
