### ISSUE TITLE
Bump airbrake-ruby to 4.15

### ISSUE THREAD

**Issue by ryanatwork** [airbrake/airbrake#1107]
Looks like airbrake-ruby v4.15.0 was released a few weeks ago https://github.com/airbrake/airbrake-ruby/releases/tag/v4.15.0

Can we get this bumped? Looks like it's on 4.13 https://github.com/airbrake/airbrake/blob/master/airbrake.gemspec#L33

I can open a PR, but figure it might be faster for y'all to do.

**Comment by kyrylo** [comment]
Shouldn't `bundle update airbrake-ruby` bump it already?

**Comment by ryanatwork** [comment]
Thanks @kyrylo  that worked, for some reason I was thinking since the `airbrake` gemspec was tied to that version it wouldn't update.  Going to close this.
