### ISSUE TITLE
Airbrake::Rack::HttpParamsFilter not handling routes mounted as rack apps

### ISSUE THREAD

**Issue by bilby91** [airbrake/airbrake#1126]
Hello,

Today I realized that our integration with Airbrake was not sending errors. 

I think I narrowed down the problem to the `Airbrake::Rack::HttpParamsFilter` not handling correctly routes that are mounted as Rack apps here: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/http_params_filter.rb#L20.

I also found this issue on another project that perform error reporting and I applied the suggested fix and it seems to be working fine => https://github.com/honeycombio/beeline-ruby/issues/31

If the `request.raw_post` is nil, then `request.params` will raise `ActionDispatch::Http::Parameters::ParseError` if called.

**Comment by kyrylo** [comment]
Is this related to airbrake v11 or was it also the case with airbrake v10?

**Comment by kyrylo** [comment]
Is there an easy way to reproduce this?

**Comment by bilby91** [comment]
I tried reproducing it in an independent app and I couldn't. This helped me realize that I was not rewinding the body after being consumed in my rack application.

Thanks! I'm closing this one.
