### ISSUE TITLE
Turn off performance stats on version 11

### ISSUE THREAD

**Issue by bilby91** [airbrake/airbrake#1127]
Hello,

Today we updated to the new v11 version and we notices that our current code to disable the performance_stats no longer works. I couldn't figure out exactly what needs to change in order to get the previous behavior. Is that documented somewhere ? 

Thanks in advance!

**Comment by kyrylo** [comment]
This is just a bug! Oops

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake-ruby/pull/618, thanks! I will release a new version of airbrake-ruby shortly.

**Comment by bilby91** [comment]
Thanks! Looking forward on the new one so we can upgrade!

**Comment by kyrylo** [comment]
Already released :)
