### ISSUE TITLE
Rejected Airbrake error bodies

### ISSUE THREAD

**Issue by sarahstrong** [airbrake/airbrake#1128]
* Airbrake version: 10.0.5
* Ruby version: 2.6.0
* Framework name & version: Rails 6.0

#### Airbrake config

```
Airbrake.configure do |c|
  c.root_directory = Rails.root
  c.logger = Airbrake::Rails.logger
  c.environment = Rails.env
  c.ignore_environments = %w[development test]
  c.blacklist_keys = [/password/i, /authorization/i]
end
```

#### Description

We get occasional unparseable error sent to Airbrake. Today we got a new error that consistently produced an unparseable error.

*Airbrake parameters*

```
{
  "json": "ctionview-6.0.0/lib/action_view/base.rb\",\"line\":2:<-274,\"function\":\"_run\"},{\"file\":\"/GEM_ROOT/gems/act"
}
```

*Airbrake context*

```
{
  "messageParams": {
    "0": ":",
    "1": "key:value"
  },
  "messagePattern": "invalid character {} after object {} pair",
  "remoteAddr": "xxxxxxxx",
  "remoteCountry": "United States",
  "remoteCountryCode": "US"
}
```

The error itself is an ActionView:Template 500 error due to an unset variable required for render.

Please let me know if I can help by sending more information about our setup or the error. Thank you!

**Comment by kyrylo** [comment]
Hi, sorry for the late reply. Can you email me your project id? kyrylo@airbrake.io
Alternatively, you can write to our support.

**Comment by kyrylo** [comment]
Thanks for the links! I checked your project and I cannot explain why you have those errors.

* Do you use any custom filters or third party code that works with Airbrake? It looks like the notifier sends invalid JSON but our official notifiers never send something like what you see
* I noticed that in your example there's a suspicious line: `\"line\":2:<-274,`. I don't understand what the `<-274` part means. It looks like this backtrace was formatted by some debugging tool. Do you happen to know if that error is from production or development?
* Other errors look like this:

    ```
    "json": "k-6.0.0/lib/abstract_controller/callbacks.rb\",\",\"l<-ine\":41,\"function\":\"process_action\"},{\"file\":\"/GEM"
    ```

    Notice the weird line again: `"l<-ine\":41`. Do you have any clue what that is?
