### ISSUE TITLE
Get error in rails console after upgrade to version 11.0.1

### ISSUE THREAD

**Issue by edenisn** [airbrake/airbrake#1138]
After upgrade gem 'airbrake' to version 11.0.1 I got error in console (periodically):

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>9BD6AF84F810C452</RequestId><HostId>VHAFntur39043H8G73EiGg7DCqWrrkQStPXSRBx7Nj4I4G9e/kpV2YL+c6sLU2S2z45ERWdyoE=</HostId></Error>
**Airbrake: applying remote settings: {}
```
I understood that this error from AWS S3, but with an older version of airbrake we didn't receive such error.
I use Rails 5.0.2, ruby 2.6 (got this error in development and production modes).

**Comment by scottsbaldwin** [comment]
@kyrylo can you take a look at this please?

**Comment by scottsbaldwin** [comment]
@edenisn are you able to still see errors reported on your dashboard?

**Comment by edenisn** [comment]
@scottsbaldwin yes, still got those errors in rails console.

**Comment by scottsbaldwin** [comment]
Good. Based on the error you reported, I assumed you should still have errors reported. Can you send me your project ID so @kyrylo and I can take a further look on the backend?

**Comment by edenisn** [comment]
@scottsbaldwin my project id: 11371 . thanks!

**Comment by scottsbaldwin** [comment]
Can you double check that project ID @edenisn? It should be the value in `c.project_id` from your corresponding initializer (or from your project settings page in the Airbrake dashboard).

```
Airbrake.configure do |c|
  c.project_id = 11111111 # this is your project ID
  c.project_key = 'your_project_key'
end
```

**Comment by edenisn** [comment]
@scottsbaldwin Yes. Everything is as you wrote above.

**Comment by edenisn** [comment]
@scottsbaldwin but look into airbrake UI dashboard I see that we have this url: projects/45413

**Comment by scottsbaldwin** [comment]
Ok, and if you load the settings link from the top navigation menu at that URL, you should see a Project ID and Project API Key at the top right corner of the page. That project ID (which should match the number in your URL) is what you should have in your configuration.

```
Airbrake.configure do |c|
  c.project_id = 45413
  ...
end
```

The `11371` ID doesn't seem correct.

**Comment by edenisn** [comment]
Ahhh. yes. You are right! Fixed it.

**Comment by scottsbaldwin** [comment]
Great! Watch your console and see if you still get that error.

**Comment by edenisn** [comment]
@scottsbaldwin Yeahh! Changed credentials data with project id and right now didn't get error from S3 in console. Thanks!

**Comment by scottsbaldwin** [comment]
@edenisn are we ok to close out this issue then?

**Comment by edenisn** [comment]
@scottsbaldwin I thinks yes.

**Comment by scottsbaldwin** [comment]
Thanks @edenisn!
