### ISSUE TITLE
Upgrading airbrake gem results in degradation of GC frequency

### ISSUE THREAD

**Issue by xantrac** [airbrake/airbrake#1144]
In the past weeks, we have been attempting to update our airbrake gem from 
`gem 'airbrake', '9.0.2'`
to a newer version
`gem 'airbrake', '11.0.1'`

with the current configuration

```
Airbrake.configure do |config|
  config.environment = Rails.env
  config.performance_stats = false
  config.ignore_environments = %w[development]
  config.blocklist_keys = [
    /(password|token)/
  ]
  config.project_id = Settings.airbrake.id
  config.project_key = Settings.airbrake.key
  config.logger = Airbrake::Rails.logger
end
```

Deploying the gem both in the production and staging environment resulted in performance degradation for our system in the form of:

- increased GC frequency
- consequent latency in generating the response from the end-user

here some data we collected. We performed to load test. The first starting at 2:20 pm and ending at 2:35 pm using the older gem version and the second starting at 3:30 pm until 3:45 pm using the newer version.

![image](https://user-images.githubusercontent.com/38252032/104025794-2784f780-5193-11eb-99f9-1b63dca810e5.png)
![image](https://user-images.githubusercontent.com/38252032/104026195-995d4100-5193-11eb-85ff-d0c60e8f7b32.png)

You can notice how the memory consumption is almost identical in both cases but the time spent in GC is definitely higher. 

Quoting one of my colleagues: 

> The number of Major GC runs is increasing overtime in the second load test. I think that means there is memory that’s unable to be freed after GC runs that’s accumulating over time. Minor GC runs are more frequent and run on newly-created objects. Major GC runs are triggered when a Minor GC run is not sufficient to free up enough memory and the entire object space must be traversed. so over time that object graph grows and grows without being cleared.
![image](https://user-images.githubusercontent.com/38252032/104026762-636c8c80-5194-11eb-9269-394a0ac98bb9.png)

Let me know if you need any further detail.

**Comment by scottsbaldwin** [comment]
Thanks @xantrac, we'll take a look.

**Comment by kyrylo** [comment]
Thanks for the report. I have a couple questions:

* What tool do you use to measure the GC stats? Seems to be New Relic?
* `v9.0.2` was released on Apr 8, 2019. Is there any change you could test this on `v9.5.5`? `v9.5.5` is the last `v9` version
* Do you know the versions of the `airbrake-ruby` gem that were used during these tests?

Jumping from `v9.0.2` to `v11.0.1` is a big leap forward because we've introduced a major feature called APM (`performance_stats`). It is expected that there might be some overhead but I can see that you disable it in the config. I would like what kind of stuff was executed during your load testing.

* Did you hit the same Rails route or was it multiple routes?
* How many SQL queries were executed during the 3:30 pm - 3:45 pm time window?
* Did you run any worker jobs?

I am trying to narrow down the culprits and understand where we might have a leak.

**Comment by xantrac** [comment]
@kyrylo thank you for looking into this.

> What tool do you use to measure the GC stats? Seems to be New Relic?
Correct

> v9.0.2 was released on Apr 8, 2019. Is there any chance you could test this on v9.5.5? v9.5.5 is the last v9 version
 I performed a test using `9.5.5` and yes I got an increased frequency in time spent in GC about the same increment of `11.0.1` between 1% and 2%.

> Do you know the versions of the airbrake-ruby gem that were used during these tests?
We are no directly pinning any `airbrake-ruby` version, we are letting `airbrake` define its own dependencies:
- airbrake 11.0.1 -> airbrake-ruby 5.1.1
- airbrake 9.5.5 -> airbrake-ruby 4.15.0

> Did you hit the same Rails route or was it multiple routes?
All the tests were performed consistently with the same concurrency on 2 different routes at the same time.

> How many SQL queries were executed during the 3:30 pm - 3:45 pm time window?
We don't have exact visibility being a lower tier of our staging environments, the number should around 5000 - 7500 SQL queries in that time frame

> Did you run any worker jobs?
We did but not directly related to the web requests, during that time we had 2 jobs running. (Tokens refresh)

**Comment by kyrylo** [comment]
Thanks for the answers. Once quick question: what memory allocator do you use? Do you use jemalloc or TCmalloc?

**Comment by xantrac** [comment]
we are on Ruby 2.6.2 with the default memory allocator `gclib`

**Comment by kyrylo** [comment]
I tried to use [Rack Mini Profiler](https://github.com/MiniProfiler/rack-mini-profiler) to inspect GC stats. I used the `?pp=profile-gc` query param against a Rails page that makes a ~10 SQL requests and ~200k allocations (according to Rails logs).

I tried 3 versions of the gem: current master, current master without performance stats and v9.5.5. I made ~1000 consequent requests to a single route for every test that I performed.

I was using Ruby 2.7.1 with the default memory allocator.

Here are my results:

<details>
<summary>Current master</summary>

```
Overview
--------
Initial state: object count: 276418
Memory allocated outside heap (bytes): 44633095

GC Stats:
--------
compact_count : 0
count : 2057
heap_allocatable_pages : 0
heap_allocated_pages : 2180
heap_available_slots : 888569
heap_eden_pages : 2180
heap_final_slots : 0
heap_free_slots : 458034
heap_live_slots : 430535
heap_marked_slots : 430534
heap_sorted_length : 2180
heap_tomb_pages : 0
major_gc_count : 1013
malloc_increase_bytes : 3152
malloc_increase_bytes_limit : 32883343
minor_gc_count : 1044
old_objects : 422418
old_objects_limit : 844836
oldmalloc_increase_bytes : 3152
oldmalloc_increase_bytes_limit : 16777216
remembered_wb_unprotected_objects : 5184
remembered_wb_unprotected_objects_limit : 10368
total_allocated_objects : 59280174
total_allocated_pages : 2180
total_freed_objects : 58849639
total_freed_pages : 0

New bytes allocated outside of Ruby heaps: 758645
New objects: 8734
```
</details>

<details>
<summary>Current master (performance stats off)</summary>

```
Overview
--------
Initial state: object count: 265593
Memory allocated outside heap (bytes): 41130669

GC Stats:
--------
compact_count : 0
count : 2048
heap_allocatable_pages : 0
heap_allocated_pages : 2169
heap_available_slots : 884065
heap_eden_pages : 2169
heap_final_slots : 0
heap_free_slots : 464566
heap_live_slots : 419499
heap_marked_slots : 419498
heap_sorted_length : 2169
heap_tomb_pages : 0
major_gc_count : 1011
malloc_increase_bytes : 2704
malloc_increase_bytes_limit : 32883343
minor_gc_count : 1037
old_objects : 411469
old_objects_limit : 822938
oldmalloc_increase_bytes : 2704
oldmalloc_increase_bytes_limit : 16777216
remembered_wb_unprotected_objects : 5138
remembered_wb_unprotected_objects_limit : 10276
total_allocated_objects : 57054509
total_allocated_pages : 2169
total_freed_objects : 56635010
total_freed_pages : 0

New bytes allocated outside of Ruby heaps: 467224
New objects: 5469
```
</details>

<details>
<summary>v9.5.5</summary>

```
Overview
--------
Initial state: object count: 264950
Memory allocated outside heap (bytes): 42141720

GC Stats:
--------
compact_count : 0
count : 2048
heap_allocatable_pages : 0
heap_allocated_pages : 2088
heap_available_slots : 851069
heap_eden_pages : 2088
heap_final_slots : 0
heap_free_slots : 432278
heap_live_slots : 418791
heap_marked_slots : 418790
heap_sorted_length : 2088
heap_tomb_pages : 0
major_gc_count : 1011
malloc_increase_bytes : 3248
malloc_increase_bytes_limit : 32883343
minor_gc_count : 1037
old_objects : 410711
old_objects_limit : 821422
oldmalloc_increase_bytes : 3248
oldmalloc_increase_bytes_limit : 16777216
remembered_wb_unprotected_objects : 5146
remembered_wb_unprotected_objects_limit : 10292
total_allocated_objects : 58786070
total_allocated_pages : 2088
total_freed_objects : 58367279
total_freed_pages : 0

New bytes allocated outside of Ruby heaps: 1531306
New objects: 17617
```
</details>

I noticed that I don't see the increased amount of GC runs on my route if I change versions. I don't have access to New Relic and I am not sure how to reproduce the issue that you are seeing. Do you know how exactly New Relic collects the GC frequency stat? Maybe you know other tools that would help me in monitoring my GC stats over time? My tooling is quite limited as I don't have anything that would build me a nice graph like yours.

I would expect that performance stats might the culprit. It would be super amazing if you could repeat the experiment with `performance_stats` disabled 😃
