### ISSUE TITLE
Airbrake performance not showing api path and query

### ISSUE THREAD

**Issue by rajnish4unow** [airbrake/airbrake#1146]
**Note**: I do see errors and jobs

**Setup**
Gem: airbrake (11.0.1) and airbrake-ruby (5.2.0)

File: config/initializers/airbrake.rb
Airbrake.configure do |config|
  config.project_id  = CONFIG[:PROJECT_ID]
  config.project_key = CONFIG[:PROJECT_KEY]
  config.performance_stats = true
  config.environment = CONFIG[:APP_ENV]
end

our rails route file is as below
Rails.application.routes.draw do
  mount CanopyBackend::Base => '/'
  mount GrapeSwaggerRails::Engine => '/'
end

Debug logs I see are below. I see performance data sent on each API call but the route is sent as 'grape_swagger_rails' instead of API path and also no query captured.
---------------------------
D, [2021-02-03T16:04:29.449262 #3262] DEBUG -- : **Airbrake: Airbrake::PerformanceNotifier#send: {"routes"=>[{"method"=>"GET", "route"=>"grape_swagger_rails#/", "statusCode"=>200, "time"=>"2021-02-03T16:04:00+00:00", "count"=>4, "sum"=>4.997147, "sumsq"=>6.3509080996469995, "tdigest"=>"AAAAAkA0AAAAAAAAAAAABD+GyOc+FRO2PSCQLj6KOggBAQEB"}], "environment"=>"Dev"}
D, [2021-02-03T16:04:29.449604 #3262] DEBUG -- : **Airbrake: Airbrake::PerformanceNotifier#send: {"routes"=>[{"method"=>"GET", "route"=>"grape_swagger_rails#/", "responseType"=>:html, "time"=>"2021-02-03T16:04:00+00:00", "count"=>4, "sum"=>5.691447, "sumsq"=>8.243182999485, "tdigest"=>"AAAAAkA0AAAAAAAAAAAABD+ZrM0+Jg3MPSMn7j6lWdUBAQEB", "groups"=>{:view=>{"count"=>4, "sum"=>3.5641351714730263, "sumsq"=>3.242721298975064, "tdigest"=>"AAAAAkA0AAAAAAAAAAAABD8+Drk9zrAcPRsi2D5dJ3oBAQEB"}}}], "environment"=>"Dev"}
D, [2021-02-03T16:04:30.239519 #3262] DEBUG -- : **Airbrake: Airbrake::Response (204):

**Comment by kyrylo** [comment]
Hey there! The issue stems from GrapeSwaggerRails, from what I can tell. I am not familiar with that gem but I can see that they ask you to set a `before_action`: https://github.com/ruby-grape/grape-swagger-rails#usage

Perhaps, tweaking it could resolve your issue. To find your route we use standard Rails APIs (recognize route): https://github.com/airbrake/airbrake/blob/6860375169f120e76cea6df15991d15fe1a30e62/lib/airbrake/rails/app.rb#L15

You can inspect your app's routes with `::Rails.application.routes.routes.map(&:path).map(&:spec).map(&:to_s)`.
You may also try mounting the GrapeSwaggerRails engine at some other location in your routes file.
