### ISSUE TITLE
Integer parameter value is displayed as String on Dashboard

### ISSUE THREAD

**Issue by kyoshidajp** [airbrake/airbrake#1147]
* Airbrake version: 11.0.1
* Ruby version: 2.6.7
* Framework name & version: Ruby on Rails 6.1.3.1

#### Airbrake config

(nothing special)

#### Description

Post request with Integer parameters like this.

```
curl -H "Content-Type: application/json" -X POST -d '{"a":2}' "localhost:3001/test"
```

The target action with controller is here.

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
    params["a"] + " doller"
  end
end
```

Then, the error is shown as below.

<img width="456" alt="airbrake_parameters" src="https://user-images.githubusercontent.com/3317191/114254517-db905b80-99ea-11eb-8530-58881f780d93.png">

Why is the value of the `"a"` key displayed as `"2"` instead of  `2` ? According to the error on dashboard, I incorrectly assume it is a string.

FYI: The request body (`req.body`) in `Airbrake::SyncSender`,
https://github.com/airbrake/airbrake-ruby/blob/v5.2.0/lib/airbrake-ruby/sync_sender.rb#L37

the value is Integer.

```
...,\"params\":{\"a\":2,\"controller\":\"application\",\"action\":\"index\",\"application\":{\"a\":2}}}"
```

**Comment by kyrylo** [comment]
Thanks for reporting, @kyoshidajp. I was able to reproduce this issue. During my investigation I found out that this problem is not specific to the airbrake gem or airbrake-ruby. It appears to be an issue with our backend.

I will open an internal ticket to resolve this problem.

**Comment by kyrylo** [comment]
@kyoshidajp this was fixed, your new errors should be displayed correctly

**Comment by kyoshidajp** [comment]
@kyrylo I have confirmed that this has been fixed. Thanks.

<img width="341" alt="airbrake-fixed" src="https://user-images.githubusercontent.com/3317191/115937458-0bebf580-a4d3-11eb-9f91-484d423c74c1.png">
