### ISSUE TITLE
Filter keys in session

### ISSUE THREAD

**Issue by iamdriz** [airbrake/airbrake#1173]
In our Rails application we store some data in our session that we don't want to be visible in the error logs.

This data is stored in the session because our app is API-only (no database) and we want the data to disappear as soon as the session expires. The data is secure in the session due to it being encrypted etc.. but if an error happens we don't want these to be visible in the session data that is sent via Airbrake as part of the error logging.

We've seen that you can do filtering: https://github.com/airbrake/airbrake#integration-with-filter_parameters

But does this only cover params on requests? Or will it work in filtering out keys inside a session?

**Comment by kyrylo** [comment]
It should cover session as well:

https://github.com/airbrake/airbrake-ruby/blob/7800c7d3b30475b419d5ebe1cb46a2920741c560/lib/airbrake-ruby/filters/keys_filter.rb#L21-L23
