### ISSUE TITLE
Airbrake v11 incompatible with elastic APM gem. 

### ISSUE THREAD

**Issue by Reinkaos** [airbrake/airbrake#1174]
* Airbrake version: 11.0.3
* Ruby version: 2.7.2
* Framework name & version: Rails 6.1.3.2

#### Description

Add elastic APM and airbrake into your Gemfile

gem 'elastic-apm', '= 3.15.1' # note that v4 of elastic APM doesn't work with airbrake. 
gem 'airbrake'

bundle and then attempt to precompile:

You will get a stack level too deep like this:

```
/gems/elastic-apm-3.15.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
/gems/2.7.0/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
/gems/elastic-apm-3.15.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
/gems/elastic-apm-3.15.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
```

Using version 10.0.6 this issue does not occur.

Hope that helps!

Richard

**Comment by kyrylo** [comment]
Sorry, I am a little confused. Does Elastic APM v4 not work but v3 does or is it vice versa?
I can see in v4 they had a fix for the issue you described: https://github.com/elastic/apm-agent-ruby/commit/636319cdcdfe517757e397ba053b63cdb9ebb600

Since v11.0.3 the airbrake gem should also ship with Rake integration fixed.
I would try to reorder the gems in your Gemfile (put `airbrake` above `elastic-apm`).

**Comment by Reinkaos** [comment]
Hey thanks for getting back to me,

Yes it appears that v4 doesn't work, it results in a stack level too deep when posting data to elastic APM when Airbrake is installed as well. To fix this issue elastic APM suggest having the elastic apm gem first in the Gemfile. 

I have tried switching the gems around in the Gemfile but had issues either on precompile or on actually running the apps and getting data to come through to ElasticSearch, so far the best thing seems to be locking to specific versions like so:

```
gem 'elastic-apm', '= 3.15.1'
gem 'airbrake', '10.0.6'
```

Worst case was an issue I had this morning where one of my apps was stuck in an infinite loop, using all the CPU, going between the Elastic APM and Airbrake gems. 

Is there something that can be done about this? My colleague and I have encountered these sorts of issues between Elastic APM and Airbrake a few times now and it would be great if they could play nice together and didn't have ordering requirements in the Gemfile. 

Thanks,
Richard

**Comment by kyrylo** [comment]
When you have the following in your Gemfile:

```ruby
gem 'elastic-apm', '= 3.15.1'
gem 'airbrake'
```

What error do you see?

Alternatively, when you have this, what's the error?

```ruby
gem 'elastic-apm'
gem 'airbrake', '10.0.6'
```

**Comment by Reinkaos** [comment]
```
gem 'elastic-apm', '= 3.15.1'
gem 'airbrake'
```

`bundle exec rails assets:precompile`

Process hangs and then returns this after you manage to exit it

```
/gems/elastic-apm-3.15.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
/gems/2.7.0/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
/gems/elastic-apm-3.15.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
/gems/elastic-apm-3.15.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
```


```
gem 'elastic-apm'
gem 'airbrake', '10.0.6'
```

This way the precompile works but when running the application I get this error in the logs:

```
{"name":"puma","hostname":"api-647bf55f88-28pwl","pid":1,"level":50,"time":"2021-07-14T21:40:55.528+00:00","v":0,"msg":"{:msg=>\"[ElasticAPM] Couldn't establish connection to APM Server:\\n\\\"#<SystemStackError: stack level too deep>\\\"\"}"
```

Which goes away if I remove Airbrake from the Gemfile. 

Hope that helps!

**Comment by kyrylo** [comment]
You mentioned that in 10.0.6 the issue doesn't occur but according to your last message you can still see it with this combination:

```
gem 'elastic-apm'
gem 'airbrake', '10.0.6'
```

What combination of gems is completely bug free?

**Comment by Cervenka** [comment]
I am having the same issue in combination with elastic-apm 3.15.1

airbrake 10.0.1 works fine
airbrake 10.0.3 causes a ton of SystemStackError:  stack level too deep
airbrake 11.0 also causes a ton of those

The order of the entries in the gemfile is irrelevant. This is the case in both development and production.

@kyrylo - this is a duplicate? I was not able to find the duplicate that was solved.

Thank you

**Comment by kyrylo** [comment]
Hey, @Cervenka. It's a duplicate of https://github.com/airbrake/airbrake/issues/1080.

You need to upgrade your elastic gem to v4+.

**Comment by Cervenka** [comment]
Thank you for pointing that out. After upgrading both airbrake and elastic apm the issues are resolved.

This combination works
```
gem 'elastic-apm', '~> 4'
gem 'airbrake', '~> 12'
```
