### ISSUE TITLE
Ability to limit APM queries

### ISSUE THREAD

**Issue by nathansamson** [airbrake/airbrake#1175]
Is there a way to limit the APM queries to the server (eg so I won't hit my quota so soon)

I want to do 2 things

* Exclude some requests: eg everything where the User-Agent is a bot (I believe my app gets more hits from bing/yandex/etc... than from real users)
* Only send X% of the data (randomly, so randomly ignore100-X% of the requests). My data will not be as valuable, but I will have a pretty good overview (error requests should always be sent)

**Comment by kyrylo** [comment]
You can use the `add_filter` API: https://github.com/airbrake/airbrake-ruby#airbrakeadd_filter

They allow you to implement both your items.

**Comment by nathansamson** [comment]
Hi

that is for errors only I think. I want all errors logged. It is for APM requests I want to only send a good subset

**Comment by kyrylo** [comment]
In a similar fashion, we provide `Airbrake.add_performance_filter`: https://github.com/airbrake/airbrake-ruby#airbrakeadd_performance_filter
