### ISSUE TITLE
Add filter causing memory to increase

### ISSUE THREAD

**Issue by neohunter** [airbrake/airbrake#1176]
We wanted to add some information to alll error notification, which, I think, is a fairy common usage

According to the documentation here: https://github.com/airbrake/airbrake#rake we add a filter con en ApplicationController that was triggered on the before_action filter of rails:

```ruby
  def nourish_airbrake
    Airbrake.add_filter do |notice|
      notice[:params][:business_id] = request.headers['business-id']
      notice[:params][:controller] = params[:controller]
      notice[:params][:action] = params[:action]
      notice[:params][:id] = params[:id]
    end
  end
```

This causes production servers to increase memory consumption forever until the container finally crashes, I think documentation must be clear about how to achieve that, and warns users to do not add filters on each requests, as it got added to a filter array.

**Comment by kyrylo** [comment]
Thanks for the report. How do you measure memory consumption?

If you call `nourish_airbrake` multiple times, it'll continue adding that filter on each call. That might be the reason why you see memory bloat (you add an infinite number of filters). Filters should be added in your initializers.
