### ISSUE TITLE
Airbrake: HTTP error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by nicolas-damiani** [airbrake/airbrake#1203]
Hi!

From one day to the other, I stopped receiving error notifications on my Airbrake panel. 

After some hours of debugging I found out the error was caused by an SSL certification error. 

`{"error"=>"**Airbrake: HTTP error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"}`

Airbrake gem version 11.0.3
Ruby version 2.3.0

My SSL certificate is alright.

Thanks

**Comment by Glis** [comment]
Hello. It's also happening in our environments. We tested it like this:
``` bash
RAILS_ENV=production bundle exec rake airbrake:test
Error: **Airbrake: HTTP error: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```
We tested it on multiple projects with different versions, and all fail equally.
It might be the same problem as of this [old issue](https://github.com/airbrake/airbrake/issues/1095)

**Comment by tswetonic** [comment]
Thanks for opening this. We're seeing the same problem.

**Comment by kyrylo** [comment]
This should be resolved now. Thanks for posting the issue.
