### ISSUE TITLE
Airbrake does not track DB queries with MongoDB

### ISSUE THREAD

**Issue by nthatcher-airbrake** [airbrake/airbrake#1215]
@thompiler 
Customer- 
From what I remember, I’ve never seen queries displayed in APM for my app routes. Looks like queries are just being categorized as “other”
could this have anything to do with us using mongo (and the mongoid gem)?

Looks like they are not seeing any Queries for any of the Routes. This applies to all performance routes.
He mentioned that they are using MongoDB, which may have an effect on the way we capture Queries.
Note: They currently use Skylight for APM and when he was showing me the routes through that platform, they also were not showing any Queries from the DB, so my guess is that the issue is not originating from Airbrake, but rather from the connection between APM providers like Airbrake and MongoDB

**Comment by nthatcher-airbrake** [comment]
Slack message reference: https://logicmonitor.slack.com/archives/C01RX4XH9DY/p1648075835443179

**Comment by kyrylo** [comment]
Yes, we don't support MongoDB. We rely on Rails to provide us with a query body, and apparently it doesn't support MongoDB query bodies.
