### ISSUE TITLE
Async logging doesn't work out of the box with application servers that prefork

### ISSUE THREAD

**Issue by fcheung** [airbrake/airbrake#122]
If you put
``` ruby
Airbrake.configure do |config|
  config.api_key = 'xxx'
  config.async = true
end
```
in an initializer, as the docs suggest and your setup preloads the apps and then forks workers (unicorn, passenger) then error notifications aren't sent. This is because Airbrake.configure sets up the girl friday work queue, which spawns a thread. When the app server forks, only the main thread is copied over to the child process, so the thread servicing the girl friday queue doesn't exist in the new thread and the exceptions are silently dropped

There are a few workarounds to this, for example configuring in after_for block or creating the girl friday queue on demand   (There is an example of this on the [girl friday](https://github.com/mperham/girl_friday/issues/47) issues page)

Given that what are probably the 2 most popular rails deployment solutions (95% according to the [recent survey](http://rails-hosting.com/Results/html-2012/SurveySummary.html)) require one of these workarounds it should at very least be mentioned in the docs. Preferably airbrake would take care of this by itself

**Comment by kyrylo** [comment]
My only advice here is to use the synchronous mode, because `fork` kills all background threads.

```ruby
worker = Thread.new do
  loop do
    sleep 10
  end
end

puts "Current pid (pre-fork): #{Process.pid} | worker.alive? #=> #{worker.alive?}" #=> true
puts "---"
fork
puts "Current pid (after-fork): #{Process.pid} | worker.alive? #=> #{worker.alive?}" #=> false
```

Output:

```
Current pid (pre-fork): 7973 | worker.alive? #=> true
---
Current pid (after-fork): 7973 | worker.alive? #=> true
Current pid (after-fork): 7976 | worker.alive? #=> false
```

As you can see, our original `worker` thread (on `master` process) is alive. However, when we `fork` the `child` process kills it. That's why async delivery doesn't work: the workers are dead.
