### ISSUE TITLE
Airbrake and ruby 3.1 versions, change display of ErrorHighlight errors

### ISSUE THREAD

**Issue by kos1kov** [airbrake/airbrake#1230]
Hello, is there any way to change the error display.
i.e. use a different format for text output
 
<img width="1109" alt="Screenshot 2022-06-09 at 15 50 27" src="https://user-images.githubusercontent.com/35836663/172851168-85ad6da3-0243-4c08-9ec6-8e661ee0f403.png">
i want to see something like that
<img width="1087" alt="Screenshot 2022-06-09 at 15 52 36" src="https://user-images.githubusercontent.com/35836663/172851372-ee430ff3-162a-4449-9fea-96a286763c60.png">

**Comment by kyrylo** [comment]
Hey there. No, it's not currently possible. Just to clarify, do you want to see the raw string with visible `\n` characters?

By the way, this issue tracker is for our Ruby library. Therefore, I am closing this issue. For general questions, please, contact support@airbrake.io

**Comment by kyrylo** [comment]
Hi again @kos1kov. I released airbrake-ruby v6.1.1. It strips out the error highlighting part of the error message. The raw error message with highlighting can be found at `context/error_message`.

**Comment by kos1kov** [comment]
thanks so much @kyrylo
