### ISSUE TITLE
Premature notification in Airbrake::Sidekiq::RetryableJobsFilter

### ISSUE THREAD

**Issue by dgsangoma** [airbrake/airbrake#1239]
We've set a global Sidekiq default of 5 for `max_retries`, but overridden that in the code for particular jobs to be higher like in the `ProgressWorker` job referenced below that has been increased via the option `sidekiq_options retry: 60`. In the example Parameters section below from an example Airbrake, you can see the following values that I think indicates the Airbrake notification shouldn't have been sent:

```
    "retry": 60,
    "retry_count": 5
```

Is it possible there's a bug in `RetryableJobsFilter` where it gets confused and defers to the global default `max_retries` instead of the per-job value?

In `config/initializers/airbrake.rb`, we have the `RetryableJobsFilter` enabled as follows:
```
...
require "airbrake/sidekiq"
...
Airbrake.add_filter(Airbrake::Sidekiq::RetryableJobsFilter.new)
```

Sample parameters:
```
{
  "job": {
    "args": [
      "969e17f3-e624-4630-abfe-6b614dd34db2",
      "2022-10-05T23:36:55+00:00",
      "2022-10-06T00:36:55+00:00",
      "wj0m3m5gbhozmpzt",
      "102617"
    ],
    "class": "ProgressWorker",
    "created_at": 1665013183.505255,
    "enqueued_at": 1665013645.800618,
    "error_class": "InProgressError",
    "error_message": "InProgressError",
    "failed_at": 1665013187.0334604,
    "jid": "fcf2ff69cde5365afdd0445a",
    "queue": "default",
    "retried_at": 1665013579.586878,
    "retry": 60,
    "retry_count": 5
  }
}
```

Environment:
```
{
  "program_name": "sidekiq 6.4.2 app [1 of 10 busy]"
}
```

Context:
```
{
  "action": "ProgressWorker",
  "component": "sidekiq",
  "environment": "production",
  "error_message": "InProgressError",
  "hostname": "bb694925539f",
  "language": "ruby/3.1.2",
  "messageParams": {
    "0": "InProgressError"
  },
  "messagePattern": "{}",
  "notifier": {
    "name": "airbrake-ruby",
    "url": "https://github.com/airbrake/airbrake-ruby",
    "version": "6.2.0"
  },
  "os": "x86_64-linux",
  "remoteAddr": "[REDACTED]",
  "remoteCountry": "United States",
  "remoteCountryCode": "US",
  "rootDirectory": "/usr/src/app",
  "severity": "error"
}
```

**Comment by kyrylo** [comment]
We read `max_retries` from Sidekiq class directly. If that's not configured, we use `Sidekiq::JobRetry::DEFAULT_MAX_RETRY_ATTEMPTS`:

https://github.com/airbrake/airbrake/blob/6ca4b6023d56dba214b55f649743b41fa4934edf/lib/airbrake/sidekiq/retryable_jobs_filter.rb#L49

It's quite possible that we don't take into account `sidekiq_options retry: 60`.

**Comment by kyrylo** [comment]
> It's quite possible that we don't take into account sidekiq_options retry: 60.

I couldn't confirm this. In your sample params, I can see the correct `retry` value (`"retry": 60,`). After reading the code and testing, I can see that we do respect the per-job retry option.

https://github.com/airbrake/airbrake/blob/6ca4b6023d56dba214b55f649743b41fa4934edf/lib/airbrake/sidekiq/retryable_jobs_filter.rb#L41-L42

I used the following code to test:

```rb
require 'sidekiq'
require 'airbrake'

::Sidekiq.options[:max_retries] = 1

Airbrake.configure do |c|
  c.project_id = 1
  c.project_key = 'asd'
  c.logger = Logger.new(STDOUT)
  c.performance_stats = false
  c.remote_config = false
end

Airbrake.add_filter(Airbrake::Sidekiq::RetryableJobsFilter.new)

class TestWorker
  include Sidekiq::Job
  sidekiq_options retry: 3
  sidekiq_retry_in do |count|
    5
  end

  def perform(name)
    p "Hey #{name}"
    raise
  end
end

TestWorker.perform_async('Joe')
```

Could you please provide a demo worker that demonstrates the problem that you mentioned?

**Comment by dgsangoma** [comment]
I'll work on putting together a minimal setup that is able to reproduce the issue.

**Comment by kyrylo** [comment]
Gentle ping @dgsangoma.

**Comment by dgsangoma** [comment]
I've made a small test app to try to reproduce the issue, but am struggling to reliably reproduce the issue in the test app.

**Comment by kyrylo** [comment]
Thanks! Could share the app and the instructions on how to run it? I can clone it and run it multiple times to see how it fails.

**Comment by dgsangoma** [comment]
I should clarify that I'm not sure I've managed to reproduce the issue yet in a small test Rails app, so there's some key detail about our production app that's missing from the test app that's required to reproduce the bug. I can confirm we're still seeing it intermittently in production on airbrake 13.0.3 / airbrake-ruby 6.2.0. I'll need to keep trying things to see if I can uncover what's missing that's required unless you have any suggestions for getting more insightful info out of our production app.

**Comment by kyrylo** [comment]
I don't really have any debugging tips for you. By manual code inspection, it should work, but I am not a Sidekiq user, and I don't have a profound knowledge of it. Maybe you defined some sort of Sidekiq config that alters the behavior.

If you take a look at the example I shared above, does it look the same as your workers?

**Comment by dgsangoma** [comment]
My worker is part of a large Rails app as opposed to a single file standalone worker like the example above. Global sidekiq configuration is managed in our app via a yml config file. We have `require "airbrake/sidekiq"` at the top of our Airbrake initializer. We've defined the `sidekiq_retries_exhausted` callback to do additional failure handling on the final retry.  I'm sure there's other differences that are less obvious.

I guess I'll continue to experiment and maybe eventually I'll stumble onto the bug.
