### ISSUE TITLE
Airbrake 13 SystemStackError:stack level too deep

### ISSUE THREAD

**Issue by Nandez89** [airbrake/airbrake#1240]
After upgrading from airbrake `10` to `13` our application starts throwing `SystemStackError:stack level too deep` errors. 
(Update) narrowed down to `10` to `11` upgrade

I checked all previous issues and the solutions... but they all deflect into to updating other gems instead (https://github.com/airbrake/airbrake/issues/395, https://github.com/airbrake/airbrake/issues/1080, https://github.com/airbrake/airbrake/issues/1171, https://github.com/airbrake/airbrake/issues/1141, https://github.com/airbrake/airbrake/issues/612), some of which we do not use so those solutions don't work for us. 

Changing the order didn't work either, updating other dependencies should not be the solution to errors caused only when updating the `airbrake` gem. 

What has changed in the gem that makes the stack behave differently, did the logging levels change? Is there a new setting that allows disabling this behavior instead of having to upgrade all other dependencies? sometimes it might not be possible.

We use bundler, previous state: 
`gem 'airbrake', '~> 10.0'` 

lock: 
```
airbrake (10.0.6)
  airbrake-ruby (~> 4.13)
airbrake-ruby (4.15.0)
```

Current state with error: 
`gem 'airbrake', '~> 13.0'` 

lock:
```
airbrake (13.0.3)
  airbrake-ruby (~> 6.0)
airbrake-ruby (6.2.0)
```

**Comment by kyrylo** [comment]
Hey, Daniel! Do you have an example backtrace with a SystemStackError? It's a bit hard to debug this without knowing where exactly this happens.

**Comment by kyrylo** [comment]
Thanks for the extra details.

The reordering trick is necessary if you use other tools that mess with Rails internals or hook into their APIs. If you don't use anything like that, then it has no effect.

I think it may be something with your setup or code. If there was a SystemStackError that had been raised consistently, more users would complain. So far, I haven't heard any similar reports.

The backtrace doesn't seem to be useful to debug this issue. Is there any chance for you to upgrade the gem gradually? From 10 to 11, from 11 to 12. I might be able to pinpoint the messy version.

The failing line is this one:
https://github.com/airbrake/airbrake/blob/6ca4b6023d56dba214b55f649743b41fa4934edf/lib/airbrake/rack/middleware.rb#LL34

Perhaps, there's something wrong inside your Rack env object that we try to read.

**Comment by kyrylo** [comment]
Thanks for pinpointing the version. That is really helpful.

There were a lot of moving parts under the hood when comparing v10 to v11, so more investigation work is required.
* Do you use the default Airbrake config or do you have custom filters? Can you share it?
* Do you see this error locally?
* What does the line of code that crashes do?

> When you say there might be something wrong on our side, I can try and fix it but would need more guidance about what to look for

Since the backtrace shows that the error occurs inside a model and you use `bullet`, it makes me think that `bullet` does something funky. I can see that the gem [monkey-patches](https://github.com/flyerhzm/bullet/blob/master/lib/bullet/active_record60.rb) a lot of Rails internals. This frequently opens a can of worms. That said, at a cursory glance, their approach looks harmless.


> Is there anything I can check or disable to change the behavior of that call to rack via airbrake?

You've mentioned the following:
    > Tried removing some we can get away with not using like bullet.

What I understood is that you removed the gem, tried to run the app, and yet saw the error. Is this correct?

**Comment by Nandez89** [comment]
> * Do you use the default Airbrake config or do you have custom filters? Can you share it?

I can't share code snippets unfortunately :/ but I can try and describe them in as much detail as possible. 
- We have the project id and key defined in the environment via env variables loaded by `airbrake.yml` file.
- The `airbrake.rb` initializer only sets one config that is a list of **blocklist_keys**
- We add a filter from airbrake rack (Airbrake::Rack::HttpHeadersFilter)
- We have a custom filter that checks for `notice[:errors]` comparing different types and calls `notice.ignore!` if we want to skip the errors.

> * Do you see this error locally?

Yes, this stack is an error we see locally. 
But... I've also gotten a different stack with the same error on the CI test setup. I will share that one at the bottom of the answers too hopefully it helps narrow down more.

> * What does the line of code that crashes do?

The line of code in the model is an after_find callback that adds attributes to the model via `self.attributes = ...`
 
> What I understood is that you removed the gem, tried to run the app, and yet saw the error. Is this correct?

This is correct I have tried it and even after removing the **bullet gem** entirely we still see the error locally.

**The other CI stack:** 
I know it is a different stack but also ends in `SystemStackError:stack level too deep` so it might help narrow down the issue:
```
# this last 4 lines loop in repeat until the error
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/bundler/gems/INTERNAL_GEM/request_id_propagation.rb:45:in `request'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/airbrake-13.0.3/lib/airbrake/rails/net_http.rb:11:in `block in request'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/airbrake-13.0.3/lib/airbrake/rack.rb:25:in `capture_timing'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/airbrake-13.0.3/lib/airbrake/rails/net_http.rb:10:in `request'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/net_http/connection_pool.rb:348:in `request'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/net_http/handler.rb:79:in `block in transmit'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/net_http/handler.rb:133:in `block in session'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/net_http/handler.rb:128:in `session'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/net_http/handler.rb:76:in `transmit'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/net_http/handler.rb:50:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/plugins/content_length.rb:24:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/plugins/request_callback.rb:85:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-dynamodb-1.60.0/lib/aws-sdk-dynamodb/plugins/crc32_validation.rb:32:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/json/error_handler.rb:10:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/signature_v4.rb:58:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/http_checksum.rb:19:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/json/handler.rb:13:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-dynamodb-1.60.0/lib/aws-sdk-dynamodb/plugins/simple_attributes.rb:119:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.130.1/lib/seahorse/client/request.rb:72:in `send_request'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/aws-sdk-dynamodb-1.60.0/lib/aws-sdk-dynamodb/client.rb:2730:in `describe_table'
/home/semaphore/accounts/app/services/aws/dynamodb_service.rb:63:in `table_exists?'
/home/semaphore/accounts/lib/MY_TASK:10:in `block in create_user_profiles_tables'
/home/semaphore/accounts/lib/MY_TASK.rake:8:in `each'
/home/semaphore/accounts/lib/MY_TASK.rake:8:in `create_user_profiles_tables'
/home/semaphore/accounts/lib/MY_TASK:59:in `block (3 levels) in <top (required)>'
/home/semaphore/accounts/vendor/bundle/ruby/2.7.0/gems/airbrake-13.0.3/lib/airbrake/rake.rb:17:in `execute'
/home/semaphore/accounts/lib/MY_TASK.rake:70:in `block in <top (required)>'
```

**Comment by kyrylo** [comment]
Thanks for the extra info! I can see that your new backtrace includes `aws-sdk-core-3.130.1/lib/seahorse/client/net_http`.

I checked how they monkey-patched `Net::HTTP` and it looks safe. Could you bump `aws-sdk-core` to the latest version and see if that helps? Maybe the older version contained a bug? My gut tells me some dependencies of yours cause this issue, not the Airbrake gem, but I don't have data to prove this.

> The airbrake.rb initializer only sets one config that is a list of blocklist_keys

Since you can reproduce the problem locally, could you set `blocklist_keys` to `[]` so that the library doesn't filter out anything?

> We add a filter from airbrake rack (Airbrake::Rack::HttpHeadersFilter.new) with no custom behavior

Could you comment out that line and run the app without that filter?

> We have a custom filter that checks for notice[:errors] comparing different types and calls notice.ignore! if we want to skip the errors.

Could you comment out that code?

It would be perfect if you could test these scenarios separately. I am not sure if this will help, but so far I don't have any good clues.

**Comment by Nandez89** [comment]
I tried the suggested changes one at a time, commenting out each section, and then removing all configurations at once. in all cases, the local issue still happens. 

I also tried updating `aws-sdk-core` latest `3.168.3` and that updates a few of the individual service packages, but I see the same result.

> My gut tells me some dependencies of yours cause this issue, not the Airbrake gem, but I don't have data to prove this. 

This is hard because in our changes the only one is updating airbrake, so it's definitely airbrake's interaction with any of the other gems, but I can't update all dependencies blindly until things work again, it's a higher risk that other things would break this way.

> I checked how they monkey-patched Net::HTTP and it looks safe 

Could you tell me what you look for here specifically? maybe I can search in the local gem installation for "unsafe" usages and try to identify the issue that way...

**Comment by kyrylo** [comment]
> Could you tell me what you look for here specifically?

I look for `eval` calls or "unsafe" class reopenings (reopening a class and redefining a method). That kind of stuff messes up our expectations when multiple gems monkey-patch the same thing. Here's an older reply of mine: https://github.com/airbrake/airbrake/issues/1080#issuecomment-609569006

People should be using `prepend` for monkey-patching, so that everyone can hook into the existing API and not break the code of others.

Your particular case doesn't look like it's the same issue, though. Even though the second backtrace indicates it could be (because Net::HTTP doesn't behave like we expected), the error from the first backtrace is new to me. I can't remember seeing an error coming from that class. It survived without bugs for 2 years.

**Comment by kyrylo** [comment]
This is completely unrelated, but we were developing the "remote config" feature during the `airbrake-ruby` v5.0.0 times. I would try to disable it to see if it changes anything. I doubt it, but it's worth a shot because, at the moment, I have no better options.

```rb
Airbrake.configure do |c|
  c.remote_config = false
end
```

**Comment by Nandez89** [comment]
I tried disabling the remote configs but the same issue happens.
 
After searching the other suggestion I did see some `Net::HTTP.class_eval` block on our 
```
/MY_REPO_FOLDER/.bundle/ruby/2.7.0/bundler/gems/CUSTOM_MIDDLEWARE.rb:10:in `call'
```

So I will try and coordinate to issue a fix patch for that custom middleware to use prepend (separate team and project 😅) and update the status here if that solves the issue. If you think of anything else I can try in the meantime please let me know 👍

**Comment by kyrylo** [comment]
Thanks Daniel! Just ping me if you still experience any issues.
