### ISSUE TITLE
How can I filter out a cookie(s) or session data while sending errors from app?

### ISSUE THREAD

**Issue by ryan3707** [airbrake/airbrake#185]

**Comment by mmplisskin** [comment]
Are there any updates to this? I think it should be mandatory to allow blacklisting of session and cookie values.

**Comment by kyrylo** [comment]
@mmplisskin yeah, you can use [`Airbrake.add_filter`](https://github.com/airbrake/airbrake-ruby#airbrakeadd_filter) now.
