### ISSUE TITLE
Sending custom informations

### ISSUE THREAD

**Issue by simonc** [airbrake/airbrake#191]
Hi,

I'm looking for a way to pass custom context variables in every error notice but I don't know if it's possible.

My use-case is the following:

* I'm getting an error with an often visited url that is not supposed to exist
* This url it nowhere to be found on the site
* It's not indexed in google
* If I had the error page `Referer` I could see where it comes from

Is there any way to get to that point? Having a custom information like the `Referer` sent with any error notification ?

Thanks :)

**Comment by kyrylo** [comment]
Hello, @simonc! I am sorry that we haven't resolved this yet. Based on the activity in this issue I can conclude that not many people are interested in this feature. I was curious, are *you* still interested in this? If not, I believe we could close this.

**Comment by simonc** [comment]
Hi @kyrylo :)
It can be closed, I'm not in the company needing it anymore ;)
