### ISSUE TITLE
Don't hook into Capistrano pipeline.

### ISSUE THREAD

**Issue by oggy** [airbrake/airbrake#252]
It would be nice to make use of the cap task that ships with this gem in even slightly nonstandard setups. In our case, we would like to only conditionally (based on a variable set in another task) run the Airbrake hook - something we cannot do when it hooks itself into the pipeline.

More generally, it seems a little overpresumptive on Airbrake's part to assume this is exactly how you want to hook it in. It's great that it works in simple cases, but it's not great that it leaves you no alternative.

There are many ways one could tackle this - the one I propose is to split out the task itself into a separate file. Then you could either:

    require 'airbrake/capistrano'        # automagic, like now
    require 'airbrake/capistrano/tasks'  # DIY mode - skips the #after calls

The first would simply do the second and then make the `after` calls.

Would you accept a patch that does this? Preferred alternative?

Thanks!

**Comment by shifi** [comment]
@oggy you're talking about Capistrano 2 or Capistrano 3?
We made few changes related to Capistrano hooks in new gem version (4.2.0).
Seems like this issue is pretty much outdated so I will close it for now.
Feel free to reopen it if you still have any issues.
Thank you.
