### ISSUE TITLE
Add Sidekiq support

### ISSUE THREAD

**Issue by mperham** [airbrake/airbrake#269]
I'm going to drop native support for error handlers in Sidekiq 3.0, so as to not play favorites and give each error service full control over their own implementation.  This includes Airbrake so you'll need to ship your own Sidekiq 3.0 support.

To be clear, I'll be removing this line:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/exception_handler.rb#L12

BugSnag has a sample implementation for their integration here:

https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/sidekiq.rb

3.0 has no set release date so you should have plenty of time.

**Comment by nburt** [comment]
I'm using Airbrake 4.3.1 with Sidekiq 3.4.2 and Rails 4.2.3 and I'm not getting any errors reported. When I use Pry within a Sidekiq worker `Sidekiq.error_handlers` only returns the standard Sidekiq error logger. I've tried adding @cwholt's code in an initializer but that hasn't worked either. If I copy/paste that config block into the Pry console it does add the Airbrake error handler and correctly posts the error.

Has anyone encountered something similar or have any ideas as to what could be happening?

**Comment by felixbuenemann** [comment]
@nburt The integration should be loaded automatically. Maybe airbrake is listed before sidekiq in your Gemfile? Try re-ordering so sidekiq comes first or add an initializer which contains:
```ruby
require "airbrake/sidekiq"
```

**Comment by kyrylo** [comment]
@nburt, feel free to file a new issue if you believe this is a bug in our gem

**Comment by nburt** [comment]
Thanks @felixbuenemann. I did have airbrake listed after sidekiq, I just tried adding the require to no avail. @kyrylo, I've filed a new issue here: https://github.com/airbrake/airbrake/issues/423
