### ISSUE TITLE
Builder gem namespace conflicts

### ISSUE THREAD

**Issue by tomharrisonjr** [airbrake/airbrake#276]
We ran into a problem today integrating the Airbrake gem into a new app we're getting ready to deploy -- our code has a class named `Builder` in a module called `Search`.  We were referencing it as `Builder` in our code, and getting an error because ruby was picking up the other `Builder`.  

We have worked around the problem by qualifying our namespace as `Search::Builder`, but this seems like such a common name (used in Rails in several contexts, in fact).  I wonder if there's a way to replace or namespace the gem's usage?

**Comment by Benjamin-Dobell** [comment]
Why is Airbrake polluting the global namespace? Having global modules with generic names like ```Client``` is a recipe for disaster.

**Comment by kyrylo** [comment]
I agree that this doesn't look normal. We're planning a major release of the library and we won't have this problem, because there will be no CLI. We're removing it, and leaving the Rake task, which does the same.
