### ISSUE TITLE
notify_airbrake() method does not work

### ISSUE THREAD

**Issue by alexey** [airbrake/airbrake#278]
In my controller i've put notify_airbrake(some_error_as_string) but it does not send any notification.

In production mode, it do send regulard exceptions.

**Comment by brian-vogogo** [comment]
FYI `notify_airbrake` will never send notifications locally. 

It skips sending notifications regardless of config.development_environments: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/controller_methods.rb#L22
