### ISSUE TITLE
Sensitive credentials exposed by default on Heroku when sending error from rake task to Airbrake

### ISSUE THREAD

**Issue by Soleone** [airbrake/airbrake#279]
This issue might be related to https://github.com/airbrake/airbrake/issues/253 which unfortunately had no description.

We noticed today in a couple of our apps hosted on heroku that sensitive credentials were exposed to all Airbrake users. In our case we have over a hundred people in the company with access to our Airbrake server to browse exceptions.

It looks like by default when an error gets raised in a rake task it's handled slightly differently than errors in the app itself: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rake_handler.rb#L30-L34

So by default the whole heroku environment (which is normally used to store credentials like the `DATABASE_URL`) gets stored in Airbrake/Errbit.

Should this maybe changed to a whitelist approach as opposed to blacklist? Otherwise in all of our apps we now have to start maintaining a (different) blacklist of filtered environment variables just for rake tasks that shouldn't get reported. Considering Airbrake is probably used in a lot of Heroku apps right now with no mention of this in the set up instructions (neither mentioned in https://github.com/airbrake/airbrake/wiki/Using-Airbrake-with-Rake or https://github.com/airbrake/airbrake/wiki/Filtering-data-before-it%27s-sent-to-Airbrake) I assume there's a lot of "leaked" credentials right now in various mongodbs (where to my knowledge the exception details are stored).

Let me know in case you need any more details or want to discuss this.

**Comment by shifi** [comment]
@Soleone errors from rake tasks should be filtered like errors from the app itself so this is definitely something I'm planning to fix. I will also make rack vars filters configurable.

**Comment by Soleone** [comment]
awesome thanks a lot for putting it on the roadmap!

**Comment by kyrylo** [comment]
@Soleone howdy! From my understanding, you're only worried about environment variables being exposed, aren't you? If that is so, do you find environment variables useful for debugging at all? Do you think we can ignore all of them and never expose any env variable?

**Comment by Soleone** [comment]
I'm sorry, I totally forgot to reply here:

Yes, on Heroku environment variables usually contain sensitive information so they can't be exposed.

I'd suggest ignoring them by default and being able to opt-in (either to all, or only specific keys) is a better out-of-the-box behaviour than exposing all.

**Comment by kyrylo** [comment]
Thanks for your answer! We're preparing a new major release. You will be able to opt-in with the following code:

```ruby
Airbrake.add_filter do |notice|
  notice[:environment] = ENV
end
```

**Comment by Soleone** [comment]
Nice! Just to clarify: does that mean you're changing the current behavior and by default the `ENV` is not included, you explicitly have to opt-in to expose it?

**Comment by kyrylo** [comment]
Correct, by default it's not included anymore.

**Comment by Soleone** [comment]
Lovely, thanks a lot :+1:
