### ISSUE TITLE
re-enable sending/storing cookies with airbrakes

### ISSUE THREAD

**Issue by alexch** [airbrake/airbrake#284]
https://github.com/airbrake/airbrake/issues/185 and https://github.com/airbrake/airbrake/commit/c9098b13342de17b252b373c7af94e9f2f30b383 removed cookies, sessions, and some other "sensitive" information from airbrakes. While in some cases this information is important to remove, in others it is important to include. (For instance I just had an issue where a number of customers had an "invalid UTF-8 sequence" in a cookie that my app set; seeing the actual value of that cookie would have helped me track down the bug.)

I suggest enabling sending cookies again by default, and/or adding an explicit configuration setting to enable/disable cookies, rather than the current code using the SENSITIVE_RACK_VARS constant with no (apparent) supported way to modify it.

**Comment by shifi** [comment]
@alexch I will make rack vars filters configurable this week.
I will keep you updated.

**Comment by kyrylo** [comment]
We plan a major release, where by default we send this information. You indeed will be able to filter this information by yourself.
