### ISSUE TITLE
Not Getting the Error ID on using Airbrake.notify_or_ignore

### ISSUE THREAD

**Issue by abibullah** [airbrake/airbrake#291]
In my ruby code I am using the `Airbrake.notify_or_ignore` to send an error to airbrake. In response I am getting the Notice ID but not the Error ID. In my app I need  to form the complete url which requires both Notice ID and Error ID. 

In Wiki, I see this: 
`env['airbrake.error_id'] = Airbrake.notify_or_ignore`

So I was expecting it to be error Error ID. Now, How can I access the Error ID?

**Comment by shifi** [comment]
@abibullah I'm not sure I understand you. Notice ID is error ID so this should be the same.
This issue is pretty outdated so I will close it. Feel free to reopen it if you still have any issues.
For other questions I recommend you to open ticket [here](https://help.airbrake.io). Thank you!
