### ISSUE TITLE
cannot set deployed by using airbrake command line?

### ISSUE THREAD

**Issue by concept47** [airbrake/airbrake#296]
Not sure if this is an oversight or intentional.
but it doesn't seem that you can use

    airbrake deploy -k apikey -E environment ... etc

to write **who** deployed the app. -r will get me the revision, -E sets the environment -k will get the right app to write to, but I can't find any option that writes who kicked off the deployment. 

It looks like it is set by a 'local_username' parameter in the api that the [default cli options don't set](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/cli/options.rb) and so never pass through to the [create_deploy cli call](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/cli/client.rb#L31)

**Comment by diclophis** [comment]
I am running into this same issue, the command line application does not pass all of the allowable arguments through to the deploy create api call...

**Comment by shifi** [comment]
@concept47 @diclophis thanks for reporting this issue. I will take a look tomorrow.
Thank you for your patience.

**Comment by shifi** [comment]
@concept47 @diclophis I just fixed this. If you use edge version, you can set who deployed app using flags `-u` or `--local-username` or using ENV `ENV["USER"]`.
I also added `scm_repository`. For more info, just hit `airbrake -h` from your app.
I will update wiki pages soon.
Thanks again guys.

**Comment by diclophis** [comment]
great!
