### ISSUE TITLE
String as argument when Hash is expected

### ISSUE THREAD

**Issue by carlosgaldino** [airbrake/airbrake#309]
Hi,

The documentation for [`Airbrake.notify`](http://rubydoc.info/gems/airbrake/3.1.16/Airbrake.notify) says that `rack_env` should be a `String` but when creating a `Notice` the library will use [either this `String` that was given or a default value which is a `Hash`](https://github.com/airbrake/airbrake/blob/v3.1.16/lib/airbrake/notice.rb#L119).

Later on, the library will use this value and clean it but the cleaner [expects a `Hash`](https://github.com/airbrake/airbrake/blob/v3.1.16/lib/airbrake/utils/params_cleaner.rb#L70-L78).

My problem is that I'm calling `Airbrake.notify` and passing a `String` as the documentation says and as expected (after reading the code) I'm getting a `NoMethodError` when the library calls `each` on the given `String`.

So, `rack_env` is really a `String`? Am I doing something wrong here?

**Comment by shifi** [comment]
@carlosgaldino it's been a while since you opened this issue. So sorry nobody respond to you sooner.
Do you still have this issue?

**Comment by shifi** [comment]
@carlosgaldino I'm going to close this one. Feel free to reopen it if you still have any issues.

**Comment by carlosgaldino** [comment]
@shifi Yes. I'm now unable to check it but if I find the same problem I will let you know. Thanks.
