### ISSUE TITLE
UninitializedConstant on Async Worker Class during Deploy Notification

### ISSUE THREAD

**Issue by bryanrite** [airbrake/airbrake#311]
Hello!  I've recently upgraded to Capistrano 3, and my Airbrake config broke during deploy notifications.  I use Sidekiq as an async error pusher and configured my initializer as described in the wiki (https://github.com/airbrake/airbrake/wiki/Using-Airbrake-asynchronously).

This works fine for the actual running app (it pushes exceptions to Airbrake), but when doing a deploy, and reaching the deploy notification task, it throws an exception on the async worker: `Uninitialized Constant AirbrakeDeliveryWorker`.

If I manually load that file:

```ruby
# initializers/config/airbrake.rb
require File.expand_path('../../../app/workers/airbrake_delivery_worker.rb', __FILE__)
...
```

It loads the worker ok, but since that worker includes `Sidekiq::Worker`, it initializes Sidekiq as well, which causes other problems...

All this worked fine in Capistrano 2.

Anything I should be doing differently to define the async job handler? Load it in a `Proc` or something, so it isn't evaluated during deploy notifications?

Thanks!

**Comment by emcgee** [comment]
We're encountering the same issue upon upgrading to Capistrano 3: 

Capistrano is throwing `Uninitialized Constant AirbrakeDeliveryWorker` on deploy when attempting to send async via Sidekiq.

@benarent - any possible ideas on this? Happy to provide the PR if you'll light the way a bit.

**Comment by benarent** [comment]
@emcgee I'm sending around to team for an update.

**Comment by emcgee** [comment]
@benarent Just following up on this.

**Comment by shifi** [comment]
@emcgee this is still an issue for you? Any suggestions how to reproduce/fix it?

**Comment by shifi** [comment]
@emcgee @bryanrite This is pretty outdated so I will close it.
If this is still an issue for you, feel free to reopen it.
Thank you.
