### ISSUE TITLE
Rails 2.3 compatability

### ISSUE THREAD

**Issue by bkosborne** [airbrake/airbrake#319]
I'm wondering if this gem is still compatible with Rails 2.3? The README indicates it is, but after adding the gem to my Gemfile and installing, then running 

`bundle exec script/generate airbrake --api-key xxx`

I get the following output (after running the second time):

```
      exists  lib/tasks
   identical  lib/tasks/airbrake_tasks.rake
      insert
Dir[File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'airbrake-*')].each do |vendored_notifier|
  $: << File.join(vendored_notifier, 'lib')
end

require 'airbrake/capistrano'
 appended to config/deploy.rb
undefined local variable or method `configuration_output' for #<Rails::Generator::Commands::Create:0x10522e498>
```
And my `config/initializers/airbrake.rb`, while created, is blank.

I do realize that 2.3 is long gone and it may be a stretch to get support for it.

**Comment by letronje** [comment]
Has this been fixed ?

**Comment by kyrylo** [comment]
@letronje no, unfortunately not. I'd be happy to merge a patch if you're interested.
