### ISSUE TITLE
Generator should generate correct capistrano integration

### ISSUE THREAD

**Issue by severin** [airbrake/airbrake#324]
At the moment, the generator probably assumes capistrano v2 and always adds this integration. The generator should check the capistrano version and install the correct integration.

for cap v2:
```ruby
require './config/boot'
require 'airbrake/capistrano'
```

for cap v3:
```ruby
require 'airbrake/capistrano3'
after :"deploy:restart", "airbrake:deploy"
```

**Comment by michaelachrisco** [comment]
Just ran into this problem myself. Confirmed issue:
```
cap aborted!
NoMethodError: undefined method `instance' for Capistrano::Configuration:Class
```

**Comment by nicolas-besnard** [comment]
We should send them a notification through Airbrake \o/

**Comment by shifi** [comment]
Sorry guys for waiting so long :(
It's fixed now!

**Comment by severin** [comment]
@shifi thanks!
