### ISSUE TITLE
give precedence to rails_env than rack_env in deployment notification

### ISSUE THREAD

**Issue by mintuhouse** [airbrake/airbrake#332]
In [capistrano.rb](https://github.com/airbrake/airbrake/blob/5e50f6233bb5d82aa827fa2890d82deafa8f7d94/lib/airbrake/capistrano.rb#L76)
```
airbrake_env = fetch(:airbrake_env, rack_env || rails_env)
```
I feel it should be 
```
airbrake_env = fetch(:airbrake_env, rails_env || rack_env)
```
as rails_env is more commonly set inside cap script than rack_env. If rack_env is not set, It is forcing all deployments to be notified as production
Even better alternative would be something like
```
airbrake_env = fetch(:airbrake_env, fetch(:rails_env) || fetch(:rack_env) ||  "production")
```
Without assigning any individual defaults

**Comment by shifi** [comment]
@mintuhouse @kreeger this is fixed with https://github.com/airbrake/airbrake/commit/eecbeecc5f5b298d07e0ad68f074bb11278b5e00
We are planning to release new gem version this week so please use edge version in the meantime.
Thank you.
