### ISSUE TITLE
airbrake not using filter_parameters correctly on Rails 4?

### ISSUE THREAD

**Issue by dvdplm** [airbrake/airbrake#336]
it appears that airbrake isn't using filter_parameters on Rails 4?

https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/controller_methods.rb#L42-L61

airbrake should be using the rails3 codepath on rails 4

**Comment by djhopper01** [comment]
Hey guys, is it possible to get a new release for the gem? This fix doesn't seem to be included with the version on Rubygems. Thank you.
