### ISSUE TITLE
Backtrace is not shown at some machines

### ISSUE THREAD

**Issue by ilonashub** [airbrake/airbrake#343]
When we run exceptions in our rails app locally, different machines shows trace, while others don't.
When i try to run some error on my app, i get the following mail:

![image](https://cloud.githubusercontent.com/assets/8695358/4719614/fef7e55a-592a-11e4-90be-800d56bc4ce2.png)

When i try to edit the code, and i take off the following lines in configuration.rb:

![image](https://cloud.githubusercontent.com/assets/8695358/4719624/1edf3d96-592b-11e4-9816-b7c16ded5991.png)

everything works fine.

**Comment by shifi** [comment]
Hi @ilonashub, can you please provide the steps to reproduce this issue?

**Comment by zenkalia** [comment]
@shifi 

(TLDR: reproducing this is really hard. i couldn't do it.)

i just spent a while trying to reproduce this bug on a new rails app but can't seem to do it. my app is doing some work in rake tasks that are giving me backtraces like OP's and i made a simplified version here: https://github.com/zenkalia/airbrake_madness

it's live here: http://airbrake-madness.herokuapp.com/

i can give access to the airbrake to whoever wants it. what i expected to happen is that the failed requests when going through the controller will have a normal backtrace but when running through the rake task they would give `:0` junk. this is what i'm getting in my current production app and it's driving me nuts.

instead here i'm getting the full backtrace. same stack. same exception. same ruby version, gem versions...

anyway, that repo is what i expected to cause the error. :sob:

**Comment by shifi** [comment]
@zenkalia can you maybe send me the Airbrake link of one error where you see empty backtrace?
Thank you for helping me out on this!

**Comment by zenkalia** [comment]
@shifi will this work? https://brainfall.airbrake.io/projects/108554/groups/1386771197731057511/notices/1423738476636973167

**Comment by shifi** [comment]
@zenkalia yep, that will work. I will check it, thanks

**Comment by shifi** [comment]
@zenkalia I'm having hard time reproducing this :(

**Comment by shifi** [comment]
@zenkalia which Rails version you're using in your production app?
Also, if you're using Spring gem (in dev, right?), can you tell me which version?

**Comment by zenkalia** [comment]
@shifi 

yeah we're using spring, i'll just upload the whole `Gemfile.lock`: https://gist.github.com/zenkalia/ed856897ccf023ea2cc1

**Comment by zenkalia** [comment]
also i haven't had the `:0` error happen in dev mode, only in production mode on heroku in a rake task.

**Comment by shifi** [comment]
@zanker and if you run rails app in production env locally? Do you see empty backtrace?

**Comment by shifi** [comment]
@zanker can you setup your gem to include [this commit](https://github.com/developwithvelocity/airbrake/commit/e0a3af11c8738ac37149418356a2b51e4f5853dc) and try again to see if that will fix your issue?
I'm not sure this is the proper fix for your issue but let's try. Thanks again!

**Comment by zenkalia** [comment]
@shifi adding that commit worked! :+1:

**Comment by benoist** [comment]
I am also seeing this in production. I am running Puma webserver. When I open a console and raise errors I get the backtrace with file locations. When I get an error via the webserver, I get backtrace as shown in the example from the first post.

**Comment by zenkalia** [comment]
@benoist if you're on airbrake `4.1.0`, try the fork i'm using: https://github.com/brainfall/airbrake/tree/brainfall_gem_patch

**Comment by shifi** [comment]
@zenkalia @benoist fix has been merged so you can use edge version now.
Thank you!
