### ISSUE TITLE
Access Api Key Dynamically?

### ISSUE THREAD

**Issue by bradurani** [airbrake/airbrake#346]
Is there a way to access the Airbrake config through a static context so I can dynamically populate the Airbrake JS notifier? Something like Airbrake.config.api_key would be nice, but I couldn't find such a way. Thanks.

**Comment by shifi** [comment]
@bradurani I'm not sure that's possible at the moment. Airbrake JS notifier has been extracted from this notifier. For any questions/issues please refer to https://github.com/airbrake/airbrake-js
