### ISSUE TITLE
also_use_rack_params_filters

### ISSUE THREAD

**Issue by vinnyglennon** [airbrake/airbrake#356]
on Airbrake 4.1.0,  ruby-2.0.0-p247, rails 4.1.8

airbrake  raise --api-key 'api_key'

/usr/lib/ruby/gems/2.0.0/gems/airbrake-4.1.0/lib/airbrake/notice.rb:370:in `also_use_rack_params_filters': undefined method`[]' for #Object:0x00000001b4ec08 (NoMethodError)
    from /usr/lib/ruby/gems/2.0.0/gems/airbrake-4.1.0/lib/airbrake/notice.rb:130:in `initialize'
    from /usr/lib/ruby/gems/2.0.0/gems/airbrake-4.1.0/lib/airbrake.rb:177:in`new'
    from /usr/lib/ruby/gems/2.0.0/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `build_notice_for'
    from /usr/lib/ruby/gems/2.0.0/gems/airbrake-4.1.0/lib/airbrake.rb:131:in`notify'
    from /usr/lib/ruby/gems/2.0.0/gems/airbrake-4.1.0/lib/airbrake/cli/runner.rb:27:in `run!'
    from /usr/lib/ruby/gems/2.0.0/gems/airbrake-4.1.0/bin/airbrake:12:in`<top (required)>'
    from /usr/bin/airbrake:23:in `load'
    from /usr/bin/airbrake:23:in`<main>'

airbrake.rb:
# -_\- encoding : utf-8 -_-

Airbrake.configure do |config|
  config.api_key = 'api_key'
end

api_key of course should be the valid key. Any ideas why it crashes on even command line?

**Comment by asymmetric** [comment]
Had the same problem, and it was solved by using the github repo in the Gemfile.

It seems a version with a fix hasn't been released yet.. any ETA?
