### ISSUE TITLE
Security Issue: Evaluation of URL parameters

### ISSUE THREAD

**Issue by bpourriahi** [airbrake/airbrake#358]
I'm not sure if this is the right place to put this, but I believe this may be a security issue. We had some auditing done on our application and we found that URL parameters on our site we being evaluated in javascript. After some digging, it turns out that this is due Airbrake code.

For example, this executes an alert: `oursite.com?aaa='-alert(String.fromCharCode(88,83,83))-'`

Is this a bug? I would think so.

It doesn't happen in Chrome or Firefox, they're escaping single quotes. But it does happen on Safari and Opera.

**Comment by vmihailenco** [comment]
Hi,

Do you use https://github.com/airbrake/airbrake-js notifier? Otherwise I can't imagine how Airbrake Ruby notifier can affect your site...

**Comment by bpourriahi** [comment]
Yes, sorry, wrong repo. This is for airbrake-js.
