### ISSUE TITLE
Tell Airbrake the version of the app when an error is reported

### ISSUE THREAD

**Issue by pas256** [airbrake/airbrake#359]
_Email to support_:
I have a Rails app that I would like to send Airbrake the version details when an error is reported. This is somewhat like the "deploy" feature, but since multiple version can be running at the same time, there is no definite "deploy" time.

Is there something in Airbrake.configure I can add that reads the version of the code from an ENV variable and sends it along when reporting any errors?

_Response from Morgan_: 
I am not aware of a way to add arbitrary keys and values to every airbrake error.
I agree that something like this should exist and be configurable from the Airbrake initialization file.
please make a github issue for this request.

My work here is done ;-)

**Comment by mmcdaris** [comment]
:+1: Thank you!

**Comment by kyrylo** [comment]
The upcoming major release allows appending arbitrary values to every notice to the Params tab. So we got this covered.
