### ISSUE TITLE
sidekiq component missing

### ISSUE THREAD

**Issue by yairperman** [airbrake/airbrake#360]
when using sidekiq, the airbrake notification does not contain component.
I needed to create the following helper method

```
def is_a_sidekiq_notification?(airbrake_notification)
  airbrake_notification.params.has_key?('retry_count')
end
```

moreover, I wanted to point out that IMO sidekiq retries should not be interesting in most cases
so in our code we filtered them till the worker is exhausted.
should I open a different issue for adding support for it / making it default ?

**Comment by sheerun** [comment]
+1 We'd like to send to errbit only dead jobs errors. We don't care about retries errors.

**Comment by kyrylo** [comment]
In the new gem (v5) we set the component: https://github.com/airbrake/airbrake/blob/4df0447b18145a6a44d6a56b43e1dae9e233f30a/lib/airbrake/sidekiq/error_handler.rb#L18
