### ISSUE TITLE
using airbrake for rake tasks

### ISSUE THREAD

**Issue by mintuhouse** [airbrake/airbrake#361]
I followed the instructions in documentation [here](https://github.com/airbrake/airbrake/wiki/Using-Airbrake-with-Rake)

But I was getting 'uninitialized constant Rake : NameError' error

I am using rails 4.1.9 and rake 10.4.2 with airbrake 4.1.0

Fix: 
I have to include ````require 'rake'```` manually on top of initializers/airbrake.rb to fix it.

**Comment by shifi** [comment]
@mintuhouse we updated [documentation](https://github.com/airbrake/airbrake/wiki/Using-Airbrake-with-Rake) like you said. Thank you for reporting this issue.
