### ISSUE TITLE
How do I get the #cause exception in Ruby?

### ISSUE THREAD

**Issue by airbrakeben** [airbrake/airbrake#362]
This come in from Support, so create Github issue here.

In Ruby 2.1+, a feature was introduced where a cause exception would be kept. I would like to be able to retrieve that data from the airbrake record - is this currently possible?

for reference see:

ruby docs http://www.ruby-doc.org/core-2.2.0/Exception.html#method-i-cause 
Avdi Grim blog post http://devblog.avdi.org/2013/12/25/exception-causes-in-ruby-2-1/

**Comment by kyrylo** [comment]
This will be supported in the next major release.

**Comment by hale** [comment]
Hi @kyrylo - looks like this didn't land in v5. Is it still in the roadmap?

**Comment by kyrylo** [comment]
It did. I suggest to open a new issue if you think there's a bug.

**Comment by kyrylo** [comment]
By the way, this is the place: https://github.com/airbrake/airbrake-ruby/issues
:P

**Comment by hale** [comment]
Ah that's great - thank you.
