### ISSUE TITLE
Airbrake::Sender#send_to_airbrake

### ISSUE THREAD

**Issue by adimircolen** [airbrake/airbrake#365]
Raising 'AirbrakeTestingException' to simulate application failure.
** [Airbrake] [Airbrake::Sender#send_to_airbrake] Cannot send notification. Error: NameError - uninitialized constant Airbrake::Notice::Builder

Configuration:
                  api_key: "XXXXX"
        backtrace_filters: [#<Proc:0x007f6caa274070@/var/www/app/shared/bundle/rub
 development_environments: []
       development_lookup: true
         environment_name: "staging"
                     host: "api.airbrake.io"
        http_open_timeout: 2
        http_read_timeout: 5
                   ignore: ["ActiveRecord::RecordNotFound", "ActionController::Rou
        ignore_by_filters: []
        ignore_user_agent: []
            notifier_name: "Airbrake Notifier"
             notifier_url: "https://github.com/airbrake/airbrake"
         notifier_version: "4.1.0"
           params_filters: ["password", "password_confirmation"]
             project_root: #<Pathname:/var/www/.....>
                     port: 80
                 protocol: "http"
               proxy_host: nil
               proxy_pass: nil
               proxy_port: nil
               proxy_user: nil
                   secure: false
use_system_ssl_cert_chain: false
                framework: "Rails: 4.1.0"
         user_information: "Airbrake Error {{error_id}}"
   rescue_rake_exceptions: nil
 rake_environment_filters: []
                test_mode: nil
Setting up the Controller.

Backtrace:
/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/notice.rb:142:in `to_xml'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/sender.rb:115:in `prepare_notice'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/sender.rb:50:in `send_to_airbrake'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake.rb:166:in `send_notice'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake.rb:138:in `notify_or_ignore'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rails/middleware.rb:40:in `notify_airbrake'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rails/middleware.rb:15:in `rescue in call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rails/middleware.rb:12:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rails3_tasks.rb:59:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rails3_tasks.rb:60:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/rack/logger.rb:38:in `call_app'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/rack/logger.rb:20:in `block in call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:68:in `tagged'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/rack/logger.rb:20:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/static.rb:64:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.9.275/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/engine.rb:514:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/railties-4.1.0/lib/rails/application.rb:144:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rails3_tasks.rb:118:in `block (2 levels) in <top (required)>'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
	/opt/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
	/var/www/app/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
	./bin/rake:16:in `load'
	./bin/rake:16:in `<main>'

** [Airbrake] Environment Info: [Ruby: 2.1.2] [Rails: 4.1.0] [Env: staging]

**Comment by shifi** [comment]
@adimircolen do you still see this issue?
Can you provide me with response when you execute:
`bundle exec rake airbrake:test`?
Thank you

**Comment by shifi** [comment]
@adimircolen closing this one. Feel free to reopen it if you still have any issues.
