### ISSUE TITLE
/notice.rb:370:in `also_use_rack_params_filters': undefined method `[]' for #<Object:0x7f5451abf778> (NoMethodError)

### ISSUE THREAD

**Issue by GideonJa** [airbrake/airbrake#368]
using Rails 3.0.3
ruby 1.8.7 (2011-02-18 patchlevel 334) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2011.03
airbrake (4.1.0)

when running airbrake raise --api-key API_KEY
or
airbrake raise -e PerlScriptError -m "Something went wrong with my perl script" -k  API-KEY

getting the below result:

/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/airbrake-4.1.0/lib/airbrake/notice.rb:370:in `also_use_rack_params_filters': undefined method `[]' for #<Object:0x1025642f0> (NoMethodError)
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/airbrake-4.1.0/lib/airbrake/notice.rb:130:in `initialize'
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `new'
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `build_notice_for'
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/airbrake-4.1.0/lib/airbrake.rb:131:in `notify'
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/airbrake-4.1.0/lib/airbrake/cli/runner.rb:27:in `run!'
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/lib/ruby/gems/1.8/gems/airbrake-4.1.0/bin/airbrake:12
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/bin/airbrake:23:in `load'
	from /Users/gideon/.rbenv/versions/ree-1.8.7-2011.03/bin/airbrake:23

**Comment by pucotronas** [comment]
Might be some missing dependencies, I've had similar problems that were solved by adding bundle exec:

    bundle exec airbrake raise ...

Only that it's hard to tell what's wrong from the stack trace...

**Comment by shifi** [comment]
@GideonJa can you test this again using the edge version of gem?
Thank you

**Comment by shifi** [comment]
Closing this one. @GideonJa feel free to reopen it if you still see this issue.

**Comment by GideonJa** [comment]
getting the same results. not sure why

**Comment by shifi** [comment]
hmmm, that is really weird. Can you please show me your `Gemfile` and your `config/initializers/airbrake.rb` file?
Filter out any sensitive data such as api-key

**Comment by shifi** [comment]
@mmcdaris can you test this using Ruby 1.8.7 and Rails 3.0.3? Thanks

**Comment by GideonJa** [comment]
Will do. I'm out this weekend but will follow up next week.
Thx

**Comment by mmcdaris** [comment]
I made a sample project to test this one out with the same ruby and rails version.
### Replication environment
```sh
# rails version
Rails 3.0.3
# ruby version
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin14.4.0], MBARI 0x6770, Ruby Enterprise Edition 2011.03
```

### Add airbrake with git
I added the following to my gemfile:
```rb
gem 'airbrake', :git => "git://github.com/airbrake/airbrake.git"
```

### Commands & Output
```sh
bundle exec airbrake raise --api-key $AIRBRAKE_API_KEY
# output: Exception sent successfully: http://airbrake.io/locate/12341234
```

```sh
bundle exec airbrake raise -e PerlScriptError -m "Something went wrong with my perl script" -k $AIRBRAKE_API_KEY
# output: Exception sent successfully: http://airbrake.io/locate/12341234
```

Please use bundle exec to make sure the correct airbrake cli used.
Let me know how it goes :)
