### ISSUE TITLE
Airbrake not respecting config.ignore on wrapped exceptions

### ISSUE THREAD

**Issue by joevandyk** [airbrake/airbrake#370]
Rails raises `ActionDispatch::ParamsParser::ParseError`that wraps a `JSON::ParserError` exception. I have `config.ignore << "ActionDispatch::ParamsParser::ParseError"` in my Airbrake config.

However, the exceptions are still being sent to Airbrake, it shows up as `JSON::ParserError`.

I don't want to ignore all `JSON::ParserErrors`, just this particular one while it's wrapped in the ActionDispatch one.

**Comment by kenn** [comment]
Came from https://github.com/rails/rails/issues/17731 and true, it's an Airbrake bug.

Also, I think it's worth considering that client errors like `ActionDispatch::ParamsParser::ParseError` or `ActionController::ParameterMissing` can be ignored by default.

**Comment by joevandyk** [comment]
Yes, I think those should be added to the default list. 

I have a pull request out there for fixing this bug btw.

**Comment by kenn** [comment]
Any thoughts? @dvdplm @shifi @alif

**Comment by kenn** [comment]
FWIW, it's a win-win because the Airbrake server will have fewer API hits, and users see less noise and have less time wasted.

**Comment by shifi** [comment]
Sorry guys for waiting so long. I will check this soon.
