### ISSUE TITLE
JSON loggin

### ISSUE THREAD

**Issue by andywenk** [airbrake/airbrake#372]
Hi,

first of all thank's a lot for the airbrake gem. It's awesome ;-).

We are using logstash for logging. I created this initializer for errbit:

    if defined?(APP_CONFIG[:errbit_api_key])
    Airbrake.configure do |config|
      config.api_key  = APP_CONFIG[:errbit_api_key]
      config.host     = APP_CONFIG[:errbit_host]
      config.port     = APP_CONFIG[:errbit_port]
      config.secure   = config.port == 443
      config.async do | notice | 
        AirbrakeDeliveryWorker.perform_async(notice.to_xml)
      end
    end
    end

Unfortunately the output from an error looks like this in the logs:

    {"@timestamp":"2015-03-17T09:46:13Z","@fields":{"pid":24850,"tid":"TID-6aoq4","context":"     
    AirbrakeDeliveryWorker JID-    
    7e3d38f19914ca8401954f44","program_name":null,"worker":"AirbrakeDeliveryW
    I, [2015-03-17T10:46:13.110817 #24850]  INFO -- : ** [Airbrake] Success: Net::HTTPOK
    D, [2015-03-17T10:46:13.110994 #24850] DEBUG -- : ** [Airbrake] Environment Info: [Ruby: 2.2.0]   
    [Rails: 4.2.0] [Env: production]
    D, [2015-03-17T10:46:13.111131 #24850] DEBUG -- : ** [Airbrake] Response from Airbrake: 
    UUID: 5507f7e573616321e46f1100
    URL:  http://errbit.server.com:3000/locate/5507f7e573616321e46f1100
    {"@timestamp":"2015-03-17T09:46:13Z","@fields":{"pid":24850,"tid":"TID-6aoq4","context":"    
    AirbrakeDeliveryWorker JID-   
    7e3d38f19914ca8401954f44","program_name":null,"worker":"AirbrakeDeliveryW

How can I configure airbrake, that the logs are JSON?

Thanks a lot and all the best

Andy

**Comment by shifi** [comment]
@andywenk I'm not sure we support JSON logs at the moment.
You can only configure logger to write into file or STDOUT.
More info [here](https://github.com/airbrake/airbrake/wiki/Logging-with-Airbrake).
I often use this config:
`config.logger = Logger.new STDOUT`

**Comment by andywenk** [comment]
@shifi thanks for the info. We created a filter in Logstash to filter out the messages.
