### ISSUE TITLE
Activejob support

### ISSUE THREAD

**Issue by iainbeeston** [airbrake/airbrake#373]
As I understand it, airbrake can send asynchronously using suckerpunch. But now that rails has activejob, would it be better to always send asynchronously, and use the default activejob handler (if defined)?

**Comment by shifi** [comment]
@iainbeeston yes we're planning to add this in new breaking version.
I'm closing this issue since it's similar to #381

**Comment by md5** [comment]
What's the right place to track support for `ActiveJob`? Both this issue and #381 were closed, so I'm not sure what my expectations should be for this feature.

**Comment by kyrylo** [comment]
Hi, @md5! We have some good news in this regard. We have already implemented the ActiveJob integration, but it's not released. We plan to release a new major version of the library in a couple of weeks.

**Comment by md5** [comment]
@kyrylo :+1:
