### ISSUE TITLE
Exceptions raised in `rails runner` are not send to airbrake

### ISSUE THREAD

**Issue by stgeneral** [airbrake/airbrake#377]
Seems that airbrake does not integrates with `rails runner`.

We use `rails runner "MyModel.some_method"` to run some cron jobs on the production instead of writing a separate rake tasks. And it would be good to have an option to integrate airbrake into `rails runner`.

**Comment by tamaloa** [comment]
+1 for this

But as a workaround you can modify bin/rails to use Airbrake notification. Our bin/rails looks as following
```ruby
#!/usr/bin/env ruby
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require_relative '../config/boot'
begin
  require 'rails/commands'
rescue => err
  Airbrake.notify_or_ignore(err)
  raise err
end
```
But this has not been extensively tested ...

**Comment by shifi** [comment]
@stgeneral @tamaloa can someone provide me with steps to reproduce this? Thank you

**Comment by tamaloa** [comment]
@shifi simply execute rails runner "ModelThatDoesNotExist.boom" -> no exception is logged.

This happens frequently to us as we use runners via whenever schedule converted to crontab entries. If a model or method is renamed our refactoring tools do not catch above string and thus the entries stay unnoticed.

**Comment by kyrylo** [comment]
The new major version of this library will support Rails runner out-of-box. In the meantime, there's an easy fix for you guys. Just add this to your Airbrake initializer.

```ruby
at_exit do
  Airbrake.notify($!) if $!
end
```

**Comment by back2war** [comment]
Does Airbrake support `rails runner` now? For me it still doesn't work. As well as 
`at_exit do`
  `Airbrake.notify($!) if $!`
`end`

`airbrake (10.0.2)`
`airbrake-ruby (4.13.3)`

**Comment by kyrylo** [comment]
Yes, we do. I just quickly checked on a Rails 6 app, and it works. If you spotted a bug, please file a new issue.

P.S. The snipped you quoted should likely be:

```rb
at_exit do
  Airbrake.notify_sync($!) if $!
end
```

`notify` is async and your Ruby process will quit faster than Airbrake can deliver an error.

**Comment by back2war** [comment]
The same snippet already present in the Airbrake gem:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/railtie.rb#L141

However it doesn't work for me because in my case `$ERROR_INFO` contains `SystemExit` and it  contains original exception. Probably it depends on Ruby version.

This code works for me:
```ruby
at_exit do
  if $ERROR_INFO.is_a?(SystemExit) && !$ERROR_INFO.success? && $ERROR_INFO.cause
    Airbrake.notify_sync($ERROR_INFO.cause)
  end
end
```

`ruby 2.6.3p62`
`rails (6.0.2.1)`
`airbrake (10.0.2)`
