### ISSUE TITLE
[doc/wiki] javascript insructions

### ISSUE THREAD

**Issue by mfazekas** [airbrake/airbrake#378]
Wiki at
https://github.com/airbrake/airbrake/wiki/Javascript-support
is out of date and still refers to arirbrake-shim which is now gone from airbrake-js.

Can you please update with the recommended way to use airbrake.js in a rails project?

**Comment by vmihailenco** [comment]
Please use README at https://github.com/airbrake/airbrake-js and open issue there if you have any questions.
