### ISSUE TITLE
invalid address when bundle exec rake airbrake:test

### ISSUE THREAD

**Issue by delphaber** [airbrake/airbrake#380]
Hi,

With a brand new rails 4.2.1 app I get this message when I run `bundle exec rake airbrake:test`

````bash
$ bundle exec rake airbrake:test

Configuration:
                  api_key: "xxxxxxx"
        backtrace_filters: [#<Proc:0x007fe92da99688@/Users/faber/.rbenv/versions/2
 development_environments: []
       development_lookup: true
         environment_name: "development"
                     host: "api.airbrake.io"
        http_open_timeout: 2
        http_read_timeout: 5
                   ignore: ["ActiveRecord::RecordNotFound", "ActionController::Rou
        ignore_by_filters: []
        ignore_user_agent: []
            notifier_name: "Airbrake Notifier"
             notifier_url: "https://github.com/airbrake/airbrake"
         notifier_version: "4.1.0"
           params_filters: ["password", "password_confirmation"]
             project_root: #<Pathname:/Users/faber/Repos/lol/lmao/blog>
                     port: 80
                 protocol: "http"
               proxy_host: nil
               proxy_pass: nil
               proxy_port: nil
               proxy_user: nil
                   secure: false
use_system_ssl_cert_chain: false
                framework: "Rails: 4.2.1"
         user_information: "Airbrake Error {{error_id}}"
   rescue_rake_exceptions: nil
 rake_environment_filters: []
                test_mode: nil
Setting up the Controller.
Processing request.


Started GET "/verify" for  at 2015-05-05 10:49:07 +0200
invalid address
`````

Due to "invalid address", I do not see the example exception on airbrake

This is my airbrake.rb initializer

````ruby
Airbrake.configure do |config|
  config.api_key = 'xxxxxxx' # api_key has been hidden
end
````

This happens also with a Rails 4.1.10 app

**Comment by delphaber** [comment]
This happens also on another pc

**Comment by ryush00** [comment]
I also happened.

**Comment by shifi** [comment]
@delphaber @ryush00 thanks for reporting this issue
we will soon add support for Rails 4.2.1

**Comment by zavan** [comment]
Also happened to me

**Comment by shifi** [comment]
The workaround is to set `REMOTE_ADDR` to localhost since web console is blocking other IPs in dev/test env.
I've added this fix here: https://github.com/airbrake/airbrake/commit/b10986f492c99fab3b841d0cab93694166d2bfa5
...but we still need to fix/update few other things in order to fully support Rails 4.2.1
Thank you for your patience guys.

**Comment by ryush00** [comment]
@shifi :+1:

**Comment by delphaber** [comment]
@shifi thanks!

**Comment by shifi** [comment]
I just cherry-picked commit which fixes this issue. If you use edge version it should work now.
Thank you all!

**Comment by toobulkeh** [comment]
this pushed out into a gem release yet?

**Comment by shifi** [comment]
@toobulkeh yes, please update your Airbrake gem. The latest version is 4.3.0

**Comment by toobulkeh** [comment]
:+1: thanks

**Comment by tarunrathi999** [comment]
Yes, just update the version of gem from 4.1.0 to 4.3.0, then you will not get this error.
