### ISSUE TITLE
Failure: Net::HTTPRequestEntityTooLarge

### ISSUE THREAD

**Issue by lacco** [airbrake/airbrake#389]
I have a Rails 3.2 application which works great with Airbrake, but some exceptions aren't reported correctly, I just find a "[Airbrake] Failure: Net::HTTPRequestEntityTooLarge" in our logs. I played around with the most current version (4.2.1), but this didn't help. Any advice?

**Comment by shifi** [comment]
@lacco max notice size which we accept is 64kb. Did you notice for which requests you get refused?

**Comment by lacco** [comment]
It looks like the error occurs when sending some big text updates from the browser with the params hash. I guess I need somehow to reduce the size of the params hash, using ```config.params_filters``` seems like the wrong place since I would need it on controller level. Do you have other ideas what I can do to get a "reduced" version of the params hash?

**Comment by shifi** [comment]
`config.params_filters` would only filter certain keys you defined so this wouldn't be helpful.
Are this kind of exceptions notified manually maybe? Currently there is no way to reduce params using airbrake gem, only if you can do that in your app somehow?

**Comment by lacco** [comment]
The idea of using ```config.params_filters``` was to remove the parameters containing long descriptions. For example, when the application is sending something like ```{post_id: 1, description: "Large chunk of text"}```, I could add ```config.params_filters += [:description]```. But this doesn't really feel like a nice solution...

The exceptions aren't sent manually, they are raised through errors in Rails views. We just have a big evil legacy application which is doing some bad stuff...

What about catching the ```Net::HTTPRequestEntityTooLarge``` error and resend the exception to Airbrake, but leaving out the parameters?

**Comment by shifi** [comment]
Is there a chance for you to detect those errors in controller, clear out params, and send [exceptions manually](https://github.com/airbrake/airbrake/wiki/Sending-notices-to-Airbrake-manually-from-controllers)? Would that work for you?
Also one other solution would be to use whitelist approach for params filters, that way you would filter out all params except the one you want to see. Whitelist approach is currently implemented on master branch and it will ship with next minor release.
If you want to try this, please use our edge version and add the following in your Airbrake config file:
`config.params_whitelist_filters << [:stuff, "to", /see/]`
Let me know if this will help you. At the moment we don't have a hack for resending large notices but I guess we can work something out in the future.

**Comment by shifi** [comment]
@lacco I will close this issue.
If you still have any questions, please open support ticket [here](https://help.airbrake.io/discussion/new).
Thank you!

**Comment by lacco** [comment]
I just saw that you can also specify regular expressions for ```config.params_filters ```, that was really helpful. I just added ```config.params_filters = [/_attributes$/]``` which reduces the amount of the params hash significantly, and the exceptions are now tracked as expected. Thanks for the help!

**Comment by shifi** [comment]
I'm glad it helped. Thank you.
