### ISSUE TITLE
Add option to filter sensitive data from URL

### ISSUE THREAD

**Issue by shifi** [airbrake/airbrake#390]
Add option to filter sensitive data from URL

**Comment by kyrylo** [comment]
Is this vital? What sensitive data is usually passed in URLs (and if it is sensitive, why you want to pass it via a URL)?

**Comment by shifi** [comment]
Here is related support ticket:
https://help.airbrake.io/discussions/questions/5881-filtering-parts-of-url-in-rack-apps

**Comment by kyrylo** [comment]
This was fixed in our upcoming major release.

**Comment by shifi** [comment]
:+1:
