### ISSUE TITLE
Background Airbrake notices when running test

### ISSUE THREAD

**Issue by benoittgt** [airbrake/airbrake#399]
Is it possible to disable it when running test with [asynchronous airbrake](https://github.com/airbrake/airbrake/wiki/Using-Airbrake-asynchronously) ? 

![image](http://i.imgur.com/jNctnoj.png)

I've try to do : 
```ruby
  config.async do |notice|
    config.development_environments = ['test', 'development']
    AirbrakeDeliveryWorker.perform_async(notice.to_xml)
  end
```

Without success.

I'm running airbrake 4.3.0. Check this [PR](https://github.com/airbrake/airbrake/pull/295) but didn't find the answer.

**Comment by benoittgt** [comment]
I've tried to take a look into the gem without success. If someone have already worked on notice it would be great. :smile:

**Comment by kyrylo** [comment]
Couldn't you just set `config.public = true` in your test suite?

**Comment by benoittgt** [comment]
Hello @kyrylo 
I've tried

```ruby
RSpec.configure do |config|
  config.public = true
end
```

```
.....................................................D, [2015-08-17T13:52:18.128928 #18502] DEBUG -- : ** [Airbrake] Notice was not sent due to configuration:
  Environment Monitored? false
  API key set? true
........

Finished in 9.97 seconds (files took 6.99 seconds to load)
61 examples, 0 failures
```

Without any changes

**Comment by kyrylo** [comment]
Hi! What I mean is this =)

```ruby
Airbrake.configure do |config|
  config.public = true
end
```

**Comment by benoittgt** [comment]
Oups sorry

```
/config/initializers/airbrake.rb:3:in `block in <top (required)>': undefined method `public=' for #<Airbrake::Configuration:0x007f80fc426c40> (NoMethodError)
```

**Comment by kyrylo** [comment]
Well, sorry, that was quite a bad tip from me! However, I think this may resolve your issue:

```ruby
Airbrake.configure do |config|
  config.environment_name = 'test'
end
```

Please let me know if this works.

**Comment by kyrylo** [comment]
Seems like it worked for you. Feel free to ping me if you have any further questions :+1:

**Comment by benoittgt** [comment]
Sorry didn't mention it doesn't fix fix my bugs. I still have notice when running test.

**Comment by kyrylo** [comment]
Ok, sorry then.

**Comment by kyrylo** [comment]
This should do the trick:

```ruby
config.logger = Logger.new('/dev/null')
```

**Comment by benoittgt** [comment]
Thanks @kyrylo it works with you tips.
