### ISSUE TITLE
Track 404 with airbrake

### ISSUE THREAD

**Issue by SergXIIIth** [airbrake/airbrake#401]
Hi,

How is it possible if airbrake put middleware after `ActionDispatch::ShowExceptions` ?

``` ruby
use Airbrake::UserInformer
use Rack::Sendfile
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f6e413c0058>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Airbrake::Rails::Middleware
```

I think it should be other way around

```
use Rails::Rack::Logger
use Airbrake::Rails::Middleware
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
```

**Comment by SergXIIIth** [comment]
Actually `Airbrake::Rails::Middleware` should be after `ActionDispatch::DebugExceptions`.
Since 404 raised in [ActionDispatch::DebugExceptions:51](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L51).

``` ruby
module ActionDispatch
  class DebugExceptions

    def call(env)
      _, headers, body = response = @app.call(env)

      if headers['X-Cascade'] == 'pass'
        body.close if body.respond_to?(:close)
        raise ActionController::RoutingError, "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"
      end
```

**Comment by kyrylo** [comment]
Hey, @SergXIIIth!

I thought we [already inserted](https://github.com/airbrake/airbrake/blob/02d29ccde1c46f957c9cf8261835ec7f9386e041/lib/airbrake/railtie.rb#L23) it after `ActionDispatch::DebugExceptions`.

I can confirm that for some reason we don't catch `ActionController::RoutingError`. I'm investigating this.

Out of curiosity, what's your scenario that you need 404's to be reported?

**Comment by SergXIIIth** [comment]
Hi @kyrylo 

I track security attacks. When someone try scan vulnerable paths.

**Comment by SergXIIIth** [comment]
Actually we should insert it **before** `DebugException`.

It work for me

``` ruby
    MyApp::Application.config.middleware.insert_before(
      ActionDispatch::DebugExceptions,
      Track404Middleware
    )

class Track404Middleware
  IGNORED_IP = [
    '91.209.196.35' # Comodo Ca Ltd - security checker
  ]

  def initialize(app)
    @app = app
  end

  def call(env)
    begin
      response = @app.call(env)
    rescue ActionController::RoutingError => exception
      if IGNORED_IP.include?(request.remote_ip)
      else
        env['airbrake.error_id'] = Airbrake.notify_or_ignore(exception, request_data(env))
      end
      # raise exception
    end

    response
  end

  private

  def controller(env)
    env["action_controller.instance"]
  end

  def request_data(env)
    if controller(env).respond_to?(:airbrake_request_data)
      controller(env).airbrake_request_data
    else
      {:rack_env => env}
    end
  end
end

```

**Comment by kyrylo** [comment]
@SergXIIIth thanks for the explanation. Unfortunately, your middleware doesn't work for me. What is your Rails version?

I have a hunch it's more tricky than just the middleware order. https://github.com/rails/rails/issues/671

**Comment by kyrylo** [comment]
I think I found out the reason why I cannot reproduce this. I didn't set `consider_all_requests_local` properly.

I've opened a PR that should fix this issue, however I'm not sure you will see `ActionController::RoutingError` in your dashboard, because we ignore this exception by default. That said, could you please test the patch with your app and tell me if we need to exclude that exception from the list of the default ignored exception.

Thanks a lot!

**Comment by kyrylo** [comment]
> @SergXIIIth 
> Actually `Airbrake::Rails::Middleware` should be after `ActionDispatch::DebugExceptions`.
 
I think this is correct.

My PR broke error reporting in general :) I need to find a better way to handle this.

**Comment by kyrylo** [comment]
It looks like if we insert our middleware before `ActionDispatch::DebugExceptions`, we lose the ability to report any other exceptions. Instead, I've found a different way to support 404 errors without breaking anything (the only downside is that exceptions' backtrace is longer and more confusing, but it shouldn't be a problem for your use case). Follow these simple steps:

1. Add a new "catch-all" route:

  ```ruby
  # config/routes.rb
  match '*path', to: 'application#routing_error', via: [:get, :post]
  ```

2. Add a handler for routing errors, which raises own `RoutingError`:

  ```ruby
# app/controllers/application_controller.rb
def routing_error
  raise ActionController::RoutingError,
        "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"
end
```

3. By default, we ignore `ActionController::RoutingError`, so you'd need to delete it from the list of ignores:

  ```ruby
# config/initializers/airbrake.rb
Airbrake.configure do |config|
  config.ignore.delete('ActionController::RoutingError')
end
```

With this setup you can report 404's now.
