### ISSUE TITLE
Airbrake is not respecting configured environment name in capistrano deploys

### ISSUE THREAD

**Issue by sakirtemel** [airbrake/airbrake#417]
I'm using a single environment both for staging and production. I've configured custom environment name 'staging' and 'production' in airbrake.rb.
https://github.com/airbrake/airbrake/wiki/Customizing-your-airbrake.rb#set-a-custom-environment-name
`
config.environment_name = "staging"
`

This works ok, but the problem is when I do the deployments, Rails.env is used to get the current environment, I think custom environment name should be used instead of Rails.env there.

https://github.com/airbrake/airbrake/blob/master/lib/airbrake/tasks/airbrake.cap#L15
`
airbrake_env = fetch(:airbrake_env, fetch(:rails_env, fetch(:stage)))
`

**Comment by shifi** [comment]
Hi @sakirtemel 
How do you propose we do that?
Should we set `environment_name` var somewhere so we can fetch it inside `.cap` file or do you have something else on your mind?
We would be very grateful if you could provide PR :smiley:

**Comment by sakirtemel** [comment]
you could change this line
` airbrake_env = fetch(:airbrake_env, fetch(:rails_env, fetch(:stage))) `

so when airbrake_env is not set it should try to get config.environment_name.

I'll try to make a PR

**Comment by kyrylo** [comment]
Hey, @sakirtemel!

Couldn't you just set your `:rails_env` in `deploy.rb`?

```ruby
set :rails_env, 'staging'
```

**Comment by sakirtemel** [comment]
I know I can do, and I did, and actually I used airbrake_env instead. 

But don't you think that it would be more natural to get this from Airbrake configuration ? Then people wouldn't need to set another extra variable that they have set it before in configuration.

Setting another variable looks like workaround for me.

@kyrylo

**Comment by kyrylo** [comment]
Thanks for the reply! I don't see anything wrong with this. Think of this as of setting your Rails environment, not configuring Airbrake. Many libraries can `fetch(:rails_env)`, not only Airbrake. 

We're planning a major release and there won't be `:airbrake_env` anymore, because it is superfluous. So in your situation you would need to set `:rails_env`.

**Comment by sakirtemel** [comment]
But what if I set rails env as production both for sandbox and staging? And
only differ them with settings? Because right now we are following this
way. With that you are not having too many environments in your app.

If you get rid of the airbrake env, I think you would still need to provide
something else to distinguish the real environment. With newrelic we are
solving this with setting the domain name. Currently domain name is not
used in Airbrake in deploy and errors list pages.

**Comment by kyrylo** [comment]
Could you publish a dummy app, which simulates the behaviour of your original app, so I can understand this issue better?

**Comment by sakirtemel** [comment]
Sure, I'll let you know when I do it.
