### ISSUE TITLE
Avoid calling Ruby URI lib

### ISSUE THREAD

**Issue by alexis779** [airbrake/airbrake#419]
Airbrake middleware makes our Rails app crash on a request parameter containing a |
![uri_parsing_error](https://cloud.githubusercontent.com/assets/210994/10115283/49b70bec-63b7-11e5-8884-5817c11f871b.png)

Sorry for the backtrace as an image.

We can not control the parameter sent by HTTP client so we need to handle this scenario.

URI.join raise an exeception when request parameter has unescaped special characters like pipe:

```
[1] pry(main)> URI.join("http://www.example.com", "/|")
URI::InvalidURIError: bad URI(is not URI?): /|
from /usr/lib/ruby/2.1.0/uri/generic.rb:1203:in `rescue in merge'
```

but we don't need to call it to build the full url of the request.

**Comment by alexis779** [comment]
See https://github.com/airbrake/airbrake/pull/420

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake/pull/420.
