### ISSUE TITLE
Whitelisting of rake environment filters?

### ISSUE THREAD

**Issue by bquorning** [airbrake/airbrake#435]
I recently learned that when a rake task fails, it by default sends the entire OS ENV to Airbrake. With the popularity of dotenv and similar solutions, that hash may contain a lot of secrets.

So I found the (undocumented) config setting `rake_environment_filters`, which allows users to specify a blacklist of ENV keys that shouldn’t be sent to Airbrake: https://github.com/airbrake/airbrake/blob/v4.3.3/lib/airbrake/rake_handler.rb#L30-L34

Since blacklists need maintenance (add a new entry when adding a new key to ENV), I would prefer an option to configure a whitelist instead of a blacklist. Would that be possible?

**Comment by kyrylo** [comment]
We're preparing a new major release of the library, which will include whitelisting. On a different note, do you find the info from environment variables useful for debugging? Or do you think it makes sense to ignore them altogether?

**Comment by bquorning** [comment]
> do you find the info from environment variables useful for debugging? Or do you think it makes sense to ignore them altogether?

In most cases, I have found that the error message and backtrace were enough to understand why the exception happened. Perhaps the `environment_info` could default to an empty hash, with a configurable whilelisting of keys from ENV?

**Comment by kyrylo** [comment]
By default, we will not be sending any ENV vars anymore. There will be a mechanism, which allows attaching custom information to notices (something like before_send hook). Therefore, you will be able to attach ENV vars, if needed. Thanks for your report, we are also concerned about privacy of your information =)

**Comment by mtrepanier** [comment]
Have an idea when this will be available?

**Comment by kyrylo** [comment]
Within a couple of weeks.
