### ISSUE TITLE
Recent update broke heroku deployments

### ISSUE THREAD

**Issue by jfimek** [airbrake/airbrake#445]
Something that just got committed recently seems to have broken Heroku deployments

Assets can't precompile anymore due to this Airbrake error

Airbrake::Error: the 'default' notifier isn't configured

**Comment by kyrylo** [comment]
Hello! We've recently released a new major version our gem. The new gem has some breaking changes. If you're ready to migrate, please read this [migration guide](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md).

If you're not ready to upgrade, you can safely use your previous Airbrake gem (we still support airbrake v4 and latest available stable release is 4.3.4).

**Comment by jfimek** [comment]
oops, I missed that.   It looks like Heroku is in the middle of an outage in their deployment environment according to status.heroku.com.  I must have been running into both things at the same time.  Thanks.

**Comment by kyrylo** [comment]
Cheers!
