### ISSUE TITLE
Resque Readme Section

### ISSUE THREAD

**Issue by mtthwhggns** [airbrake/airbrake#448]
In the README file, under **resque**, there is an example like this;

    # config/initializers/resque.rb
    require 'airbrake/resque/failure'
    Redis::Failure.backend = Resque::Failure::Airbrake

I don't know much about how resque works, but I'm pretty sure this should be

    # config/initializers/resque.rb
    require 'airbrake/resque/failure'
    Resque::Failure.backend = Resque::Failure::Airbrake

Locally, this resolves an `UninitialisedConstant` error (caused by hurriedly copy/pasting the code without reading it!)

Am I mistaken, or should this be updated (I'm happy to submit a PR if necessary).

**Comment by kyrylo** [comment]
Thanks! You are correct. That was probably my Emacs with wrong autocompletion :)
I am happy to accept a PR fixing this :)
