### ISSUE TITLE
Airbrake 5 Breaks Debugging

### ISSUE THREAD

**Issue by jonmchan** [airbrake/airbrake#449]
Using ruby-debug-ide 0.6.0, after upgrading to airbrake 5, I get the following error when debugging:

```
Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.2.beta6, file filtering is supported) listens on 127.0.0.1:59714
Uncaught exception: uninitialized constant Rake::TaskManager
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/airbrake-5.0.0/lib/airbrake/rake/task_ext.rb:4:in `<top (required)>'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/airbrake-5.0.0/lib/airbrake.rb:19:in `require'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/airbrake-5.0.0/lib/airbrake.rb:19:in `<top (required)>'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `each'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `block in require'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `each'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `require'
	/home/jchan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler.rb:134:in `require'
```

There is an issue with the order of loading airbrake that didn't occur in the older gem. I don't believe Rake::TaskManager is loaded when the task_ext.rb file is loaded. I am unable to run my project in debug because of this.

**Comment by kyrylo** [comment]
Hi! How do I reproduce this?

**Comment by cec** [comment]
I get the same error when trying to run a spec.

I'm using:
* airbrake 5.0.1
* airbrake-ruby 1.0.0
* rake 10.4.2
* rspec 3.3.0

To reproduce, just run any spec file.

**Comment by kyrylo** [comment]
@cec could you update airbrake & airbrake-ruby just to be sure it's still a problem? The latest versions are airbrake-5.0.2 & airbrake-ruby-1.0.2. Just execute:

```sh
bundle update airbrake
```

**Comment by cec** [comment]
Hi @kyrylo , 
I did that right after posting and the bug is still there.

Sorry if I noticed your message only now!

**Comment by jonmchan** [comment]
@kyrylo i also updated airbrake - same issue.

**Comment by kyrylo** [comment]
I am still not sure how to reproduce this because running specs works just fine for me.

@jonmchan Could you please describe how do I reproduce this with your scenario?

**Comment by eostrom** [comment]
FYI, I'm getting a similar error running specs in RubyMine (not in debug mode). The Rake::TaskManager error is wrapped in an Airbrake configuration error:

```
/Users/eostrom/.rvm/rubies/ruby-2.2.3/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/eostrom/workspace/ten/plc/bin/rspec /Users/eostrom/workspace/ten/plc/spec --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter --pattern **/*_spec.rb
Testing started at 5:01 PM ...
/Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:282:in `call_notifier': the 'default' notifier isn't configured (Airbrake::Error)
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:149:in `notify_sync'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:292:in `block in <top (required)>'
/Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/airbrake-5.0.2/lib/airbrake/rake/task_ext.rb:4:in `<top (required)>': uninitialized constant Rake::TaskManager (NameError)
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/airbrake-5.0.2/lib/airbrake.rb:19:in `<top (required)>'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/eostrom/.rvm/gems/ruby-2.2.3@plc/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
```

The specs run fine from the command line.

I'll work on getting more information and/or a reproducible test case tomorrow, I just wanted to add a data point.

**Comment by jonmchan** [comment]
@kyrylo i can't seem to reproduce it outside of ruby mine. You could download a trial of Rubymine and try to launch a spec from the debugger. 

I wonder if this is something that Rubymine will have to fix.

**Comment by eostrom** [comment]
I added rake near the top of my Gemfile and now my tests run. I don't know why rake was being loaded in the command line environment and not in RubyMine.

**Comment by cec** [comment]
@kyrylo sorry for replying only now.

As @eostrom suggested, I changed my Gemfile as:

````
gem 'rake'
gem 'airbrake', '~> 5.0'
````

With that, specs run fine once again.
Same for the debugger.

**Comment by kyrylo** [comment]
Thanks for the information, guys! I was able to reproduce this and submitted a fix.

**Comment by cec** [comment]
Nice! Thank you

**Comment by jonmchan** [comment]
I just tested your fix and it works! Rubymine debugging is back! Thank you @kyrylo
