### ISSUE TITLE
Airbrake 5 causes server to crash

### ISSUE THREAD

**Issue by liorsion** [airbrake/airbrake#452]
after upgrading (not starting a new project) to airbrake 5 and using the following config:

Airbrake.configure do |config|
  config.project_key = 'xyz some key here'
  config.project_id = project id here
  config.environment = Rails.env
  config.ignore_environments = %w(development test)

end

Airbrake.add_filter do |notice|
  if notice[:errors].any? { |error| error[:type] == 'ActionController::ParameterMissing' }
    notice.ignore!
  end
end

Airbrake.add_filter do |notice|
  if notice[:errors].any? { |error| error[:type] == 'ActiveRecord::RecordNotFound' }
    notice.ignore!
  end
end

any RecordNotFound error (404) actually crashed the server and returned error 500. Not sure what is the reason but regardless - this behavior is really bad for production servers.

**Comment by kyrylo** [comment]
To see the reason check your `production.log`. I'm afraid we can't do much without more information. Please also make sure you use latest `airbrake-ruby` - v1.0.1 (this is really important).

**Comment by liorsion** [comment]
I used airbrake-ruby (1.0.0) which is what came bundled with airbrake (I didn't install directly) . If this is so important why don't you update the dependency or update the doc someplace?

this is the log:

NoMethodError (undefined method `call' for nil:NilClass):
 vendor/bundle/ruby/2.2.0/gems/airbrake-ruby-1.0.0/lib/airbrake-ruby/filter_chain.rb:64:in `block in refine'
vendor/bundle/ruby/2.2.0/gems/airbrake-ruby-1.0.0/lib/airbrake-ruby/filter_chain.rb:62:in `each'
vendor/bundle/ruby/2.2.0/gems/airbrake-ruby-1.0.0/lib/airbrake-ruby/filter_chain.rb:62:in `refine'
 vendor/bundle/ruby/2.2.0/gems/airbrake-ruby-1.0.0/lib/airbrake-ruby/notifier.rb:123:in `send_notice'
vendor/bundle/ruby/2.2.0/gems/airbrake-ruby-1.0.0/lib/airbrake-ruby/notifier.rb:45:in `notify'
vendor/bundle/ruby/2.2.0/gems/airbrake-ruby-1.0.0/lib/airbrake-ruby.rb:280:in `call_notifier'
 vendor/bundle/ruby/2.2.0/gems/airbrake-ruby-1.0.0/lib/airbrake-ruby/filter_chain.rb:62:in `each' Context

btw, I no longer need help around that, I downgraded since it's not possible to work with something that kills my production site.. at this point I'm just trying to help you debug it.

**Comment by kyrylo** [comment]
Thanks for the log. This was fixed by https://github.com/airbrake/airbrake-ruby/pull/10

I am sorry for the inconvenience that we caused for you. If you do a fresh install of the airbrake gem, you will automatically fetch the latest airbrake-ruby version.

The fix for you is simple: `bundle update airbrake-ruby`.
