### ISSUE TITLE
New Airbrake 5 ignores environment settings.

### ISSUE THREAD

**Issue by secoint** [airbrake/airbrake#453]
Hi! After migration from v4 to v5:

```ruby
# config/initializers/airbrake.rb
Airbrake.configure do |config|
  config.project_key = '<key>'
  config.project_id = <id>
  config.ignore_environments = %w(development test)
end
```

But Airbrake ignores `config.ignore_environments` option! It send error event in 'test' (from CI) and 'development' envs.

I am using:
* airbrake (5.0.1)
* airbrake-ruby (1.0.1)
* rails (4.0.13)
* ruby 2.1.7p400

What I'm doing wrong? Thanks!

**Comment by secoint** [comment]
Oops, I think I've missed `config.environment = Rails.env` setting. Sorry :-)

**Comment by kyrylo** [comment]
Greetings! Yeah, this was subtle and we've only recently [mentioned](https://github.com/airbrake/airbrake/pull/451) this in the migration guide.
