### ISSUE TITLE
Airbrake 5 -- "ActiveRecord::RecordNotFound" not ignored by default

### ISSUE THREAD

**Issue by aleksejleonov** [airbrake/airbrake#456]
* Airbrake version: 5.0.1
* Ruby version: 2.3.0
* Framework name & version: Rails 4.2.4

#### Airbrake config

    Airbrake.configure do |c|
      c.project_id = xxx
      c.project_key = xxx
      c.root_directory = Rails.root
      c.logger = Rails.logger
      c.environment = Rails.env
      c.ignore_environments = %w(test)
    end

#### Description

After upgrade to Airbrake v5 (accordingly to migration guide) we start receiving "ActiveRecord::RecordNotFound" exceptions (that should be ignored by default).

I trying to ignore them with `.add_filter`:
```ruby
Airbrake.add_filter do |notice|
  notice.ignore! if notice[:error_class] == 'ActiveRecord::RecordNotFound'
end
```

But `notice` object didn't contains :error_class hash key. Actually `notice` is complex object and I could get error type only next way: `notice[:errors][0][:type]`.

**Comment by kyrylo** [comment]
In v5 we're not ignoring anything but `SystemExit` by default.

Could you link me or cite where it says to use `.add_filter` like you showed? That's definitely a mistake.
The correct way is described [here](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#ignore-by-filter).

**Comment by aleksejleonov** [comment]
@kyrylo, I open this issue about `.add_filter` in `airbrake-ruby` gem repo (https://github.com/airbrake/airbrake-ruby/issues/15).

Also, you need to fix (or make separate docs for v4 and v5) on Airbrake site docs: http://help.airbrake.io/kb/installing-airbrake/installing-airbrake-in-a-rails-application (it have section "Errors Ignored by default")

Would be very good to clarify this changes about ignored errors in "Migration guide" (actually, it's not a big problem, but this changes was unexpected for me).

**Comment by aleksejleonov** [comment]
@kyrylo, `.add_filter` example in "Migration guide" is Ok. But there is mistake in `airbrake-ruby` gem docs: https://github.com/airbrake/airbrake-ruby#airbrakeadd_filter.

**Comment by kyrylo** [comment]
Awesome, @aleksejleonov! Thanks a lot for noticing these discrepancies and filing issues. I've updated all the docs. The Airbrake site article is deprecated now.
