### ISSUE TITLE
falling back to sync delivery because there are no running async workers

### ISSUE THREAD

**Issue by cnluzhang** [airbrake/airbrake#463]
* Airbrake version: 5.0.2
* Ruby version: 2.2.2
* Framework name & version: Rails 4.2.4

#### Airbrake config
Airbrake.configure do |config|
  config.project_key = 'xxx'
  config.project_id = 12345
  config.environment = Rails.env
  config.ignore_environments = ["development", "test"]
end

#### Description
Well, I am a complete beginner to rails. I put the config to my config/initializers/ and start my server. Although it works fine and I also can check the error (and its detail) in my Airbrake, but I still receive the WARN likes title.

I noticed that 'Airbrake is now async by default.', but I don't know where to configure async worker, Could you help me or give some examples?

PS: 
1. https://github.com/airbrake/airbrake/wiki/Using-Airbrake-asynchronously is deprecated.
2. I use sidekiq 3.4.2.

Thanks.

**Comment by kyrylo** [comment]
Can you uncomment the `Thread` expression in your initializer to see if you get any errors?

**Comment by cnluzhang** [comment]
Okay, but after I uncomment it and restart my application, nothing there seemed to have changed, the WARN still appear.

**Comment by wgrrrr** [comment]
I am also getting this same issue.

Airbrake: 5.0.1
Rails: 4.2.5
Ruby: 2.2.4

```ruby
Airbrake.configure do |config|
  config.project_id = 'xxx'
  config.project_key = 'yyy'
  config.root_directory = Rails.root
  config.logger = Rails.logger
  config.environment = Rails.env
  config.ignore_environments = %w(development test)
  config.workers = 1
end
```

**Comment by kyrylo** [comment]
@wgrrrr are you using Sidekiq?

**Comment by wgrrrr** [comment]
Sure am. Sidekiq 4.0.1.

**Comment by kyrylo** [comment]
@cnluzhang @wgrrrr

* When you uncomment `Thread.abort_on_exception = true`, do you see anything in your logs?
* Could you share your `Gemfile`?
* Can you reproduce this locally?
* Do you customise your `config/sidekiq.yml`? If yes, please share.

Thanks!
