### ISSUE TITLE
`call_notifier': the 'default' notifier isn't configured (Airbrake::Error)

### ISSUE THREAD

**Issue by grammakov** [airbrake/airbrake#467]
All of a sudden my app stopped booting up on development, throwing an error on any command:

```
/Users/grammakov/.rvm/gems/ruby-2.2.3@weintervene/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:282:in `call_notifier': the 'default' notifier isn't configured (Airbrake::Error)
	from /Users/grammakov/.rvm/gems/ruby-2.2.3@weintervene/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:149:in `notify_sync'
	from /Users/grammakov/.rvm/gems/ruby-2.2.3@weintervene/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby.rb:292:in `block in <top (required)>'
/Users/grammakov/repositories/weintervene/config/initializers/airbrake.rb:2:in `block in <top (required)>': undefined method `api_key=' for #<Airbrake::Config:0x007fa9272e8330> (NoMethodError)
```

My gemfile:
```
gem 'airbrake', '~> 5.0', '>= 5.0.2'
```
Did not do anything to inflict this behavior, app worked fine yesterday. Any tips appreciated.

**Comment by kyrylo** [comment]
Howdy! You have upgraded to Airbrake v5. It's a bit different from Airbrake v4 in terms of configuration. Please refer to the [migration guide](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md). In your case the fix is simple: rename `api_key` to `project_key` and configure your `project_id`.

**Comment by grammakov** [comment]
@kyrylo thank you for the quick reply. I have updated the information and the error changed to

```
/Users/grammakov/.rvm/gems/ruby-2.2.3@weintervene/gems/airbrake-ruby-1.0.2/lib/airbrake-ruby/backtrace.rb:92:in `match_frame': can't parse '/Users/grammakov/repositories/weintervene/config.ru:in `new'' (Airbrake::Error)
```

**Comment by kyrylo** [comment]
That's a bug :) Are you using Sinatra?

**Comment by grammakov** [comment]
@kyrylo no I am on Rails. I now realized I've updated the RVM earlier today.

**Comment by grammakov** [comment]
The warning is gone after disabling the ```exception_handler``` gem

**Comment by kyrylo** [comment]
Thanks for the info. There's still a bug for us.

**Comment by kyrylo** [comment]
Closed in favour of https://github.com/airbrake/airbrake-ruby/issues/24. Thanks!
