### ISSUE TITLE
Capistrano 2.x deployment notification broken

### ISSUE THREAD

**Issue by nick-desteffen** [airbrake/airbrake#468]
```
fileutils.rb:127:in `chdir': No such file or directory @ dir_chdir
```
I'm not sure how this would work, this command would run on the local machine doing the deployment:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/capistrano/tasks.rb#L42

It needs to change the directory on the remote machine.

**Comment by kyrylo** [comment]
Thanks for reporting this, @nick-desteffen. This worked only because I was deploying from my computer to... my computer! :) Good catch.

I'd be happy to accept a patch, if you wish.

**Comment by kyrylo** [comment]
Hey, @nick-desteffen! Could you please confirm if the fix above resolves the issue for you?

**Comment by nick-desteffen** [comment]
I wish I could help, but I went ahead and just upgraded our final application to Cap 3 last Friday...  It was going to happen eventually.

**Comment by kyrylo** [comment]
No worries, thanks for reporting this fatal bug. It's more than enough :)

**Comment by vikrammishra333** [comment]
I am getting the error 
`I don't know to which Rails environment you are deploying (use the TO=production option) `

I am using capistrano-2 and recently upgraded from airbrake-4.3.x to airbrake-5.5.0. Please help.

**Comment by kyrylo** [comment]
I suggest to open a new issue.
