### ISSUE TITLE
Integration with Phusion Passenger

### ISSUE THREAD

**Issue by mvastola** [airbrake/airbrake#470]
I'd very much like to see integration between `airbrake` and Phusion's `passenger`, because a major hole in my error notification setup occurs when I deploy to a server and `passenger` fails to spawn instances of my `rails` app (well, technically it treats everything as a `rack` app, but that's beside the point) for whatever reason. 

While `airbrake` already has `rack` integration, this doesn't come into play until/unless `rack` successfully loads. Issues from missing gems to corrupt configurations can prevent `rack` from getting to this point, and currently, with `passenger`, the only way to monitor these errors is to tail your web server log file or subscribe to their (paid) UnionStation service.

In the past half-hour I just scraped together an extremely bare-bones integration as its own gem called [airbrake-passenger](https://github.com/Partyista/airbrake-passenger). Rather than a separate gem, however, I would really like to see this code become part of `airbrake` though.

Would `airbrake` be willing to merge this implementation into their official gem/repository if I refactored it as a PR here? Note that I plan to go through and add a couple of extra features (which is mostly to say that I want to see if I can add additional helpful context data to the notifications) and would additionally be happy to make any other changes requested by you guys prior to submitting such a PR.

**Comment by kyrylo** [comment]
> Would airbrake be willing to merge this implementation into their official gem/repository if I refactored it as a PR here? 

Hi, Mike! That would be fantastic. :+1:

**Comment by mvastola** [comment]
Ok. Cool. I'm going to close this then. If not tomorrow (by which I mean Sunday), expect a PR soon!

**Comment by mvastola** [comment]
@kyrylo, FYI, see #472. Input would be greatly appreciated!
