### ISSUE TITLE
nil Error with Passenger and passenger_pre_start/passenger_min_instances

### ISSUE THREAD

**Issue by svoop** [airbrake/airbrake#474]
There's something fishy with the airbrake v5 gem when used for a Rails app behind Nginx/Passenger with the directives `passenger_pre_start` and `passenger_min_instances`. Unfortunately, I'm not able to put my finger on where exactly the problem occurs.

The two directives mentioned above trigger simple HEAD requests whenever the webserver is reloaded. According to Passenger support, the requests look as follows:

    HEAD / HTTP/1.1
    Host: 0.0.0.0
    Connection: close

When I simulate such a request on an application instance in "production", it works without any problem:

    curl -v -I http://0.0.0.0:3000/  -H "User-Agent:" -H "Accept:" -H "Host: 0.0.0.0" -H "Connection: close"

The real request by Passenger, however, does trigger a notification with a somewhat limited payload (I've replaced the real host with myhost.com):

```
{"errors"=>
  [{"type"=>"NoMethodError",
    "message"=>
     "undefined method `call' for nil:NilClass\nDid you mean?  caller",
    "backtrace"=>[]}],
 "context"=>
  {"environment"=>"staging@f057",
   "os"=>"x86_64-linux",
   "language"=>"ruby/2.3.0",
   "notifier"=>
    {"name"=>"airbrake-ruby",
     "version"=>"1.0.2",
     "url"=>"https://github.com/airbrake/airbrake-ruby"}},
 "environment"=>
  {"HOST"=>"myhost.com",
   "SHELL"=>"/bin/bash",
   "TERM"=>"xterm-256color",
   "EINFO_LOG"=>"/etc/init.d/nginx",
   "PASSENGER_DEBUG_DIR"=>"/tmp/passenger.spawn-debug.XXXXyCJtbm",
   "LC_ALL"=>"en_US.utf8",
   "USER"=>"myhost_production",
   "FIXTURES_PATH"=>"spec/fixtures",
   "MULTIOSDIRS"=>"../lib64:../lib32",
   "PAGER"=>"/usr/bin/less",
   "PASSENGER_USE_FEEDBACK_FD"=>"true",
   "RC_SVCNAME"=>"nginx",
   "PWD"=>"/var/www/myhost.com/current",
   "EDITOR"=>"/bin/nano",
   "LANG"=>"en_US.utf8",
   "SVCNAME"=>"nginx",
   "HOME"=>"/var/www/myhost.com/",
   "SHLVL"=>"1",
   "RAILS_ENV"=>"production",
   "LOGNAME"=>"myhost_production",
   "SERVER_SOFTWARE"=>"nginx/1.8.0 Phusion_Passenger/5.0.23",
   "LESS"=>"-R -M --shift 5",
   "GCC_SPECS"=>"",
   "LESSOPEN"=>"|lesspipe %s",
   "GEMRC"=>"--no-ri --no-rdoc",
   "IN_PASSENGER"=>"1",
   "PYTHONUNBUFFERED"=>"1",
   "RACK_ENV"=>"production",
   "WSGI_ENV"=>"prodoction",
   "NODE_ENV"=>"production",
   "PASSENGER_APP_ENV"=>"production",
   "GEM_PATH"=>"",
   "GEM_HOME"=>"/var/www/myhost.com/shared/bundle/ruby/2.3.0",
   "BUNDLE_BIN_PATH"=>
    "/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/exe/bundle",
   "BUNDLE_GEMFILE"=>
    "/var/www/myhost.com/releases/20160110192007/Gemfile",
   "RUBYOPT"=>"-rbundler/setup",
   "RUBYLIB"=>"/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib",
 "session"=>{},
 "params"=>{},
 "notifier"=>
  {"name"=>"airbrake-ruby",
   "version"=>"1.0.2",
   "url"=>"https://github.com/airbrake/airbrake-ruby"},
 "key"=>"__REMOVED__",
 "controller"=>"api/v3/notices",
 "action"=>"create",
 "project_id"=>"__REMOVED__",
 "notice"=>
  {"notifier"=>
    {"name"=>"airbrake-ruby",
     "version"=>"1.0.2",
     "url"=>"https://github.com/airbrake/airbrake-ruby"}}}
```

Apparently, the environment is quite different from a normal request (e.g. no `REQUEST_HOST`) because it is produced by Passenger in a different context than a regular request.

The error looks similar to #452 but I don't think it's really related because the fix is already part of airbrake-ruby 1.0.2 used here.

Also, I've not checked whether the work on #472 has an impact, mostly because I have no clue what's actually going awry here.

**Comment by svoop** [comment]
By the way: I'm using the ENV filter (from the docs) in the above setup:

    Airbrake.add_filter do |notice|
      notice[:environment] = ENV
    end

However, the behaviour is identical even if I remove this filter altogether.

**Comment by mvastola** [comment]
#472 hasn't been merged, so can't be related.

**Comment by svoop** [comment]
@mvastola My bad, what I ment was that #472 might fix this problem as a side effect.

**Comment by kyrylo** [comment]
This PR may potentially fix your issue: https://github.com/airbrake/airbrake-ruby/pull/21.

**Comment by svoop** [comment]
@kyrylo Indeed, it does, thanks for the hint!

**Comment by kyrylo** [comment]
Fantastic :) Please note this fix hasn't been released yet. It will be released sometime during this week.

**Comment by svoop** [comment]
No problem, I stick to master until then.

**Comment by kyrylo** [comment]
The new gem was released today.

**Comment by svoop** [comment]
@kyrylo Thanks for the heads up... and for all the work!

**Comment by wlipa** [comment]
I still get this when doing Passenger deployments on the latest released gem as of now.

**Comment by kyrylo** [comment]
@wlipa please follow https://github.com/airbrake/airbrake/issues/490
