### ISSUE TITLE
Cannot disable Airbrake on development after upgrade

### ISSUE THREAD

**Issue by grammakov** [airbrake/airbrake#477]
I have enabled Airbrake on *production only* in my control panel.
Within my applications I have this code

```
Airbrake.configure do |config|
  config.project_key = 'xxx'
  config.project_id = 111
  config.ignore_environments = %w(development test)
end
```

Am I missing something?

**Comment by blackjackcf** [comment]
+1 on this issue. I'm having Airbrake trigger in RSpec. I'm having to manually stub the requests so that they don't trigger.

**Comment by kyrylo** [comment]
Hi! You need to set your environment. See an example [here]( https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#development-environments)

**Comment by blackjackcf** [comment]
@kyrylo - Thanks. This fixed the issue! Glad it got clarified in the guides.

**Comment by kyrylo** [comment]
:+1:

**Comment by grammakov** [comment]
yes, spasibo :+1:
