### ISSUE TITLE
Ignore exceptions in v5?

### ISSUE THREAD

**Issue by KurtPreston** [airbrake/airbrake#480]
According to [the documentation](https://github.com/airbrake/airbrake/wiki/Customizing-your-airbrake.rb), you should be able to ignore exceptions by adding a ```c.ignore << 'ExceptionName'```

However, I receive the following error message when trying to start my app.
```
NoMethodError: undefined method `ignore' for #<Airbrake::Config:0x007fb0df292718>
```

My configuration looks like:
```ruby
Airbrake.configure do |c|
  c.project_id = 'XXXX'
  c.project_key = 'YYY'
  c.root_directory = Rails.root
  c.logger = Rails.logger
  c.environment = Rails.env
  c.ignore_environments = %w(test)
  c.ignore << "SignalException"
end
```

What is the proper way to ignore exceptions in v5?

**Comment by kyrylo** [comment]
The `ignore` option is gone. Use the new `add_filter` API described in our [Migration Guide](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#ignore-by-filter).

**Comment by KurtPreston** [comment]
Thanks!

**Comment by kyrylo** [comment]
Make sure to have airbrake-5.0.2 and airbrake-ruby-1.0.2 installed because this API is broken in airbrake-ruby-1.0.0.

Happy Airbraking!

**Comment by imnotquitejack** [comment]
Probably want to update your https://github.com/airbrake/airbrake/wiki/Customizing-your-airbrake.rb !

**Comment by kyrylo** [comment]
The wiki is deprecated and should be used only for Airbrake v4. Read the README or the Migration Guide for v5 docs.
