### ISSUE TITLE
Important params are being filtered out despite being added to whitelist

### ISSUE THREAD

**Issue by blackjackcf** [airbrake/airbrake#488]
To prevent any sensitive information from leaking, I decided to just whitelist specific keys. However, the action and controller params are now being filtered, despite being added to the whitelist. I'm basically configuring the whitelist keys as is specified in the migration guide:

    Airbrake.whitelist_keys(['array_of_keys_here'])

Is there any way to allow those through?

**Comment by kyrylo** [comment]
Hi! I just tested this with a dummy app and it's working correctly for me.

This is how I filter:

```ruby
Airbrake.whitelist_keys(['action', 'controller', 'foo'])
```

Are you sure your config looks similar?
