### ISSUE TITLE
Error Manually Sending Notifications

### ISSUE THREAD

**Issue by igorgue** [airbrake/airbrake#502]
Hi guys,

I'm currently having an error manually sending notifications with version `5.0.4` it works perfectly on `5.0.3`.

Here's the error

```
[3] pry(main)> Airbrake.notify("Error", this_is: "This is a test")
=> nil
[4] pry(main)> E, [2016-02-08T12:27:42.085934 #30851] ERROR -- : **Airbrake: strconv.ParseInt: parsing "ss": invalid syntax
```

**Comment by kyrylo** [comment]
Hey! Could you show how you configured your notifier?

**Comment by igorgue** [comment]
Same config works in `5.0.3`.

```# Airbrake is an online tool that provides robust exception tracking in your Rails
# applications. In doing so, it allows you to easily review errors, tie an error
# to an individual piece of code, and trace the cause back to recent
# changes. Airbrake enables for easy categorization, searching, and prioritization
# of exceptions so that when errors occur, your team can quickly determine the
# root cause.
#
# Configuration details:
# https://github.com/airbrake/airbrake-ruby#configuration
Airbrake.configure do |c|
  # You must set both project_id & project_key. To find your project_id and
  # project_key navigate to your project's General Settings and copy the values
  # from the right sidebar.
  # https://github.com/airbrake/airbrake-ruby#project_id--project_key
  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.project_key = ENV['AIRBRAKE_API_KEY']

  # Configures the root directory of your project. Expects a String or a
  # Pathname, which represents the path to your project. Providing this option
  # helps us to filter out repetitive data from backtrace frames and link to
  # GitHub files from our dashboard.
  # https://github.com/airbrake/airbrake-ruby#root_directory
  c.root_directory = Rails.root

  # By default, Airbrake Ruby outputs to STDOUT. In Rails apps it makes sense to
  # use the Rails' logger.
  # https://github.com/airbrake/airbrake-ruby#logger
  c.logger = Rails.logger

  # Configures the environment the application is running in. Helps the Airbrake
  # dashboard to distinguish between exceptions occurring in different
  # environments. By default, it's not set.
  # NOTE: This option must be set in order to make the 'ignore_environments'
  # option work.
  # https://github.com/airbrake/airbrake-ruby#environment
  c.environment = Rails.env

  # Setting this option allows Airbrake to filter exceptions occurring in
  # unwanted environments such as :test. By default, it is equal to an empty
  # Array, which means Airbrake Ruby sends exceptions occurring in all
  # environments.
  # NOTE: This option *does not* work if you don't set the 'environment' option.
  # https://github.com/airbrake/airbrake-ruby#ignore_environments
  c.ignore_environments = %w(test)
end

# If Airbrake doesn't send any expected exceptions, we suggest to uncomment the
# line below. It might simplify debugging of background Airbrake workers, which
# can silently die.
# Thread.abort_on_exception = ['test', 'development'].include?(Rails.env)
```

**Comment by kyrylo** [comment]
The config looks good to me. So does it not work at all or only when you are trying to send it with `Airbrake.notify("Error", this_is: "This is a test")`?

Also, what's the version of `airbrake-ruby`? It's a dependency of `airbrake`.

**Comment by igorgue** [comment]
Hey, well weird, it works now, so I gonna close it... I wonder what I had wrong now.

**Comment by kyrylo** [comment]
My guess would be that it's some weird notice object, but given that you tried to send an error manually that does look weird. Maybe your backtrace had weird character in the path.

Anyway, don't hesitate to reopen if you see this error again. I'm happy to help.

**Comment by khpeek** [comment]
Hi, I'm getting the same error in Python trying to manually trigger an error message using `pybrake` with [Django integration](https://github.com/airbrake/pybrake#django-integration); I've described the issue in [this StackOverflow question](https://stackoverflow.com/questions/50615078/airbrake-throwing-error-pybrake-error-strconv-parseint-parsing-none-inv). How might I resolve this issue?

**Comment by kyrylo** [comment]
We didn’t find the root cause of the issue but it is probably notifier-specific so I recommend filing an issue at the Airbrake Django issue tracker.

**Comment by phumpal** [comment]
@kyrylo, @khpeek has a support issue for open for this item.

@khpeek would you mind opening an issue on the pybrake repo with this error?

**Comment by kyrylo** [comment]
Seems like it was resolved as per https://stackoverflow.com/questions/50615078/airbrake-throwing-error-pybrake-error-strconv-parseint-parsing-none-inv#comment88274811_50615756

Thanks for investigating it, @khpeek!
