### ISSUE TITLE
capistrano airbrake_env option no longer supported in Airbrake 5

### ISSUE THREAD

**Issue by wlipa** [airbrake/airbrake#506]
Airbrake 5 has dropped the airbrake_env option for Capistrano deploys that was present in Airbrake 4.  This allowed the environment to be set differently than rails_env.  This is useful when running multiple "shards" of a production application that are used for different customers.  Shards have different versions deployed and are configured differently, so it is useful to separate their exceptions in Airbrake.  Deployments to one shard should not affect exceptions in another shard.

I think the only effect of this option is to control the argument to the rake task that notifies Airbrake of a deployment.  The Capistrano task used to look like:

    airbrake_env = fetch(:airbrake_env, fetch(:rails_env, fetch(:stage)))
    notify_command = "airbrake:deploy"
    notify_command << " TO=#{airbrake_env}"
    notify_command << " REVISION=#{fetch(:current_revision)} REPO=#{fetch(:repo_url)}"
    notify_command << " USER=#{local_user.strip.shellescape}"

which would let us define :airbrake_env in our deployment rb file.  Now in Airbrake 5 it looks like:

    airbrake:deploy USERNAME=#{Shellwords.shellescape(local_user)} \
                    ENVIRONMENT=#{fetch(:rails_env, fetch(:stage))} \
                    REVISION=#{fetch(:current_revision)} \
                    REPOSITORY=#{fetch(:repo_url)} \
                    VERSION=#{fetch(:app_version)}

and the airbrake_env option is no longer supported.  Please bring this back, as it's a useful setting.

**Comment by wlipa** [comment]
Changing the ENVIRONMENT line to the following works for me:

    ENVIRONMENT=#{fetch(:airbrake_env, fetch(:rails_env, fetch(:stage)))} \

**Comment by kyrylo** [comment]
Thanks, that makes perfect sense. I'd be happy to accept a pull request with this change, if you wish.

**Comment by wlipa** [comment]
Sure, I will put one together.
