### ISSUE TITLE
Migration guide offers to lost information from NoticeBuilder

### ISSUE THREAD

**Issue by kimrgrey** [airbrake/airbrake#508]
Migration guide from v4 to v5 tells us that information about `ENV` was removed from `Notice` by default, but offers to add this support back using this code if it's needed:

```ruby
Airbrake.add_filter do |notice|
  notice[:environment] = ENV
end
```

But it looks like this advice is incompatible with latest changes in `Airbrake::Rack::NoticeBuilder`. All data which is added here: https://git.io/vgXbS, - will be lost. Suppose, assignment should be replaced with merge in Guide. Am I right?

**Comment by kyrylo** [comment]
Very fair point. I'd be happy to accept a pull request :)

**Comment by kimrgrey** [comment]
Sure. I just wanted to clarify that it's correct.  I'll send a PR just in a few minutes. As I understand, `notice[:environment]` is always a Hash. So, it's not needed to add check on nil, we can just merge any additional values. Right?

**Comment by kyrylo** [comment]
[Correct](https://github.com/airbrake/airbrake-ruby/blob/80c6ba2847f234f828fd9f711ec277edcc4122db/lib/airbrake-ruby/notice.rb#L65).

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake/issues/510.
