### ISSUE TITLE
Impossible to add addtional info about RACK env to the notice

### ISSUE THREAD

**Issue by kimrgrey** [airbrake/airbrake#509]
As I understand from code, there is only one point where information from RACK environment is available for `Notice`. It is `Rack::NoticeBuilder`. But it adds only specific type of information that is predefined. So, it is impossible to add `REMOTE_IP` or something like this to the created notice. Am I missed something? May be it's good idea to allow users extend `NoticeBuilder`?

**Comment by kyrylo** [comment]
That's correct. The idea is that the defaults should be good enough for everyone. I will think about the way to allow this, but if you have any ideas or examples, feel free to share. It's not straightforward.

**Comment by kimrgrey** [comment]
Well, it's almost not possible to satisfy everyone :smile: May be we it's good idea to allow users to create their own builders that is inherited from `Rack::NoticeBuilder` and after it configure `Airbrake` to use it?

**Comment by kimrgrey** [comment]
Hi, @kyrylo! What about this stuff? We really need to add some additional headers in our project. And I don't want to use monkey patching for it :disappointed:

**Comment by kyrylo** [comment]
Hey, @kimrgrey! Don't worry, you are not forgotten. I need some more time. This will be resolved during this week.

**Comment by kimrgrey** [comment]
Good news, thanks! I will follow up :wink:

**Comment by kyrylo** [comment]
What do you think about the following API:

```ruby
# config/initializers/airbrake.rb
# Standard config... and then...

module AirbrakeNoticeBuilderMetadata
  def add_metadata(notice)
    notice[:params][:remoteIp] = @rack_env['REMOTE_IP']
  end
end

class Airbrake::Rack::NoticeBuilder
  prepend AirbrakeNoticeBuilderMetadata
end
```

Plain Ruby, no shenanigans. You get access to everything you wish for. Might be a bit bare bones.

**Comment by kimrgrey** [comment]
Well, it looks like officially allowed monkey patching =) But, as for me, it's really simple solution, it's easy to add to the  current code and it solves the problem.

**Comment by kimrgrey** [comment]
@kyrylo, should I send a PR with this change?

**Comment by kimrgrey** [comment]
- [ ] account_accesses_controller.rb
- [ ] affiliates_controller.rb
- [ ] agreement_reports_controller.rb
- [ ] agreements_controller.rb
- [ ] announcements/announcements_controller.rb
- [ ] announcements/categories_controller.rb
- [ ] api_controller.rb
- [ ] application_controller.rb
- [ ] attachment_images_controller.rb
- [ ] attachments_controller.rb
- [ ] availability_controller.rb
- [ ] bankets_controller.rb
- [ ] bills_controller.rb
- [ ] callback_controller.rb
- [ ] calls_controller.rb
- [ ] comments_controller.rb
- [ ] concerns/after_sign_in.rb
- [ ] confirmations_controller.rb
- [ ] errors_controller.rb
- [ ] events/categories_controller.rb
- [ ] events/events_controller.rb
- [ ] events/occurrences_controller.rb
- [ ] events/schedules_controller.rb
- [ ] events/tickets_controller.rb
- [ ] mandrill_web_hooks_controller.rb
- [ ] metros_controller.rb
- [ ] omniauth_callbacks_controller.rb
- [ ] pages_controller.rb
- [ ] parcels_controller.rb
- [ ] passwords_controller.rb
- [ ] payments_controller.rb
- [ ] phones_controller.rb
- [ ] place/bankets_controller.rb
- [ ] place/reservations_controller.rb
- [ ] places/reviews_controller.rb
- [ ] places_controller.rb
- [ ] registrations_controller.rb
- [ ] reminders_controller.rb
- [ ] reports/agreements_controller.rb
- [ ] reports/bankets_controller.rb
- [ ] reports/bills_controller.rb
- [ ] reports/call_center_controller.rb
- [ ] reports/calls_controller.rb
- [ ] reports/cohorts_controller.rb
- [ ] reports/failed_requests_controller.rb
- [ ] reports/feed_controller.rb
- [ ] reports/marketing_controller.rb
- [ ] reports/operators_controller.rb
- [ ] reports/places_performance_controller.rb
- [ ] reports/reminders_controller.rb
- [ ] reports/reservations_controller.rb
- [ ] reports/reviews_controller.rb
- [ ] reports/sent_sms_controller.rb
- [ ] reports/summary_controller.rb
- [ ] reports/totals_controller.rb
- [ ] reports_controller.rb
- [ ] representatives_controller.rb
- [ ] reservations_controller.rb
- [ ] reviews/replies_controller.rb
- [ ] reviews_controller.rb
- [ ] sent_mails_controller.rb
- [ ] sessions_controller.rb
- [ ] settings/fields_controller.rb
- [ ] settings/incoming_phones_controller.rb
- [ ] settings/pages_controller.rb
- [ ] settings/users_controller.rb
- [ ] settings_controller.rb
- [ ] short_links_controller.rb
- [ ] sitemap_controller.rb
- [ ] taxonomies/categories_controller.rb
- [ ] taxonomies/cuisines_controller.rb
- [ ] taxonomies/groups_controller.rb
- [ ] taxonomies/occasions_controller.rb
- [ ] taxonomies/sets_controller.rb
- [ ] taxonomies/taxonomy_controller.rb
- [ ] timetables_controller.rb
- [ ] tracking_controller.rb
- [ ] versions_controller.rb
- [ ] vk_controller.rb
- [ ] yamoney_controller.rb

**Comment by kyrylo** [comment]
Sure, thanks. Naming improvements are also welcome. Don't hesitate to rethink the approach if it sucks.

**Comment by kimrgrey** [comment]
@kyrylo, may be we can use some kind of filters like in `Airbrake::Notifier`? In this case all this methods will be implemented like "standard" filters: https://git.io/v2flv. And we will allow users to add anything that they need. WDYT?

**Comment by kyrylo** [comment]
That sounds pretty general to be honest. If you have a concrete example, please share :) We still somehow need to pass `@rack_env`.

As of now I struggle to see problems with my approach. Yes, it's not extremely flexible, but does it need to be?

**Comment by kimrgrey** [comment]
> As of now I struggle to see problems with my approach. Yes, it's not extremely flexible, but does it need to be?

Well, it's not about flexibility, it's more about "bare bones", as you said before. Because methods `add_context`, `add_session`, `add_params` and `add_environment` in `NoticeBuilder` are private. And now we want to add another one - `add_metadata`. And call it from `build_notice`. Should it be private, too? By current logic - yes. But, you know, it's not good idea to override private methods from any place, but especially from the outside of class hierarchy =) And should it be just empty by default? It's ugly =( I think the system of filters looks much more familiar for any Rails user. 

Well, ok, I will make some experiments and share the results.

**Comment by kyrylo** [comment]
"Ugly" is a subjective term, I prefer to avoid it. If this is the only problem in your opinion, then it's fine =P The benefit is that we already know how it works and how to implement it. It also won't mess up the existing well tested class. In terms of lines of code the change will also be compact. Will it be hard to modify the implementation once people start depend on it? Yes. I think this is what needs to be solved so it can be production ready.

That said, I'd be curious to see the system of filters at least described on paper. That is, how do you plan to pass `@rack_env` or any other internal data? If you wish, I could write the "ugly" implementation and try to make it look less like bare bones. You, in turn, could write your filter approach (feel free to ask questions while writing it), so we could compare and decide what approach is the best.

What do you think?

**Comment by kyrylo** [comment]
Let me know if you're not interested.

**Comment by kimrgrey** [comment]
More than anybody else :wink:  

Do you know a good way to test an approach with prepending of the module? I've added this code in `notice_builder_spec` just to be sure that everything works but I don't think that it's good idea to leave it like this, because described class will be permanently extended in this case:

```ruby
RSpec.describe Airbrake::Rack::NoticeBuilder do
  # previous specs here....
  
  context "when add_metadata is implemented" do
    described_class.class_eval do
      prepend Module.new {
        def add_metadata(notice)
          notice[:params][:remoteIp] = @rack_env['REMOTE_IP']
        end
      }
    end

    it "calls add_metadata" do
      notice_builder = described_class.new({ 'REMOTE_IP' => '127.0.0.1' })
      notice = notice_builder.build_notice(AirbrakeTestError.new)
      expect(notice[:params][:remoteIp]).to eq("127.0.0.1")
    end
  end
end
```

**Comment by kyrylo** [comment]
`dup` it?

**Comment by kimrgrey** [comment]
Please, take a look on this PR: https://github.com/airbrake/airbrake/pull/516. Is it implements what you expected?

**Comment by kimrgrey** [comment]
Hmmm... Is Ruby 1.9.x supported by Airbrake? We are not able to use `prepend` in this case :disappointed:

**Comment by kimrgrey** [comment]
And what about another one implementation, I think it could be something like this: https://github.com/airbrake/airbrake/pull/517.

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake/pull/517.
