### ISSUE TITLE
JSON-style hash breaking Airbrake 4 in old rubies

### ISSUE THREAD

**Issue by garyv** [airbrake/airbrake#511]
Airbrake 4.3.5 is breaking in ruby 1.8.7 because this of JSON-style hash syntax added in this commit.

https://github.com/airbrake/airbrake/commit/afe85f8039fa52c67b2d2fd1935f60cb1835e0b2#diff-2ac19359e5b6229d824220ccf4d52bd1R179

I recommend making it a Hashrocket, at least in the V4 branch.

**Comment by kimrgrey** [comment]
By the way, is Airbrake really steal officially supports Ruby 1.8 and Ruby EE?

**Comment by garyv** [comment]
Version 5, the current version of Airbrake, does not support Ruby 1.8. Version 4, however, is supposed to maintain support. 

From [README.md](https://github.com/airbrake/airbrake/tree/v5.0.4#airbrake-v5-is-already-here-but-we-still-support-airbrake-v4)

> 
Since the 5th major release of the Airbrake gem we support only Rails 3.2+ and Ruby 1.9+. Don't worry, if you use older versions of Rails or Ruby, just continue using them with Airbrake v4: we still support it. However, v4 is feature frozen. We accept only bugfixes.

**Comment by kimrgrey** [comment]
Well, it this case I'm :+1: for this PR. And may be it's good idea to add a rule that prohibits not "hashrocket" syntax in the rubocop for airbrake 4.x to avoid such problems. Is it possible?

**Comment by kyrylo** [comment]
I am sorry about breaking 1.8.7. I confirm, we still support it, but only for Airbrake v4.

> @kimrgrey 
>  [...] rubocop for airbrake 4.x [...]

Unfortunately, Airbrake v4 didn't check itself with Rubocop.

**Comment by kyrylo** [comment]
Just released v4.3.6 https://rubygems.org/gems/airbrake/versions/4.3.6.

**Comment by kimrgrey** [comment]
@kyrylo, thank you! :+1:
