### ISSUE TITLE
How to access configuration in Javascript?

### ISSUE THREAD

**Issue by krisleech** [airbrake/airbrake#524]
We are in the process of upgrading to v5. Our Javascript integration uses data attributes on the body tag to store the `project_id` and `project_key`. These are then read in order to configure the Airbrake Javascript client.

```haml
= javascript_include_tag "application", 'data-airbrake-project-id' => Airbrake.configuration[:project_id]
```

However it seems the configuration, `Airbrake.configuration`, is not longer accessible. I checked the source and I couldn't see a way to get this information. Is there a way?

It would be preferable not to have to have the configuration repeated in both Ruby and Javascript.

**Comment by kyrylo** [comment]
Thanks for the question. Normally these values are assigned to environment variables, so you could access them via `ENV['AIRBRAKE_PROJECT_ID']`. Indeed, there's no way to read them through `Airbrake.configuration` anymore.

In your case it's possible to:

1. Use environment variables
2. Use 2 Airbrake projects so each of them would require its own unique values (probably not what you want, but I would use 2 separate projects for Ruby and JS)
3. Write the values inline (which isn't a big deal, if you ask me)

**Comment by krisleech** [comment]
@kyrylo Thanks. I'll move them to `settings.yml`.
