### ISSUE TITLE
custom context data on Sidekiq Exception

### ISSUE THREAD

**Issue by antnvtkvsk** [airbrake/airbrake#528]
how can I paste some important context details to ```Airbrake#notify``` from a Sidekiq worker with default Airbrake Sidekiq error handler? there was ```exception.to_hash``` on notice building previously(in v4)

**Comment by kyrylo** [comment]
Could you link me to the relevant documentation or provide some code that demonstrates what you want to achieve?

**Comment by antnvtkvsk** [comment]
[here](https://github.com/airbrake/airbrake/blob/airbrake-v4/lib/airbrake/sidekiq.rb) is Sidekiq error handler in Airbrake v.4
[here](https://github.com/airbrake/airbrake/blob/airbrake-v4/lib/airbrake.rb#L178) is exception's `to_hash` merged to options for notice creation

so I could implement `to_hash` for my exception with `cgi_data` key to get any custom information on Airbrake

unfortunately, there is no `to_hash` method calling anymore in version 5 and I cant create own sidekiq airbrake error handler instead of default one with fixed parameters. but I still need some comprehensive data in Airbrake logs.

**Comment by kyrylo** [comment]
Thanks for the detailed explanation. I'd like to clarify, are you interested in the `context` object from [here](https://github.com/airbrake/airbrake/blob/airbrake-v4/lib/airbrake/sidekiq.rb#L6)?
If that is so, then this object should be sent to Airbrake entirely, so you don't need to add anything. If you want to attach some custom information, you can use the [`add_filter` API](https://github.com/airbrake/airbrake-ruby#airbrakeadd_filter). 

If that's not enough to accomplish what you want, could you please describe what you want to attach? Perhaps, we could send such information by default?

**Comment by antnvtkvsk** [comment]
oh, thanks a lot. solved with filters :sunny:

**Comment by kyrylo** [comment]
Don't hesitate to ask in case you have more questions about the library :wink:
