### ISSUE TITLE
No ignored-by-default exceptions in v5?

### ISSUE THREAD

**Issue by JasonBarnabe** [airbrake/airbrake#529]
In v4, [numerous exceptions were ignored by default](https://github.com/airbrake/airbrake/wiki/Customizing-your-airbrake.rb#ignoring-errors-certain-types-of-errors). In v5, the [ignore feature was replaced by the add_filter API](https://github.com/airbrake/airbrake/blob/23457a14144013959ffc4f54683238929e30f908/docs/Migration_guide_from_v4_to_v5.md#configuration).

After upgrading my app to v5, airbrake is reporting `ActiveRecord::RecordNotFound` exceptions. Does this mean v5 no longer ignores certain exceptions by default? Was this intentional? Should it belong in the upgrade guide?

**Comment by kyrylo** [comment]
Hi! Correct, we don't make any assumptions anymore. This was intentional. It's mentioned in our migration guide [here](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#default-ignored-classes).
