### ISSUE TITLE
Same exceptions occurred from ActiveJob have different action values

### ISSUE THREAD

**Issue by thefron** [airbrake/airbrake#532]
Hi, I'm using sidekiq as queue adapter of active_job.
Recently I noticed every occurrence of exceptions like `ActiveRecord::RecordInvalid` is grouped separately on airbrake dashboard.
The reason turned out to be different action value of each occurrence differs since exception handler of activejob is assigning `job_id` for action value.(https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/active_job.rb#L13)
I think name of the worker class should be an action value instead of job_id since it's uuid as in sidekiq middleware(https://github.com/airbrake/airbrake/blob/master/lib/airbrake/sidekiq/error_handler.rb).

**Comment by kyrylo** [comment]
Thanks for the bug report. A few hours ago we released a new gem with the fix. Happy Airbraking!
