### ISSUE TITLE
Configuration for ActiveJob + Resque

### ISSUE THREAD

**Issue by dan-manges** [airbrake/airbrake#540]
* Airbrake version: 5.2.3
* Airbrake-ruby version: 1.2.2
* Ruby version: 2.2.4
* Framework name & version: Rails 4.2.6
* ActiveJob version: 4.2.6
* Resque version: 1.26.0

#### Airbrake config

```ruby
Airbrake.configure do |c|
  c.project_id = ENVVARS["AIRBRAKE_PROJECT_ID"]
  c.project_key = ENVVARS["AIRBRAKE_PROJECT_KEY"]

  c.root_directory = Rails.root
  c.logger = Rails.logger
  c.environment = Rails.env
  c.ignore_environments = %w(development test)
end

Airbrake.add_filter do |notice|
  unless ENVVARS["AIRBRAKE_REPORTING"] == "enabled"
    notice.ignore!
  end
end
```

#### Description

We're using Airbrake with Resque run via ActiveJob. In the Airbrake README, it says that no configuration should be required when using ActiveJob.

We weren't getting error reports from background jobs. We looked into it and figured out that Resque is forking its worker process for each job that it runs. With Airbrake sending notifications asynchronously, the forked process was exiting before the Airbrake thread could send the notification.

We fixed this by adding this to our config:

```ruby
Resque.after_fork do
  at_exit { Airbrake.close }
end
```

We also had to set `ENV["RUN_AT_EXIT_HOOKS"]` for Resque.

It took a while to figure this out, so I'd like to contribute something to Airbrake to save other people who run into this same issue some time. Should there be an update to the README for this? I couldn't think of a way to update the code, but I'm happy to create a PR if somebody has a suggestion.

**Comment by kyrylo** [comment]
Hey @dan-manges! I've submitted a patch to fix this issue. Our Resque integration is synchronous, so we should probably be async in case of ActiveJob+Resque, too. Could you please verify that the following PR works for you? https://github.com/airbrake/airbrake/pull/542

P.S. Interesting approach with `AIRBRAKE_REPORTING`. Another way to write this would be `Airbrake.add_filter(&:ignore!) if ENVVARS["AIRBRAKE_REPORTING"] == "enabled"`

**Comment by dan-manges** [comment]
Hi @kyrylo, thanks for the fix! I tested using the code in that PR and it worked.

Thanks for the tip on the filter too.
