### ISSUE TITLE
Errors not being ignored

### ISSUE THREAD

**Issue by constantm** [airbrake/airbrake#541]
I'm trying to ignore certain errors, but it's not working. Not sure if it's a bug or whether I'm doing it wrong, probably the latter. :)

* Airbrake version: 5.2.3
* Airbrake-ruby version: 1.2.2
* Ruby version: 2.2.4
* Rails: 4.2.6

```ruby
# /config/initializers/airbrake.rb
Airbrake.add_filter do |notice|
  if notice[:type] == 'Intercom::ServiceUnavailableError'
    notice.ignore!
  end
end
```

The above error getting reported in the web interface:

```
Error type	             Intercom::ServiceUnavailableError
Error message	         Sorry, the API service is temporarily unavailable
Where	                 delayed_job#Delayed::PerformableMethod
```

**Comment by kyrylo** [comment]
Hey, @constantm! Are you sure `airbrake.rb` is in the correct directory? Normally, it should be in _config/initiali**z**ers_, not in _config/initiali**s**ers_.

**Comment by constantm** [comment]
Yup, it's in the same directory as the rest of our initialisers. (we don't use z's this side of the planet. 😬)

**Comment by kyrylo** [comment]
Heh, thanks for the info. Well, this looks normal to me. This error occurred in a job, so maybe this is why we don't filter it (it might be a bug). I'll investigate this possible scenario on Monday and let you know.

P.S. Could you share your full config?

**Comment by constantm** [comment]
Sure, here's my airbrake.rb initialiser. Let me know if you need anything else.

```RUBY
# Airbrake is an online tool that provides robust exception tracking in your Rails
# applications. In doing so, it allows you to easily review errors, tie an error
# to an individual piece of code, and trace the cause back to recent
# changes. Airbrake enables for easy categorization, searching, and prioritization
# of exceptions so that when errors occur, your team can quickly determine the
# root cause.
#
# Configuration details:
# https://github.com/airbrake/airbrake-ruby#configuration
Airbrake.configure do |c|
  # You must set both project_id & project_key. To find your project_id and
  # project_key navigate to your project's General Settings and copy the values
  # from the right sidebar.
  # https://github.com/airbrake/airbrake-ruby#project_id--project_key
  c.project_id = 'xxxxx'
  c.project_key = 'xxxxxxx'

  # Configures the root directory of your project. Expects a String or a
  # Pathname, which represents the path to your project. Providing this option
  # helps us to filter out repetitive data from backtrace frames and link to
  # GitHub files from our dashboard.
  # https://github.com/airbrake/airbrake-ruby#root_directory
  c.root_directory = Rails.root

  # By default, Airbrake Ruby outputs to STDOUT. In Rails apps it makes sense to
  # use the Rails' logger.
  # https://github.com/airbrake/airbrake-ruby#logger
  c.logger = Rails.logger

  # Configures the environment the application is running in. Helps the Airbrake
  # dashboard to distinguish between exceptions occurring in different
  # environments. By default, it's not set.
  # NOTE: This option must be set in order to make the 'ignore_environments'
  # option work.
  # https://github.com/airbrake/airbrake-ruby#environment
  c.environment = Rails.env

  # Setting this option allows Airbrake to filter exceptions occurring in
  # unwanted environments such as :test. By default, it is equal to an empty
  # Array, which means Airbrake Ruby sends exceptions occurring in all
  # environments.
  # NOTE: This option *does not* work if you don't set the 'environment' option.
  # https://github.com/airbrake/airbrake-ruby#ignore_environments
  c.ignore_environments = %w(test development)

end

Airbrake.add_filter do |notice|
  # Ignore 404s for when admin is not logged in and tries to match disciplines
  if notice[:context][:url] == 'https://leap.ly/md'
    notice.ignore!
  end

  if notice[:type] == 'Intercom::ServiceUnavailableError'
    notice.ignore!
  end

  if notice[:type] == 'Intercom::ResourceNotFound'
    notice.ignore!
  end

  if notice[:type] == 'SignalException' #HAPPENS ON DEPLOY
    notice.ignore!
  end
end
```

**Comment by kyrylo** [comment]
Thanks for the config. So is the problem only with `Intercom::ServiceUnavailableError` or also with all the exceptions you try to ignore?

**Comment by constantm** [comment]
All of them.

**Comment by constantm** [comment]
Any progress on this?

**Comment by kyrylo** [comment]
Hey, Constant! Big sorry for the delay. There are some good news, though. It took me a while to notice that your filters are not configured correctly. One notice can carry multiple errors, hence the filter should look like this:

```ruby
Airbrake.add_filter do |notice|
  if notice[:errors].any? { |error| error[:type] == 'Intercom::ServiceUnavailableError' }
    notice.ignore!
  end
end
```

And it should just work :) 

I am curious though, where did you read about the API that you used? Perhaps, we have some bad documentation somewhere?

**Comment by kyrylo** [comment]
Let me know if you still have issues.

**Comment by constantm** [comment]
Thanks @kyrylo. My turn to apologise - I was away for a week. :) I'll give that a try and let you know if it doesn't work. I'm afraid that I have no idea where I got that config from.

**Comment by phstc** [comment]
```ruby
if notice[:errors].any? { |error| error[:type] == 'Intercom::ServiceUnavailableError' }
    notice.ignore!
end
```

@kyrylo If `notice[:errors]` has also some exceptions that we want to track, wouldn't that cause of them to be ignore?

**Comment by kyrylo** [comment]
Correct, the code you showed would do that.

**Comment by phstc** [comment]
@kyrylo how can I skip only in case of `Intercom::ServiceUnavailableError`? I don't want to skip the whole batch, I want to skip only certain exceptions.

**Comment by kyrylo** [comment]
`notice[:errors]` carries nested exceptions, so if you ignore `Intercom::ServiceUnavailableError` in most of the cases it means you don't care about the nested exception, too. `notice[:errors][0]` would return the most recent exception and next indices represent how many times it was re-raised (so `notice[:errors][-1]` is the original exception). Filtering mechanism is quite flexible, since it's all plain Ruby, so you are free to construct your ignore conditions like you want: there's no boundaries.
