### ISSUE TITLE
Can't Parse

### ISSUE THREAD

**Issue by mastertechrv** [airbrake/airbrake#543]
raise Airbrake::Error, "can't parse '#{stackframe}'"

**Comment by kyrylo** [comment]
Please show an example of a stack frame that couldn't be parsed.

**Comment by shakycode** [comment]
@mastertechrv You need to provide more detail on your issue.  This will help the community better resolve your problem.  Please provide the example stackframe and any other relevant information such as gem version, ruby version, rails version, etc.

**Comment by mastertechrv** [comment]
`airbrake-ruby (1.1.0) lib/airbrake-ruby/backtrace.rb:93:in `match_frame'
airbrake-ruby (1.1.0) lib/airbrake-ruby/backtrace.rb:63:in `block in parse'
airbrake-ruby (1.1.0) lib/airbrake-ruby/backtrace.rb:62:in `map'
airbrake-ruby (1.1.0) lib/airbrake-ruby/backtrace.rb:62:in `parse'
airbrake-ruby (1.1.0) lib/airbrake-ruby/nested_exception.rb:19:in `block in as_json'
airbrake-ruby (1.1.0) lib/airbrake-ruby/nested_exception.rb:16:in `map'
airbrake-ruby (1.1.0) lib/airbrake-ruby/nested_exception.rb:16:in `as_json'
airbrake-ruby (1.1.0) lib/airbrake-ruby/notice.rb:63:in `initialize'
airbrake-ruby (1.1.0) lib/airbrake-ruby/notifier.rb:84:in `new'
airbrake-ruby (1.1.0) lib/airbrake-ruby/notifier.rb:84:in `build_notice'
airbrake-ruby (1.1.0) lib/airbrake-ruby.rb:282:in `call_notifier'
airbrake-ruby (1.1.0) lib/airbrake-ruby.rb:238:in `build_notice'
airbrake (5.0.5) lib/airbrake/rack/notice_builder.rb:41:in `build_notice'
airbrake (5.0.5) lib/airbrake/rack/middleware.rb:40:in `notify_airbrake'
airbrake (5.0.5) lib/airbrake/rack/middleware.rb:24:in `rescue in call'
airbrake (5.0.5) lib/airbrake/rack/middleware.rb:21:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
request_store (1.3.0) lib/request_store/middleware.rb:9:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.2.4) lib/rails/engine.rb:518:in `call'
railties (4.2.4) lib/rails/application.rb:165:in `call'
newrelic_rpm (3.14.2.312) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/Users/serveradmin/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/serveradmin/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/serveradmin/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'`

Gem Version: 5.0.5
Ruby Version: 2.2.3
Rails Version: 4.2.4

Running in production mode locally,

**Comment by kyrylo** [comment]
Thanks for the additional info. Try to upgrade the `airbrake` gem. This was fixed somewhere in between your version and current release (v5.2.3).

**Comment by mastertechrv** [comment]
ok ill let you know

**Comment by mastertechrv** [comment]
Updated Gem from 5.0.5 to 5.2.3 fixed the issue,

**Comment by kyrylo** [comment]
Happy Airbraking :+1:
