### ISSUE TITLE
adding remote_ip to notice environment

### ISSUE THREAD

**Issue by ql** [airbrake/airbrake#544]
Hello!
Is it possible to add remote ip to each error notice when using Airbrake in Rails?

**Comment by kimrgrey** [comment]
@ql, hi! Yep, this ability has been introduced by this PR: https://github.com/airbrake/airbrake/pull/517. Take a look on the example in description.

**Comment by kimrgrey** [comment]
@ql and this part of README contains the same example: https://github.com/airbrake/airbrake#rack

**Comment by kyrylo** [comment]
A+ support, nothing more to add :)
