### ISSUE TITLE
Disable Airbrake when not configured?

### ISSUE THREAD

**Issue by khustochka** [airbrake/airbrake#546]
In Airbrake v4 I used to do this:

````ruby
# config/initializers/airbrake.rb
if ENV['AIRBRAKE_API_KEY']
  Airbrake.configure do |config|
    config.api_key = ENV['AIRBRAKE_API_KEY']
  end
end
````

And it worked as I expected: if AIRBRAKE_API_KEY environment variable was not set Airbrake was silent. It was OK in development, test, and on staging servers that ran in production mode but had no need in error reporting.

After upgrade to v5 I wanted to do the same:

````ruby
# config/initializers/airbrake.rb
if ENV['AIRBRAKE_PROJECT_ID'] && ENV['AIRBRAKE_API_KEY']
  Airbrake.configure do |config|
    config.project_id = ENV['AIRBRAKE_PROJECT_ID']
    config.project_key = ENV['AIRBRAKE_API_KEY']
    config.environment = Rails.env
  end
end
````

But this time it did not work, every exception was replaced with the notorious `Airbrake::Error (the 'default' notifier isn't configured)`! So now if I include airbrake in the project I am forced to always configure it. Even if I want to make use of `ignore_environments` I have to provide project id and key.

As a workaround I tried the following:
1. Declare `gem "airbrake", require: false` in `Gemfile`
2. In `config/initializers/airbrake.rb`:

````ruby
if ENV['AIRBRAKE_API_KEY'] && ENV['AIRBRAKE_API_KEY']
  require "airbrake"
  Airbrake.configure do |config|
    ......
  end
end
````
But this did not work with an opposite effect: errors were not sent to airbrake even when keys were properly provided. I may spent some time later to investigate why exactly this happens.

So... I do not know if this was intended behaviour or not, but for me it seems reasonable to have a way to completely disable or silence Airbrake even if the gem is included in the project. Personally I would prefer the way it worked in v4, if you do not call Airbrake.configure it is not activated, but there may be other possible solutions.

**Comment by kyrylo** [comment]
Hey, @khustochka! Would the following code be enough to meet your expectations?

```
Airbrake.add_filter(&:ignore!) unless ENV['AIRBRAKE_API_KEY']
```

**Comment by khustochka** [comment]
Thanks, I was able to make it into a workaround. 

As I understand to call `Airbrake.add_filter` notifier should already be configured, and when I am configuring it I cannot leave project key and id blank, so I have to replace it with dummy values:

````
Airbrake.configure do |config|
  config.project_id = ENV['AIRBRAKE_PROJECT_ID''] || true
  config.project_key = ENV['AIRBRAKE_API_KEY'] || "dummy"
  config.environment = Rails.env
end

unless ENV['AIRBRAKE_API_KEY'] && ENV['AIRBRAKE_PROJECT_ID']
  Airbrake.add_filter(&:ignore!)
end
````

This way it works but I still feel uneasy I have to configure it with some dummy values just to ignore.

I do not know if I make any sense :) Please tell if I am missing something.

**Comment by kyrylo** [comment]
I do admit this is an annoying issue and it confuses a lot of people. The logic here was that if you want to require the airbrake gem, then you always want to capture errors. But I can see that in reality it's not quite like that.

I've heard enough complaints about this behaviour, so [it's high time to get rid of this](https://github.com/airbrake/airbrake-ruby/pull/75). Thanks for bringing up this issue!
