### ISSUE TITLE
Pipeline + React stopping Airbrake with non-descript Error instead of Explanitory Rails Error.

### ISSUE THREAD

**Issue by atebit** [airbrake/airbrake#554]
This is because of a syntax error in the asset pipeline compile. I have :development environment ignored.. Any thoughts would be super helpful. I don't want to have to remove just to test new react components..

<img width="1089" alt="screen shot 2016-05-24 at 4 52 30 pm" src="https://cloud.githubusercontent.com/assets/6557296/15521180/fb1b7162-21cf-11e6-8233-02c683f55341.png">

**Comment by kyrylo** [comment]
Please share your config.
