### ISSUE TITLE
NoMethodError: undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by mberube** [airbrake/airbrake#557]
Airbrake 5.4
Airbrake-ruby 1.4.1
Ruby 2.1.6
Rails 4.2.5.1

Airbrake reports these errors with backtraces.

My airbrake config is:
Airbrake.configure do |config|
  config.project_id = 'xxxxx'
  config.project_key = 'xxxxxxxxxxxxxxxxxx'
  config.environment = Rails.env
  config.ignore_environments = %w(development test)
end

I saw issues #497 and #490 but they are both marked as fixed and I have the same issue even after upgrading to airbrake 5.4 and airbrake-ruby 1.4.1. We are using nginx, not passenger like the issues seem to mention.

The errors provide no stack trace and I don't see any reference to the error in our logs.

Any idea on what the issue might be this time?

For reference, the context looks like:

{
  "environment": "production",
  "hostname": "xxxxxx",
  "language": "ruby/2.1.6",
  "notifier": {
    "name": "airbrake-ruby",
    "url": "https://github.com/airbrake/airbrake-ruby",
    "version": "1.4.1"
  },
  "os": "x86_64-linux",
  "remoteAddr": "xxx.xxx.xxx.xxx"
}

**Comment by kyrylo** [comment]
1. When did this start happening?
2. What was the first version of airbrake-ruby that caught it?
3. Did you do any configuration changes?
3. Please send your account name and project name with this error to me: `kyrylo@airbrake.io`.
3. I suggest to use this temporary workaround to get rid of the error:

  ```rb
  Airbrake.add_filter do |notice|
    # See: https://github.com/phusion/passenger/issues/1730
    passenger_error = proc do |error|
      error[:backtrace].empty? &&
        error[:type] == 'NoMethodError' && 
        error[:message] =~ %r{undefined method `call'}
    end

    notice.ignore! if notice[:errors].any?(&passenger_error)
  end
  ```

**Comment by mberube** [comment]
I am sorry, it seems that we are actually using passenger (a rather old version 4.x), so it's most likely the same bug... We probably just need to wait until our infrastructure gets upgraded to the latest passenger version...

Sorry about the confusion.

**Comment by kyrylo** [comment]
Hey, no worries. Yeah, it looks like it's the same bug. Still, you can use the workaround I suggested to ignore this error. Happy Airbraking!
