### ISSUE TITLE
Airbrake reports during rspec

### ISSUE THREAD

**Issue by haraldkrischner** [airbrake/airbrake#558]
Airbrake is configured to report to our Heroku Errbit instance. That worked well until the update to Airbrake 5. We set up a new Errbit server and the error reporting itself seems to work well.

Problem is:
Specs do now fail because Airbrake tries to report.. We have got Webmock running and thus the call is blocked, but this behaviour doesn't work out.. A single spec always succeeds. Some combinations of spec do not.
Adding :test and :development to ignored_environments does not help.
Setting the worker count to 5 seems to help but that is not a desired solution from my point of view.

I get a warning: 
W, [2016-06-10T14:20:19.391274 #31006]  WARN -- : **Airbrake: falling back to sync delivery because there are no running async workers

Is it possisble that the async workers were correctly muted in the test environment. But the fallback causes airbrake to me no more muted?

Airbrake 5.4.0
Sidekiq 4.1.2
Ruby 2.3.0

**Comment by kyrylo** [comment]
1. Please share your full Airbrake config
2. Make sure you use `airbrake-ruby-1.4.2` (`bundle update airbrake-ruby`).

**Comment by haraldkrischner** [comment]
Airbrake.configure do |config|
  config.host = 'https://xx.herokuapp.com'
  config.project_id = Figaro.env.airbrake_project_id
  config.project_key= Figaro.env.airbrake_project_key
end

Problem persists with  airbrake-ruby-1.4.2 (was 1.4.1)

**Comment by kyrylo** [comment]
Try this:

```rb
Airbrake.configure do |config|
  config.host = 'https://xx.herokuapp.com'
  config.project_id = Figaro.env.airbrake_project_id
  config.project_key= Figaro.env.airbrake_project_key
  config.environment = Rails.env # (or whatever framework you are using)
  config.ignore_environments = [:test]
end
```

The key thing here is to specify `environment` *along with* `ignore_environments`.

**Comment by kyrylo** [comment]
Sorry, this is likely won't work. Make sure that `:test` is actually a string `'test'`. I corrected my example.

**Comment by kyrylo** [comment]
The rule here is to make sure types of `environment` and types of elements in the `ignore_environments` Array match. I guess I'll fix this, since this is quite annoying to deal with.

**Comment by haraldkrischner** [comment]
Ahh, great, your example did the job. Thanks a lot for your quick response! Issue can be closed.

**Comment by kyrylo** [comment]
Nice one! I'm going to keep this open until I fix the issue described in https://github.com/airbrake/airbrake/issues/558#issuecomment-225173073.

**Comment by dsandstrom** [comment]
@kyrylo Is adding the enviroment to the initializer required now?  I'm upgrading our Errbit app so I can use the new API and was getting `development` for the environment no matter what I specified as the `RAILS_ENV` in my staging app.

**Comment by kyrylo** [comment]
Yeah. If you want to make `ignore_environments` work, you have to specify `environment`. If you don't specify it, it will be `nil`.

**Comment by dsandstrom** [comment]
Thanks.  I'm asking if I have to specify the environment in a app's initializer in order for the Errbit/Airbrake app to know which environment the error came from?  Or is that a bug with Errbit?

**Comment by kyrylo** [comment]
Yes, you need to specify the environment. The library doesn't make assumptions.

**Comment by haraldkrischner** [comment]
Perhaps this is worth mentioning in the docs?

**Comment by kyrylo** [comment]
I think it's mentioned here: https://github.com/airbrake/airbrake-ruby#environment

**Comment by dsandstrom** [comment]
And in the [migration guide](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md), which I saw after asking.
