### ISSUE TITLE
Capistrano deploy notification with multiple rake installs

### ISSUE THREAD

**Issue by fsmanuel** [airbrake/airbrake#563]
I get this error:
> Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 11.1.2. Prepending `bundle exec` to your command may solve this.

Is it intentional that the gem does not use `bundle exec rake`:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/capistrano/tasks.rb#L10

Do I have to use [capistrano/bundler](https://github.com/capistrano/bundler/) to make it work?

**Comment by kyrylo** [comment]
It is intentional, yes. I thought `execute` was handling Bundler. 
I haven't really checked how [capistrano/bundler](https://github.com/capistrano/bundler/) fares, but if it's not too hard for you to test it, I'd be really grateful for that. We might need a fix (or documentation update here).

**Comment by fsmanuel** [comment]
@kyrylo Thanks for the clarification.
As far as I know we would need `execute :bundle, :exec, :rake, <<-CMD`

My problem with capistrano/bundler is that it [pushes](https://github.com/capistrano/bundler/blob/master/lib/capistrano/tasks/bundler.cap#L50) a prefix to the `bundle_bins` and I'm not sure if it plays nice with my setup. I'll test it and let you know how it turned out.

**Comment by fsmanuel** [comment]
@kyrylo capistrano/bundler doesn't work with my setup. Should I open a PR that makes it configurable?

```ruby
            execute *fetch(:rake_command, :rake), <<-CMD
              airbrake:deploy USERNAME=#{Shellwords.shellescape(local_user)} \
                              ENVIRONMENT=#{fetch(:airbrake_env, fetch(:rails_env, fetch(:stage)))} \
                              REVISION=#{fetch(:current_revision)} \
                              REPOSITORY=#{fetch(:repo_url)} \
                              VERSION=#{fetch(:app_version)}
            CMD
```

That way I could do `set(:rake_command, [:bundle, :exec, :rake])`

**Comment by kyrylo** [comment]
I think making an assumption that bundler is always present is safe enough. Let's use `execute :bundle, :exec, :rake` directly. I'd be happy to accept a PR :)

**Comment by fsmanuel** [comment]
@kyrylo done!
