### ISSUE TITLE
How to start the airbrake from commandline

### ISSUE THREAD

**Issue by lakshmivrv** [airbrake/airbrake#569]
I've run this command from command line 

airbrake

I am getting the following error: 

/usr/lib/ruby/1.9.1/rubygems.rb:317:in `bin_path': can't find gem airbrake ([">= 0"]) with executable airbrake (Gem::GemNotFoundException)
	from /usr/local/bin/airbrake:24:in `<main>'

How do I start the airbrake from commandline?

**Comment by kyrylo** [comment]
With version 5 it's not possible anymore.
