### ISSUE TITLE
rails g airbrake doesn't exist 5.4.1 release

### ISSUE THREAD

**Issue by rstormsf** [airbrake/airbrake#573]
It just doesn't work :-( 

It's sooo weird:
I created new rails5 project - generator works fine,
created new rails 4.2.6 project - works fine

in my current project with 4.2.6 - generator doesn't exist :-( I don't understand why

**UPDATE:** I think something is broken in my local gems, I installed rbenv-gemset in order to keep gems from system install

Not sure what happened, cloned repo clean and now everything works

**Comment by kyrylo** [comment]
Well, what can I say? Happy Airbraking ;)
