### ISSUE TITLE
rake airbrake:install_heroku_deploy_hook parsing env vars inocrrectly

### ISSUE THREAD

**Issue by seku** [airbrake/airbrake#574]
bundle exec rake airbrake:install_heroku_deploy_hook HEROKU_APP=<APP_NAME> --trace
** Invoke airbrake:install_heroku_deploy_hook (first_time)
** Execute airbrake:install_heroku_deploy_hook
rake aborted!
ArgumentError: odd number of arguments for Hash

Error place:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rake/tasks.rb#L95

Hash["1", "2", "3"]
ArgumentError: odd number of arguments for Hash

The reason is that i have in config vars values which contain "=" sign and splitting return 3 objects 
i.e:

`SPREADSHEET_URL:  https://docs.google.com/spreadsheet/pub?key=111111111111111111111111`

Fix would be appreciated

**Comment by seku** [comment]
Fix proposal (tested only once):
`h.merge!(Hash[*line.rstrip.split('=', 2)])`

**Comment by kyrylo** [comment]
@seku hey, thanks for the bug report. Could please confirm this fix works for you? https://github.com/airbrake/airbrake/pull/577

**Comment by seku** [comment]
@kyrylo confirmed !
