### ISSUE TITLE
Airbrake v4 deprecation

### ISSUE THREAD

**Issue by kyrylo** [airbrake/airbrake#596]
Airbrake v4 was first released on May 27, 2014. The latest update to the library was on June 24, 2016, which was the release of v4.3.8. 

Airbrake v5 was first released on December 18, 2015. It was created to replace v4. As you may know, we are still supporting Airbrake v4, accepting and applying bug fixes, and responding to issues.

However, the time has come to move on. On November 24, 2016, we will be stopping support for Airbrake v4, this version will no longer be maintained. Realistically, there's no reason to use Airbrake v4, unless you still use Rails 2 or Ruby 1.8. Airbrake v5 supports Rails 3.2+, Ruby 1.9.2+, JRuby and even Rubinius, so please upgrade and enjoy modern experience 👯

**Comment by kyrylo** [comment]
### **The support for airbrake-v4 ended today**

Thanks everybody for using Airbrake v4, I hope you upgraded to v5 by now.

**Comment by grosser** [comment]
should delete this wiki now ? https://github.com/airbrake/airbrake/wiki/Customizing-your-airbrake.rb

**Comment by kyrylo** [comment]
👍
