### ISSUE TITLE
One exception is send several times to Airbrake

### ISSUE THREAD

**Issue by edariedl** [airbrake/airbrake#597]
Hi,

we found possible bug in airbrake gem. In our rails application some exceptions are send up to 3 times to Airbrake.

It mostly happens with background jobs exception. We use `delayed_job` and `active_job`. If there is an error raised because of validation fails in the model same exception is send to Airbrake in following order:

1. `ActiveRecord` modul catches the exception, sends it to Airbrake and then reraises the exception
2. `ActiveJob` modul catches the same exception, sends it to Airbrake and then reraises the exception
3. `DelayedJob` modul catches the same expection, sends it to Airbrake again and then reraiseds the exception

Then it shows something like this in the airbrake:
![screen shot 2016-08-29 at 12 12 06](https://cloud.githubusercontent.com/assets/163762/18048358/e917859c-6de1-11e6-8eef-bffd19eeaefd.png)

Only thing where it differs are Params in the airbrake. One exception has no params. Second exception has`ActiveJob` params

```
{
  "arguments": [
    "TipGenerator.perform"
  ],
  "job": "TipGenerator.perform",
  "job_id": "cc1cf80e-ea1c-47e5-8e4a-928f0855b63b",
  "queue_name": "default",
  "serialized_arguments": null
}
```

and third error has `DelayedJob` params:

```
{
  "active_job": {
    "arguments": [
      "TipGenerator.perform"
    ],
    "job_class": "ScheduledJob",
    "job_id": "cc1cf80e-ea1c-47e5-8e4a-928f0855b63b",
    "queue_name": "default"
  },
  "job": {
    "attempts": 0,
    "created_at": "2016-08-22T23:45:00.000+02:00",
    "failed_at": null,
    "handler": "--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: ScheduledJob\n  job_id: cc1cf80e-ea1c-47e5-8e4a-928f0855b63b\n  queue_name: default\n  arguments:\n  - TipGenerator.perform\n",
    "id": 3544998,
    "last_error": null,
    "locked_at": "2016-08-22T23:45:00.468+02:00",
    "locked_by": "host:app1 pid:10645",
    "priority": 0,
    "queue": null,
    "run_at": "2016-08-22T23:45:00.000+02:00",
    "updated_at": "2016-08-22T23:45:00.000+02:00"
  }
}
```

**Comment by kyrylo** [comment]
Hey, thanks for sharing this information and sorry for the delay in response.
I am not sure if we should qualify this as a bug. But at the same time if we were to fix this, I can't imagine a straightforward way to do this. Is this too annoying to have?
What would you expect to see in the dashboard instead?

**Comment by edariedl** [comment]
It is at least inconvenient. Every time this happens we have to find out that these three reports are because of the same exception, which takes some time. 

And what is worse [Airbrake has rate limit](https://airbrake.io/pricing) for errors per minute in the plans. Thus if one exception is sent up to three times - effective limit is one third of the limit in your plan eg. for Essential plan where the limit is 25 errors per minute, our app fails "only" 8 times but because of behaviour described above there will be 24 errors sent to Airbrake. Thankfully this isn't problem for us but it could be for someone.

I would probably expect it to send only the last one from DelayedJob, which has all the informations from the levels above.

**Comment by kyrylo** [comment]
Thanks for the information. It would greatly simplify debugging if you could set up a test Rails app demonstrating this problem. I have tried to replicate this myself, but failed so far.

**Comment by kyrylo** [comment]
I am more than happy to find a fix to this problem, but I do need reproduction steps, since I couldn't make it fail thrice (not even twice). If anybody reading this can explain how to reproduce, please ping me and we'll solve the issue.

**Comment by edariedl** [comment]
I am sorry I am currently on vacations. I will be back home next week and I'll try to replicate the bug.

**Comment by kyrylo** [comment]
No worries, and thank you!
