### ISSUE TITLE
airbrake-ruby version 1.4

### ISSUE THREAD

**Issue by mrkgrandjean** [airbrake/airbrake#601]
I'm using this gem, to do notification from rails, and all of my notification emails are tagged with this banner. 
![screen shot 2016-09-13 at 2 28 32 pm](https://cloud.githubusercontent.com/assets/382310/18492105/798557a2-79be-11e6-9310-d1d428a6816b.png)
When I went to update, I realized that this gem is pegged to version 1.4 not 1.5.

**Comment by kyrylo** [comment]
Thanks for opening the issue. This was my oversight.

**Comment by kyrylo** [comment]
Solved by https://github.com/airbrake/airbrake/pull/602.
