### ISSUE TITLE
user_attributes removed v5?

### ISSUE THREAD

**Issue by DiegoSalazar** [airbrake/airbrake#604]
This was a valuable feature for us. Why was it removed?

**Comment by kyrylo** [comment]
We send user information by default now.

> This was a valuable feature for us.

Could you elaborate?

**Comment by DiegoSalazar** [comment]
> We send user information by default now.
Oh good to know!

It's helpful to know who was logged in when the error happened, we connect that information to other info we have of the user.

**Comment by kyrylo** [comment]
Fantastic :)

Feel free to open new issues if you think we miss some information about users.

**Comment by felixbuenemann** [comment]
@kyrylo It would be great if the v4 to v5 migration guide mentioned why it was removed.

**Comment by kyrylo** [comment]
By now, I expect everyone to be already upgraded to v5. If you are still on v4, I wholeheartedly recommend to upgrade. We don't support v4 anymore (for almost a year already: https://github.com/airbrake/airbrake/issues/596). I'd be happy to accept a PR, if you don't mind, though.

**Comment by felixbuenemann** [comment]
I could do a pr, if I knew what the new behavior is, which is still unclear to me.

Is airbrake now sending all attributes on the current_user model? What should I do to prevent that …

**Comment by kyrylo** [comment]
[Like I previously said](https://github.com/airbrake/airbrake/issues/604#issuecomment-248542946), user information is sent [by default](https://github.com/airbrake/airbrake/blob/44d39c6bb33ce171e0d7633feb3e72acfef0b6a5/lib/airbrake/rack/user.rb#L41-L44).

**Comment by felixbuenemann** [comment]
@kyrylo Thanks for pointing me at the right source code, I've prepared PR #805 to improve the docs.
