### ISSUE TITLE
New host configuration directive is actually a URI.

### ISSUE THREAD

**Issue by rantler** [airbrake/airbrake#607]
While I applaud the change, I think the choice of naming can lead to confusion (it certainly does in our own codebases). Example:
```Ruby
Airbrake.configure do |c|
  c.host = 'http://example.com:8080'
end
```
The directive should really be called `uri` since it is no longer merely a host.
```Ruby
Airbrake.configure do |c|
  c.uri = 'http://example.com:8080'
end
```

**Comment by kyrylo** [comment]
I appreciate your feedback. It indeed would be nice to be more accurate, but this is what we have. I'm a bit wary of renaming it, since it's a well-known name by now. The price we have to pay in order to rename it is probably too high for what we'd get in return.

Could you explain why your codebases clash with the `host` option?

**Comment by rantler** [comment]
I could have been more clear. What I mean to say is that our own code bases are littered with configuration directives that claim they are hosts, but are really URIs and of course the reverse is also quite prevalent. I causes untold amounts of pain when trying to reason about configurations in different environments and across projects. One of our major technical debt tasks is to address this and rationalize the configuration directives across the engineering organization. After having done so, the Airbrake host will be the only remaining configuration directive that does not conform to our accepted naming convention.

This is a pain point that is likely somewhat unique to our own code bases and (hopefully) isn't a major concern for most of your customers.

As they say, naming is hard.

**Comment by kyrylo** [comment]
I understand the issue, but at the same time, it feels to me like your naming convention shouldn't dictate library name choices. Please don't get me wrong, I'm fine with renaming it and I am grateful for this feedback, but what if another customer filed an issue where they would claim they prefer "endpoint" (or "url", or whatnot) in their company and the airbrake gem violates their policy? I wouldn't have an answer for them. Unfortunately, after thinking this through, I have to close the issue.
