### ISSUE TITLE
airbrake not playing well with our automated heroku PR deploys

### ISSUE THREAD

**Issue by tansaku** [airbrake/airbrake#620]
airbrake works for us on heroku, but we're struggling with automated PR deploys.

when we run rake db:setup we get a failed to connect to db error despite the fact that database actions are working fine from the log output.

We notice the following in the stack trace:

```
/app/vendor/bundle/ruby/2.3.0/gems/airbrake-5.6.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
```

full details in https://github.com/AgileVentures/WebsiteOne/issues/1348

Apologies if this is unrelated to airbrake - just can't find anything else to go on at the moment.  The log seems to show connecting to the DB fine, and then a DB connection error with a stack trace that doesn't refer to any or our own code ...

**Comment by kyrylo** [comment]
Hey, @tansaku!

To be sure it's not related to Airbrake, just remove the gem and try again. I took a look at https://github.com/AgileVentures/WebsiteOne/issues/1348 and I don't see how Airbrake is related to your issue.

`execute` is just our wrapper around Rake tasks, so we have a chance to capture possible exceptions there, however it seems to be red herring for you.
