### ISSUE TITLE
airbrake-ruby 1.6.0 gem install failure

### ISSUE THREAD

**Issue by cwa821** [airbrake/airbrake#622]
I'm trying to install version 1.6.0 and I get the following failure.

An error occurred while installing airbrake-ruby (1.6.0), and Bundler cannot
continue.
Make sure that `gem install airbrake-ruby -v '1.6.0'` succeeds before bundling.

C:\Users\Wes\Documents\TVM\tvm>gem install airbrake-ruby -v '1.6.0'
ERROR:  Could not find a valid gem 'airbrake-ruby' (= 1.6.0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

How do I fix this?
Thanks,
Wes

**Comment by kyrylo** [comment]
This error has nothing to do with our project.

But the fix should be easy: https://gist.github.com/luislavena/f064211759ee0f806c88
