### ISSUE TITLE
Rack: send payload of XML requests on POST

### ISSUE THREAD

**Issue by kyrylo** [airbrake/airbrake#623]
Currently, our Rack integration is capable of transmitting JSON request body. The body is being displayed in the Params panel.

The problem is that if Content-Type is XML, then this is not the case anymore. Request body is not attached anymore.

Originally reported here: https://github.com/airbrake/airbrake/issues/182#issuecomment-255278749

Reproducible with:

```
require 'rest-client'
xml = '<xml><foo>bar</foo><bar>foo</bar></xml>'
RestClient.post('http://localhost:3000/welcomes', xml, content_type: :xml)
```

Expected to see `xml` in the dashboard.
Saw nothing instead.

**Comment by kyrylo** [comment]
@halida I just released v5.6.1, which includes request body. Enjoy!

**Comment by halida** [comment]
@kyrylo Thanks, it works fine with errbit.

**Comment by halida** [comment]
@kyrylo Hi, I found it only read first 512 byte for request body, I understand it is used for performance concern, but sometimes we need fetch all the request body for debugging use.
Could you provide an config for it? Thanks.
I remove it from my application :-P

**Comment by halida** [comment]
@kyrylo the body is truncated, and I saw there is an PAYLOAD_MAX_SIZE and MAX_NOTICE_SIZE, can I config it?

**Comment by kyrylo** [comment]
I suggest to file a new issue to discuss this. Our API imposes certain limitations and most likely full body support is not possible.
