### ISSUE TITLE
Can not install on heroku

### ISSUE THREAD

**Issue by hanguyenst** [airbrake/airbrake#635]
Hello,

I'm integrating Airbrake on Heroku. On my Heroku, I installed this plugin and I have PROJECT_ID and PROJECT_KEY. I add gem to my project and install it. After I push code to Heroku by git then heroku alert error:
Bundler::GemRequireError: There was an error while trying to load the gem 'airbrake'.
Gem Load Error is: undefined method `runner' for #<Airbrake::Rails::Railtie:0x000000033b4068>
I'm using newest Airbrake version. Can you help me?

**Comment by kyrylo** [comment]
My hunch is that you are using an unsupported version of Rails, or load Rails in a peculiar way (which I'm unaware of). Could you tell me more about your environment?

**Comment by hanguyenst** [comment]
My enviroment:
- ruby 1.9.3
- gem 2.4.8
- rails 3.2.13
I can install Airbrake version 4.x but I can not generate config file airbrake.rb.

**Comment by kyrylo** [comment]
Would it be possible for you to upgrade at least to Rails `3.2.22` or higher? I'm not sure it'll help, but it shouldn't be hard to try.

> I can install Airbrake version 4.x but I can not generate config file airbrake.rb.

It's possible to generate the config with some shenanigans (I don't remember exactly), but I highly recommend against using it. [It's unsupported anymore](https://github.com/airbrake/airbrake/issues/596).

**Comment by hanguyenst** [comment]
I'm newbie in rails. Now my system can not upgrade to new ruby version (it makes some other gem can not run right), I have to use ruby 1.9.3, so do you think i can upgrade to rails 4.2 that don't affect to ruby version?

**Comment by kyrylo** [comment]
Rails 4.2 should support both your current Ruby and Rails. However it is probably easier to update `3.2.x` without touching your Ruby at all.

**Comment by hanguyenst** [comment]
ah, I see. I'll try upgrade to 3.2.x ^^. Thank you so much!

**Comment by kyrylo** [comment]
Ping me in case you have any other questions 👍
