### ISSUE TITLE
do not send ENV when rake tasks fail

### ISSUE THREAD

**Issue by grosser** [airbrake/airbrake#647]
ENV includes lots of secrets / tokens ... so ideally do not send this by default ... 
Just fixed that for our apps that run v4, but the tests for rake tasks say it should still be happening on master.

Prefer to make this op-in ... it's not as safe as for example the request env ... or use a whitelist

**Comment by kyrylo** [comment]
Are you referring to [this test](https://github.com/airbrake/airbrake/blob/05e66f4941d4cedcb690124703b63ec0b498c293/spec/unit/rake/tasks_spec.rb#L21-L29)? It tests [these](https://github.com/airbrake/airbrake/blob/b752b778ff82177569944dc5d4559352a6c30d55/lib/airbrake/rake/tasks.rb#L78-L82) environment variables. We don't read the rest of values, so it should already be op-in.

**Comment by grosser** [comment]
Thats great, was unable to find what it actually sends, just need to upgrade then :)

**Comment by grosser** [comment]
FYI script to delete all airbrake rake errors:

```Ruby
require 'json'

def sh(command)
  puts command
  result = `#{command}`
  raise "FAIL #{command}\n#{result}" unless $?.success? == true
  result
end

user_key = ""
project_id = ""
group_api = "https://airbrake.io/api/v4/projects/#{project_id}/groups"
groups = sh("curl -sfS '#{group_api}?component=rake&key=#{user_key}'")
groups = JSON.parse(groups)
puts "FOUND #{groups.fetch("count")} groups"

groups.fetch("groups").each do |group|
  id = group.fetch("id")
  puts "Deleting #{id}"
  sh "curl -sfS -X DELETE '#{group_api}/#{id}?key=#{user_key}'"
end
```

**Comment by grosser** [comment]
... so we found a few projects that are stuck on 4.x ... would you accept a PR to the 4.x branch ?

**Comment by grosser** [comment]
My PR would be this https://github.com/airbrake/airbrake/compare/v4.3.8...grosser:grosser/fix-env?expand=1 ... but cannot open it since there is no airbrake-v4 branch ...

**Comment by grosser** [comment]
monkey patch would be:

```Ruby
# Do not leak ENV vars https://github.com/airbrake/airbrake/issues/647
require 'airbrake/rake_handler'
Airbrake::RakeHandler.send(:define_method, :environment_info) { {} }
```

**Comment by kyrylo** [comment]
I deleted the `airbrake-v4` branch because its support has ended. If the monkey-patch works for you, then I see no harm in continue using it. If not, then we can probably resurrect the branch.

However, I still highly recommend to upgrade :)

**Comment by grosser** [comment]
maybe even simpler by @catkins

```
# do not send our environment (secrets etc) to airbrake
# https://github.com/airbrake/airbrake/issues/647
config.rake_environment_filters.concat ENV.keys
```
