### ISSUE TITLE
v5 configuration of: v4 config.ignore ?

### ISSUE THREAD

**Issue by a-leung** [airbrake/airbrake#678]
Hi,

I want to confirm the v5 configuration of v4 options:

Rails' filter_parameters:

```ruby
# V4
Rails.configuration.filter_parameters.each do |p|
  config.params_filters << p.to_s
end

# V5
 config.blacklist_keys << Rails.application.config.filter_parameters
```

config.ignore:

```ruby
# V4
config.ignore << "ActionController::RoutingError"

# V5
Airbrake.add_filter << "ActionController::RoutingError"
```

Are these the correct v5 configuration method for v4 options?

**Comment by kyrylo** [comment]
Hey!

> Rails' filter_parameters:

That seems to be correct.

> config.ignore:

This is not entirely correct. This is what you do now:

```rb
Airbrake.add_filter do |notice|
  if notice[:errors].first[:type] == 'ActionController::RoutingError'
    notice.ignore!
  end
end
```

**Comment by a-leung** [comment]
for filter parameters, the [documentation](https://github.com/airbrake/airbrake/blob/master/README.md#integration-with-filter_parameters), show this is the way to use Rails' `filter_parameters`:

```ruby
 c.blacklist_keys = Rails.application.config.filter_parameters
```

but in the v4 => v5 migration [guide](https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#blacklist-filter)

```ruby
config.blacklist_keys << Rails.application.config.filter_parameters
```

so, which way is  the way to configure `blacklist_keys` with Rails' `filter_parameters`? Would both work?

**Comment by kyrylo** [comment]
Either way should work. `c.blacklist_keys` is always an Array, so you are either overwriting it or appending to it.

**Comment by a-leung** [comment]
hmm... `Rails.application.config.filter_parameters` is also an array. So `[a, b, c] << [d, e, f]` returns: `[a, b, c, [d, e, f]]`. Not: `[a, b, c, d, e, f]`.

I tested this out quickly on the rails console. When `blacklist_keys` are configured by appending `Rails.application.config.filter_parameters`, when sending out an Airbrake notification:

```ruby
Rails.config.filter_parameters += :payment_token

Airbrake.configuration.blacklist_keys << Rails.application.config.filter_parameters

Airbrake.notify('test blacklist <<', { payment_token: 'clear text token' })

# => E, [2017-03-01T20:08:45.846855 #1] ERROR -- : **Airbrake: one of the patterns in Airbrake::Filters::KeysBlacklist is invalid. Known patterns: [[:payment_token]]
#=> #<Airbrake::Promise:0x0055c97aaa6038 @on_resolved=[], @on_rejected=[], @value={}, @mutex=#<Mutex:0x0055c97aaa5f98>>
```

The notification is sent, despite the `ERROR`, and the parameters section of the notification on the website lists:

```json
{
  "payment_token": "clear text token"
}
```

Whereas setting `blacklist_keys` equal to `filter_parameters` array:

```ruby
Rails.config.filter_parameters += :payment_token

Airbrake.configuration.blacklist_keys = Rails.application.config.filter_parameters

Airbrake.notify('test blacklist =', { payment_token: 'clear text token' })

=> #<Airbrake::Promise:0x00556f273a51d8 @on_resolved=[], @on_rejected=[], @value={}, @mutex=#<Mutex:0x00556f273a5138>>
```

There is no error and the parameter section of the notification is:

```json
{
  "payment_token": "[Filtered]"
}
```

So, I suspect that each way of configuring `blacklist_keys` are not equivalent.

**Comment by kyrylo** [comment]
You are actually correct. I fixed the migration guide, big thanks for pointing out the discrepancy! 

So this should work:

```
c.blacklist_keys = Rails.application.config.filter_parameters
c.blacklist_keys << 'key'
```

It all boils down to Ruby and you are free to use any method to achieve what you want: a flat array with keys.

P.S. I can see you use `Airbrake.configuration`. We actually don't have that method in v5. Could you elaborate how it appeared and why you need it?

**Comment by a-leung** [comment]
re: `Airbrake.configuration` - I just wrote out and got it mixed up with `Rails.application.configuration`. :sweat_smile: 

Thanks for updating the docs!
