### ISSUE TITLE
Add custom params using Rake middleware

### ISSUE THREAD

**Issue by nicolas-besnard** [airbrake/airbrake#711]
I'd like to add some custom parameters when an error occurs. I think it was possible on some previous version, but can't find any documentation about it.

`Admin` can log as an `User`, and airbrake is sending the `Admin` information instead of the logged as `User`. Would love to be able to send them both as those information are in an other session

**Comment by kyrylo** [comment]
Hi, Nicolas. Will using the Notice stash work for you?

https://github.com/airbrake/airbrake#appending-information-from-rack-requests

**Comment by kyrylo** [comment]
Let me know if you this doesn't work and we'll work something out.
