### ISSUE TITLE
do not load airbrake initializer when environment is already loaded and require it

### ISSUE THREAD

**Issue by grosser** [airbrake/airbrake#714]
- do not load when it was already loaded via then environment -> check if environment task was already invoked
 - use `require File.expand_path(file)` instead of load load prevent duplicate loading (in case environment is loaded later)

https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rake/tasks.rb#L71

**Comment by kyrylo** [comment]
I'm afraid I'm a bit confused about this issue.
Could you provide more details? 

1. What doesn't work properly?
2. Why is https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rake/tasks.rb#L71 executed twice?

**Comment by grosser** [comment]
I'm doing `rake db:migrate airbrake:deploy` so the environment is already loaded when airbrake is executed, which then loads the initializer a second time ... then my notifiers got added twice and weird things happened :D

**Comment by kyrylo** [comment]
Oh, thanks, this is more clear now. I hadn't known it was possible to invoke multiple rake commands at the same time.
