### ISSUE TITLE
[BUG] HttpParamsFilter overrides custom params.

### ISSUE THREAD

**Issue by dragosmiron** [airbrake/airbrake#715]
When putting extra params in an exception using `to_airbrake` or when using the `add_filter` like so:
```ruby
Airbrake.add_filter do |notice|
  notice[:params][:xxxx] = "1234"
end
```
They get overriden if the Airbrake notice contains the rack request in filtering (controller errors, etc) here: https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/notifier.rb#L124
Because the custom filter can be applied before `HttpParamsFilter`

Therefore this line here: https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/http_params_filter.rb#L13
```ruby
notice[:params] = request.params
```
needs to be:
```ruby
notice[:params].merge! request.params
```

**Comment by kyrylo** [comment]
Good catch. Are interested in submitting a PR?

**Comment by dragosmiron** [comment]
i'll see if i have some time tomorrow
