### ISSUE TITLE
Capistrano Deployment Notification stopped working in v6.1.0 Update

### ISSUE THREAD

**Issue by nick-desteffen** [airbrake/airbrake#745]
We recently updated to v6.1.0 and deployment notifications for Capistrano v3 have stopped working.  Rolling back just the `airbrake` gem to v6.0.0 resolves the issue.

**Comment by kyrylo** [comment]
What was your airbrake-ruby version when it wasn't working?

I didn't make any changes to the Capustrano integration, so my hunch is that you were hitting https://github.com/airbrake/airbrake/issues/743. The fix for that was already released so please make sure you run airbrake-ruby v2.2.4.

**Comment by nick-desteffen** [comment]
When it wasn't working we were running v2.2.3 of airbrake-ruby.  I'm going to confirm deployment notifications work with  v2.2.4 of airbrake-ruby + v6.1.0 of airbrake.

**Comment by nick-desteffen** [comment]
Ok we are running v2.2.4 of airbrake-ruby + v6.1.0 of airbrake and deployment notifications are still not working, so it is an issue with v6.1.0 of airbrake.

**Comment by kyrylo** [comment]
Thanks for checking. That's weird. I'll check next week.

**Comment by kyrylo** [comment]
I just released v6.1.1, which fixes this issue.

**Comment by nick-desteffen** [comment]
Awesome, thanks!
