### ISSUE TITLE
RuntimeError:  can't modify frozen SystemStackError

### ISSUE THREAD

**Issue by urkle** [airbrake/airbrake#752]
After upgrading to Airbrake 6.1.0/airbrake-ruby 2.2.3 (from 5.6.1/1.6.0) we started receiving this error all over our application.    We upgraded airbrake once more to 6.1.1/2.2.5 (which pulled in fix https://github.com/airbrake/airbrake-ruby/pull/224 ) seemed to fix most of the errors.  We are right now only left with two occurrences that keep recurring both within our grape-based API.

One thing that is odd, is that the stack error occurs randomly..  Sometimes things work correctly, and other times it fails. (right now it seems every other request creates the system stack error).

In our grape API we are simply rescuing exception using the rescue_from like so.

```ruby
      rescue_from Hubstaff::Errors::SecurityError do |e|
        APIUtils.notify_airbrake(e, env)
        error_response(message: e.message, status: 401)
      end
 
      # APIUtils.notify_airbrake
      def self.notify_airbrake(exception, env)
        user_details = {}
        # code that populates user_details based on the ENV and database
        Airbrake.notify exception, {
           user: user_details,
           rack_env: env,
        }
      end
```

If we comment OUT the Airbrake.notify call, then things work fine (except we don't get the airbrakes, obviously).   but with the airbrake notify call we are get (about every other request with me testing on a staging environment)  frozen stack error.

```
2017-06-03T20:02:19.483103+00:00 app[web.1]: App 141 stdout: RuntimeError (can't modify frozen SystemStackError):
2017-06-03T20:02:19.483104+00:00 app[web.1]: App 141 stdout:   app/public/api_v1.rb:127:in `notify_airbrake'
2017-06-03T20:02:19.483105+00:00 app[web.1]: App 141 stdout:   app/public/api_v1.rb:167:in `block in <class:API_v1>'
```

The exception that makes it up to airbrake contains a loop of
```
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in map
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in as_json
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:128 in as_json
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in block in as_json
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in map
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in as_json
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:128 in as_json
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in block in as_json
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in map
/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:140 in as_json
```

**Comment by urkle** [comment]
so, I found that if I remove the sending of the rack_env, then I no longer receive the stack errors.  However, I also have NO contextual information provided in the errors ( no params, no server headers, nothing!!)..   So how in the world do I get that back with a Airbrake error produced through my grape API?

**Comment by kyrylo** [comment]
What's your Ruby version?

**Comment by urkle** [comment]
Currently 2.2.5..  but I did upgrade to 2.2.6 in running down the avenue of upgrading grape.

The main thing I want to know now, is how do I cleanly add the ENV in safely when I report airbrakes that are outside of the action controller (in a rack app like grape)

**Comment by kyrylo** [comment]
Could you try blacklisting `puma.config`? It cannot be converted to JSON because this a super complex object and I suspect it to be the culprit.

**Comment by urkle** [comment]
@kyrylo we aren't using puma.  So that's unfortunately not the issue.  now.. here is a list of the keys we do have in our ENV.

```json
[
  "REQUEST_URI",
  "PATH_INFO",
  "SCRIPT_NAME",
  "QUERY_STRING",
  "REQUEST_METHOD",
  "SERVER_NAME",
  "SERVER_PORT",
  "SERVER_SOFTWARE",
  "SERVER_PROTOCOL",
  "REMOTE_ADDR",
  "REMOTE_PORT",
  "CONTENT_TYPE",
  "CONTENT_LENGTH",
  "PASSENGER_CONNECT_PASSWORD",
  "HTTP_USER_AGENT",
  "HTTP_TOTAL_ROUTE_TIME",
  "HTTP_ACCEPT_ENCODING",
  "HTTP_CONNECT_TIME",
  "HTTP_X_FORWARDED_PROTO",
  "HTTP_X_REQUEST_ID",
  "HTTP_ACCEPT",
  "HTTP_ACCEPT_LANGUAGE",
  "HTTP_ORIGIN",
  "HTTP_COOKIE",
  "HTTP_X_FORWARDED_PORT",
  "HTTP_HOST",
  "HTTP_X_REQUEST_START",
  "HTTP_VIA",
  "HTTP_X_FORWARDED_FOR",
  "rack.version",
  "rack.input",
  "rack.errors",
  "rack.multithread",
  "rack.multiprocess",
  "rack.run_once",
  "rack.url_scheme",
  "rack.hijack?",
  "rack.hijack",
  "HTTP_VERSION",
  "newrelic.transaction_started",
  "ORIGINAL_FULLPATH",
  "ORIGINAL_SCRIPT_NAME",
  "action_dispatch.routes",
  "action_dispatch.parameter_filter",
  "action_dispatch.redirect_filter",
  "action_dispatch.secret_token",
  "action_dispatch.secret_key_base",
  "action_dispatch.show_exceptions",
  "action_dispatch.show_detailed_exceptions",
  "action_dispatch.logger",
  "action_dispatch.backtrace_cleaner",
  "action_dispatch.key_generator",
  "action_dispatch.http_auth_salt",
  "action_dispatch.signed_cookie_salt",
  "action_dispatch.encrypted_cookie_salt",
  "action_dispatch.encrypted_signed_cookie_salt",
  "action_dispatch.cookies_serializer",
  "action_dispatch.cookies_digest",
  "ROUTES_70159535530680_SCRIPT_NAME",
  "rack.cors",
  "rack-cache.cache_key",
  "rack-cache.verbose",
  "rack-cache.storage",
  "rack-cache.metastore",
  "rack-cache.entitystore",
  "rack-cache.default_ttl",
  "rack-cache.ignore_headers",
  "rack-cache.private_headers",
  "rack-cache.allow_reload",
  "rack-cache.allow_revalidate",
  "rack-cache.use_native_ttl",
  "rack.request.form_hash",
  "rack.request.form_input",
  "action_dispatch.request_id",
  "action_dispatch.remote_ip",
  "rack.session",
  "rack.session.options",
  "action_dispatch.request.content_type",
  "action_dispatch.request.path_parameters",
  "grape.routing_args",
  "api.endpoint",
  "grape.request",
  "grape.request.headers",
  "rack.request.query_string",
  "rack.request.query_hash",
  "grape.request.params",
  "api.version",
  "api.format",
  "rack.request.cookie_hash",
  "rack.request.cookie_string"
]
```

**Comment by urkle** [comment]
so, after digging in through EACH of those I found that there were several that threw .to_json for issues, include the IO class, the Grape::Request (which is a Rack::Request child)..

After digging through the Airbrake 6.1.1 gem code, I reworked my code to do this instead

```ruby
        params = { user: user_details }
        notice = Airbrake[:default].build_notice(exception, params)
        notice.stash[:rack_request] = env['grape.request']
        Airbrake[:default].notify(notice, params)
```
And that has restored my contextual information that I needed.

**Comment by kyrylo** [comment]
This is not an issue with the Airbrake gem, but with [ActiveSupport](https://github.com/rails/rails/issues/26132). I'm glad that you've found a workaround. I'm going to close this issue because I don't see an easy workaround here. In theory, we could monkey-patch `IO#to_json` to make it safe, but I don't think the airbrake gem should include such code.

P.S. You don't need to invoke `Airbrake[:default]`. `Airbrake.build_notice` already does that, thus:


```rb
notice = Airbrake.build_notice(exception, user: user_details)
notice.stash[:rack_request] = env['grape.request']
Airbrake.notify(notice)
```
