### ISSUE TITLE
Using server IP address not as useful in real world debugging

### ISSUE THREAD

**Issue by urkle** [airbrake/airbrake#759]
(from bug #266 )
> Remote address in the summary tab shows IP address of the server that sent the error. This is useful when you have different versions of the code deployed on different servers. So this is a feature, not a bug.

This is actually not very useful, as I have other identifiers to know which server the error came from.. Most of the time when I'm needing to look are remote IP & remote country I am wanting to know what client address caused the issue..  that is I want the ability to see if a bunch of requests causing errors are coming in from a single country or IP address..

Right now I have GLOBALLY pinned env.headers.HTTP_X_FORWARDED_FOR, however that uses up one of the FEW global pins I have. and it doesn't give me the country information readily either.

IMHO these two fields are very badly named and they should be labeled "Server addresses" and "Server countries" as that will greatly reduce confusion.

**Comment by kyrylo** [comment]
We added support for that in https://github.com/airbrake/airbrake/pull/756. It hasn't been released yet, but I'm going to cut a new release today.

We support REMOTE ADDRESS (server) and USER ADDRESS (user IP). With the new release of this library we'll support USER ADDRESS. As for the naming, we'll consider changing it. I can see how it can be hard to understand.

**Comment by kyrylo** [comment]
Released new version (v6.1.2). Make sure to `bundle update airbrake`.

**Comment by urkle** [comment]
@kyrylo thanks so much for the quick response..  This will be much appreciated by my team.
