### ISSUE TITLE
`rake airbrake:deploy` doesn't seem to work in a non-Rails project

### ISSUE THREAD

**Issue by nickgrim** [airbrake/airbrake#762]
* Airbrake version: 6.1.2 / 2.2.7
* Ruby version: 2.4.1p111
* Framework name & version: None

#### Airbrake config

N/A, but see below. I haven't actually set it up in this test, but it fails before it gets to that point.

#### Description

I'm trying to follow the docs for notifying Airbrake of a deployment, specifically the [using-the-rake-task "Anywhere" part](https://github.com/airbrake/airbrake#user-content-rake-task).

I've got the following very minimal test case:
```
$ ls -l
total 12
-rw-r--r-- 1 nick nick  46 Jun 28 14:48 Gemfile
-rw-r--r-- 1 nick nick 198 Jun 28 14:48 Gemfile.lock
-rw-r--r-- 1 nick nick  54 Jun 28 14:46 Rakefile
```

The `Gemfile` only contains `airbrake`:
```
$ cat Gemfile
source "https://rubygems.org"

gem "airbrake"
```

`Rakefile` includes the Rake integration, as indicated in the docs:
```
$ cat Rakefile
require 'bundler/setup'
require 'airbrake/rake/tasks'
```

Everything's installed:
```
$ bundle check
The Gemfile's dependencies are satisfied
```

The tasks are there:
```
$ rake -T
rake airbrake:deploy                      # Notify Airbrake of a new deploy
rake airbrake:install_heroku_deploy_hook  # Install a Heroku deploy hook to notify Airbrake of deploys
rake airbrake:test                        # Verify your gem installation by sending a test exception
```
...but calling the task fails due to a missing `Airbrake` constant:
```
$ rake airbrake:deploy
rake aborted!
NameError: uninitialized constant Airbrake
/usr/local/rvm/gems/ruby-2.4.1@airbroken/gems/airbrake-6.1.2/lib/airbrake/rake/tasks.rb:84:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => airbrake:deploy
(See full trace by running task with --trace)
```

Now, the `airbrake:test` task also fails:
```
$ rake airbrake:test
rake aborted!
Don't know how to build task 'environment' (see --tasks)
/usr/local/rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => airbrake:test
(See full trace by running task with --trace)
```
...because of a dependency on a task called `environment`, which doesn't exist. So far, so fair.

However, even if such a task existed, and did what you might expect (load constants, set up configuration), I still don't think that the deploy task would work, because [that task looks like this (at the time of writing)](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rake/tasks.rb#L63-L89):

```
...
63   desc 'Notify Airbrake of a new deploy'
64   task :deploy do
65     if defined?(Rails)
66       initializer = Rails.root.join('config', 'initializers', 'airbrake.rb')
67
68       # Avoid loading the environment to speed up the deploy task and try guess
69       # the initializer file location.
70       if initializer.exist? && Airbrake[:default].is_a?(Airbrake::NilNotifier)
71         load(initializer)
72       else
73         Rake::Task[:environment].invoke
74       end
75     end
76
77     deploy_params = {
78       environment: ENV['ENVIRONMENT'],
79       username: ENV['USERNAME'],
80       revision: ENV['REVISION'],
81       repository: ENV['REPOSITORY'],
82       version: ENV['VERSION']
83     }
84     promise = Airbrake.create_deploy(deploy_params)
85     promise.then do
86       puts "The #{deploy_params[:environment]} environment was deployed."
87     end
88     promise.rescue { |error| abort(error) }
89   end
 ...
```

Note that this task only runs the `environment` task *if* `Rails` is defined (and some other conditions).

I'm not sure what the correct solution is, but it feels like something along the lines of "load the environment task if `!defined?(Airbrake)`" ?

**Comment by kyrylo** [comment]
Thanks for the detailed report. This sounds like a bug to me.

**Comment by kyrylo** [comment]
@nickgrim could you please give this PR a spin? https://github.com/airbrake/airbrake/pull/763
