### ISSUE TITLE
blank errors not reported

### ISSUE THREAD

**Issue by ericcj** [airbrake/airbrake#768]
with airbrake gem 6.2.0 (airbrake-ruby 2.3.0) even with airbrake logger.level debug if I just "raise" from my rails 4.1 controller endpoint all I see in the output from script/server is:

E, [2017-07-13T20:20:05.711281 #42715] ERROR -- : **Airbrake:

whereas 'raise "test"' or 'raise RuntimeError.new' work fine.  looks like it's from the line:

        when 400, 401, 403, 429
          parsed_body = JSON.parse(body)
          logger.error("#{LOG_LABEL} #{parsed_body['error']}")

response is actually:

{"code":400,"type":"Bad Request","message":"no errors found"}). Body: {"code":400,"type":"Bad Request","message":"no errors found"}

so that log line isn't helpful since it's looking for error but the response has message.  but the root cause seems like a server-side bug since the request body sent to airbrake starts with: 

{"errors":[{"type":"RuntimeError","message":"","backtrace":[{"file":"[PROJECT_ROOT]/app/controllers/application_controller.rb","line":29,"function":"prestart"},{"file":"[GEM_ROOT]/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb","line":4,"function":"send_action"},...

**Comment by kyrylo** [comment]
Thanks for reporting. You are right, we should execute `parsed_body['message']` instead.

**Comment by ericcj** [comment]
Was the bug in the api that returns 400 instead of reporting the errors
fixed?

**Comment by kyrylo** [comment]
I don't think so. Could you send me full payload of your notice? Feel free to send a list to a gist either to kyrylo@airbrake.io or via support.
