### ISSUE TITLE
airbrake 6.2 causes "can't modify frozen IOError" at shutdown in passenger

### ISSUE THREAD

**Issue by ericcj** [airbrake/airbrake#770]
when we used airbrake 4 passenger has always thrown IOErrors at shutdown but since upgrading to 6.2 passenger blows up trying to print its exception on "can't modify frozen IOError", not obvious what's being modified or which is responsible for the root cause:  https://github.com/phusion/passenger/issues/1961

[ 2017-07-14 00:49:51.6654 64/7f10155b7700 age/Cor/CoreMain.cpp:588 ]: Signal received. Gracefully shutting down... (send signal 1 more time(s) to force shutdown)
App 153 stderr: [ 2017-07-14 00:49:51.6668 210/0x000000022865c0(HTTP helper worker) utils.rb:87 ]: *** Exception IOError (stream closed) (process 210, thread 0x000000022865c0(HTTP
helper worker)):
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept_and_process_next_request'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:431:in `block (2 levels) in start_threads'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
...
App 153 stderr: [ 2017-07-14 00:49:51.6733 245/0x00000002286bd8(Worker 1) utils.rb:87 ]: *** Exception IOError (stream closed) (process 245, thread 0x00000002286bd8(Worker 1)):
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept_and_process_next_request'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
App 153 stderr: D, [2017-07-14T00:49:51.674906 #252] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.676001 #266] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.677018 #217] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.680053 #210] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.680953 #273] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.682778 #280] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.683871 #259] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.684841 #245] DEBUG -- : **Airbrake: closed
App 153 stderr: [ 2017-07-14 00:49:51.6854 224/0x000000022855d0(HTTP helper worker) utils.rb:87 ]: *** Exception IOError (stream closed) (process 224, thread 0x000000022855d0(HTTP
helper worker)):
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept_and_process_next_request'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:431:in `block (2 levels) in start_threads'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
App 153 stderr: [ 2017-07-14 00:49:51.6738 224/0x000000022868e0(Worker 1) utils.rb:87 ]: *** Exception IOError (stream closed) (process 224, thread 0x000000022868e0(Worker 1)):
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:136:in `accept_and_process_next_request'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
App 153 stderr: D, [2017-07-14T00:49:51.685948 #231] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.686291 #238] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:51.722655 #224] DEBUG -- : **Airbrake: closed
App 153 stderr: D, [2017-07-14T00:49:52.138364 #287] DEBUG -- : **Airbrake: {"id"=>"0005543c-6d4c-b003-dbae-c8511de6fa41", "url"=>"https://airbrake.io/locate/0005543c-6d4c-b003-dbae-c8511de6fa41"}
App 153 stderr: D, [2017-07-14T00:49:52.138557 #287] DEBUG -- : **Airbrake: closed
App 153 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/ruby_core_enhancements.rb:52:in `backtrace_string'
App 153 stderr: : can't modify frozen IOError (RuntimeError)
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:85:in `print_exception'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:117:in `rescue in block in create_thread_and_abort_on_exception'
App 153 stderr:         from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:112:in `block in create_thread_and_abort_on_exception'
[ 2017-07-14 00:49:52.3153 64/7f101c5c67c0 age/Cor/CoreMain.cpp:1065 ]: Passenger core shutdown finished

**Comment by kyrylo** [comment]
1. What's your Airbrake config?
2. What are your exact airbrake & airbrake-ruby versions?
3. What's your exact Passenger version?
4. What would be the easiest way for me to reproduce this issue?

**Comment by kyrylo** [comment]
Let me know if this is still an issue. Closing for now.
