### ISSUE TITLE
Too small string truncation size

### ISSUE THREAD

**Issue by vledniov** [airbrake/airbrake#774]
Hey there !

Recently I've updated airbrake gem in my Rails app, from 4.x to 5.8.1, and a part of sensitive data I need for debugging is getting truncated (when an error is raised).

**Rails version**: 4.2.0
**Airbrake version**: 5.8.1
This is my Airbrake configuration:

```ruby
Airbrake.configure do |config|
  config.project_key         = ****
  config.project_id          = ****
  config.host                = "host:port"
  config.ignore_environments = %w(development test)
  config.environment         = Rails.env
  config.blacklist_keys      = Rails.application.config.filter_parameters
end

Rails.application.config.filter_parameters => %i(password current_password password_confirmation
      client_secret secret_token secret authenticity_token photo)
```

Having this said, I have a route in the controller which handles BIG payloads (which MAY reach around 1-2 MB), and when I have an error raised on that side, I get the following from Airbrake:

```
Error message -> Validation failed: [Truncated]

{
  "params" => {
    "data"=> {
      "accounts" => [{"name"=>"Yo3", "updated_at"=>"2017-07-05T01:24:31[Truncated]", "guid"=>""E43470D3-5A6E-4850-[Truncated]", ...}]
  },
  "meta"=> {
      "timestamp1" => "2017-07-04T13:31:22[Truncated]",
      "timestamp2" => "2017-07-04T13:31:22[Truncated]",
      "timestamp3" => "2017-07-04T13:31:22[Truncated]",
      ...
  }
}
```

Now I don't know what was the validation error (the message is truncated), and it is very hard to debug the error when all the data you need is getting truncated :(

**Comment by kyrylo** [comment]
Howdy @vledniov, 

Our API does not permit errors bigger than 64KB, and our notifier [truncates](https://github.com/airbrake/airbrake-ruby#exception-limit) such notices.

I can suggest to strip out unwanted data via filters (globally).

```rb
Airbrake.add_filter do |notice|
  notice[:params][:meta] = nil
end
```

If you throw your exception manually, you can strip out unwanted data only for that particular error:

```rb
Airbrake.notify('oops') do |notice|
  notice[:params][:meta] = nil
end
```

**Comment by vledniov** [comment]
@kyrylo thanks for the response !

does the `notify_airbrake` helper have the same interface as `Airbrake.notify` ?

I mean, can I just go with `notify_airbrake(error) do |notice| ...` ?

**Comment by kyrylo** [comment]
Due to some technical difficulties the `notify_airbrake` helper does not support blocks (but the rest should be compatible with `Airbrake.notify). However, you can do the following:

```rb
notice = build_notice('oops')
notice[:params][:meta] = nil
notify_airbrake(notice)
```

**Comment by vledniov** [comment]
okay, will work this out, thanks !

**Comment by kyrylo** [comment]
Happy Airbraking 👍
Let me know if you have any other questions.

**Comment by kyrylo** [comment]
The size of the exception is determined by the size of the [JSON payload](https://github.com/airbrake/airbrake-ruby/blob/15501ae14c5f45e7f683ffe3d6c79f501e5c8b58/lib/airbrake-ruby/notice.rb#L85) we send to Airbrake. We count [how many bytes](https://github.com/airbrake/airbrake-ruby/blob/15501ae14c5f45e7f683ffe3d6c79f501e5c8b58/lib/airbrake-ruby/notice.rb#L89) that payload has. 

The exceptions that you raise programmatically usually don't contain a lot of data (unless you attach something to params or via filters). Airbrake integrations attach a lot of information by default to provide as much context as possible. Therefore, truncation can occur if there's simply too much.

**Comment by laasem** [comment]
@kyrylo Awesome, thanks so much for the super fast reply!
