### ISSUE TITLE
Airbrake: unexpected code (420)

### ISSUE THREAD

**Issue by shamil** [airbrake/airbrake#775]
Hi,

We lately started to get the following errors:

`ERROR -- : **Airbrake: unexpected code (420). Body: {"code":420,"type":"","message":"Project is rate limited"}`

We had several time over-limits, but this never affected our app, and no such errors on the app side.
Is this normal? Isn't this library should know how to handle `420` errors and not throw errors to the console?

Using rails `4.2.9`, ruby `2.4.1`, airbrake `6.2.0`

**Comment by kyrylo** [comment]
Hi @shamil. It should, but unfortunately it doesn't handle `420` as of now. The fix is easy, though.
