### ISSUE TITLE
Airbrake 5.8.1: Is there a way to send error to another project ?

### ISSUE THREAD

**Issue by vledniov** [airbrake/airbrake#776]
Hey guys !

I am having a web backend server which opens an API to an Android and one iOS app. I would like to send errors incoming from different sources to different Errbit rooms, depending whether it is an error on web backend side, Android side or iOS side.

on Airbrake 4.2.1 I used to do the following:

```ruby
Airbrake.notify(error, {api_key: extract_api_key})
```
And depending on which devise the request came from - I created an error on different Errbit rooms.

Now, I've upgraded to Airbrake 5.8.1, and left the same code.
Unfortunately, the errors are coming to the same room, as configured in `config/initializers/airbrake.rb`:

```ruby
Airbrake.configure do |config|
  config.project_key         = ****
  config.project_id          = ****
  config.host                = ****
  config.ignore_environments = %w(development test)
  config.environment         = Rails.env
  config.blacklist_keys      = Rails.application.config.filter_parameters
end
```

How can I achieve the same functionality with Airbrake 5.8.1 ?
P.S. using **Rails 4.2.0**

**Comment by kyrylo** [comment]
Howdy @vledniov!

You need to configure a second notifier as described in https://github.com/airbrake/airbrake-ruby#creating-a-named-notifier.

For example:

```rb
Airbrake.configure(:android) { ... }
```

Now you can send errors via that notifier:

```rb
Airbrake[:android].notify(error)
```

Let me know if this works for you.

**Comment by vledniov** [comment]
Yes, this configuration is exactly what I needed, works well with configurable notifiers !

Thanks @kyrylo
