### ISSUE TITLE
Rails 5.1 compatibility issue

### ISSUE THREAD

**Issue by eadz** [airbrake/airbrake#782]
Hi,

Using the latest airbrake gem 

```
airbrake (6.1.2)
      airbrake-ruby (~> 2.2, >= 2.2.5)
    airbrake-ruby (2.2.7)
````

I get the following exception:

```
undefined method `each_key' for #<ActionController::Parameters:0x007f19a0063950> Did you mean? each_pair
```

Backtrace

```
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/filters/keys_filter.rb:77 in filter_hash
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/filters/keys_filter.rb:54 in block in call
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/filters/keys_filter.rb:54 in each
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/filters/keys_filter.rb:54 in call
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/filter_chain.rb:47 in block in refine
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/filter_chain.rb:45 in each
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/filter_chain.rb:45 in refine
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/notifier.rb:126 in send_notice
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/notifier.rb:50 in notify
/gems/airbrake-ruby-2.3.2/lib/airbrake-ruby.rb:168 in notify
```

I am using 

`  c.blacklist_keys = [/password/i, /token/i] `

in the config.

**Comment by kyrylo** [comment]
I cannot reproduce this issue. I am running Rails v5.1.4, Ruby v2.3.3, airbrake-ruby v2.3.2, airbrake v6.2.1. I generated a new app and integrated Airbrake (the default config also configures blacklist filters). I sent a test exception and set up a controller which always raises an error. In both cases my exception was delivered to the dashboard.

Do you have any custom filters? Do you send an exception manually? What does your notice look like? Maybe you pass ActionController::Parameters manually?
