### ISSUE TITLE
Airbrake::Rack::HttpParamsFilter.call needs to handle exceptions

### ISSUE THREAD

**Issue by bquorning** [airbrake/airbrake#785]
I’ve sometimes seen this stack trace in New Relic, where `Airbrake::Rack::Middleware#call` encounters an exception and tries to `notify_airbrake`, but the HttpParamsFilter cannot properly extract the `request.params`:

```
Rack::QueryParser::InvalidParameterError: invalid %-encoding [...]
 /opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/common.rb:  387:in `decode_www_form_component'
…or/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/utils.rb:   51:in `unescape'
…le/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:  150:in `unescape'
…le/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:   65:in `block (2 levels) in parse_nested_query'
…le/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:   65:in `map!'
…le/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:   65:in `block in parse_nested_query'
…le/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:   64:in `each'
…le/ruby/2.4.0/gems/rack-2.0.3/lib/rack/query_parser.rb:   64:in `parse_nested_query'
…/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:  468:in `parse_query'
…/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:  343:in `POST'
…/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:  358:in `params'
…/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/request.rb:   20:in `params'
…airbrake-6.2.1/lib/airbrake/rack/http_params_filter.rb:   21:in `call'
…/airbrake-ruby-2.3.2/lib/airbrake-ruby/filter_chain.rb:   47:in `block in refine'
…/airbrake-ruby-2.3.2/lib/airbrake-ruby/filter_chain.rb:   45:in `each'
…/airbrake-ruby-2.3.2/lib/airbrake-ruby/filter_chain.rb:   45:in `refine'
…gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/notifier.rb:  126:in `send_notice'
…gems/airbrake-ruby-2.3.2/lib/airbrake-ruby/notifier.rb:   50:in `notify'
….0/gems/airbrake-6.2.1/lib/airbrake/rack/middleware.rb:   72:in `notify_airbrake'
….0/gems/airbrake-6.2.1/lib/airbrake/rack/middleware.rb:   54:in `rescue in call'
….0/gems/airbrake-6.2.1/lib/airbrake/rack/middleware.rb:   51:in `call'
…/new_relic/agent/instrumentation/middleware_tracing.rb:   96:in `call'
…
```

**Comment by kyrylo** [comment]
It doesn't look like an issue with Airbrake to me. Try to use this: https://github.com/whitequark/rack-utf8_sanitizer

P.S. Do you use Rubinius? How did you make your backtrace look like that?

**Comment by bquorning** [comment]
I am already using https://github.com/whitequark/rack-utf8_sanitizer – this issue might actually be related to whitequark/rack-utf8_sanitizer#40.

@kyrylo Could you please explain *why* you don’t see this as an Airbrake issue? An exception is happening *inside* `notify_airbrake`, so if it wasn’t for New Relic, this exception would be visible only in my logs.

P.S. New Relic is responsible for the strange backtrace formatting. I find it quite unreadable :-)

**Comment by kyrylo** [comment]
Exception happens when we call `request.params`. `request` is an instance of a Rack class. I checked http://www.rubydoc.info/gems/rack/Rack/Request#params-instance_method and it doesn't document that this exception should be expected and rescued.

I don't see what Airbrake can do here besides rescuing that particular exception on line 21 in `http_params_filter.rb`. I don't like this solution because it sounds like a temporary hack that doesn't *seem* to belong to this codebase.

I found this other solution online (I guess you've already seen it, if you know about rack-utf8_sanitizer): https://stackoverflow.com/a/15770203/511205

**Comment by kyrylo** [comment]
Alternatively, if you know what param that is, you can write a custom filter to delete it with `request.delete_param`: http://www.rubydoc.info/gems/rack/Rack%2FRequest:delete_param

**Comment by kyrylo** [comment]
One more project: https://github.com/alext/invalid_utf8_rejector

**Comment by bquorning** [comment]
Also related: https://github.com/rack/rack/issues/323
