### ISSUE TITLE
Cannot make de API work

### ISSUE THREAD

**Issue by nicokras** [airbrake/airbrake#801]
Hi, 

I made the following POST

https://airbrake.io/api/v3/projects/PROJECT_ID/notices?key=[PROJECT_KEY]

Data: {"errors":[{"type":"error","message":"pruebaAPI"}]}

Response: 
{
    "id": "00055a54-5fa8-44a6-da8e-c62cac54a269",
    "url": "https://airbrake.io/locate/00055a54-5fa8-44a6-da8e-c62cac54a269"
}

But there is no error in my dashboard. Also if I access the provided reply URL, it tels me there is no such record.

What could be happening?
Thanks.

**Comment by kyrylo** [comment]
Hi @nicokras. This issue tracker is for our Ruby notifier. General questions can be asked here: https://airbrake.io/contact

I think your data is missing a backtrace. Right now we're experiencing some delay in error processing, so there's also a chance that your errors will be delivered once we resolved that technical difficulty.

**Comment by nicokras** [comment]
Hi, Thanks for the info, and sorry for the posting error.
