### ISSUE TITLE
Your API key is unknown

### ISSUE THREAD

**Issue by akkee** [airbrake/airbrake#813]
```
2.4.0 :001 > Airbrake.notify(StandardError)
 => #<Airbrake::Promise:0x007fd915b8f740 @on_resolved=[], @on_rejected=[], @value={}, @mutex=#<Thread::Mutex:0x007fd915b8f470>>
2.4.0 :002 > E, [2017-12-12T16:23:58.590220 #83514] ERROR -- : **Airbrake: unexpected code (422). Body: Your API key is unknown
```
I see this error in both airbrake 6 and 7. None of my errors are being posted to errbit.

My `errbit.rb` looks like what it is supposed to:

```
Airbrake.configure do |config|
  config.host = 'https://myerrsite.com'
  config.project_id = 9999 # Just some random integer to make project_id true
  config.project_key = '12312wsdw2kdmkmkdkekkekkdd' #just some key
  config.ignore_environments  = %w[test]
  config.environment          = Rails.env
end
```
Reverting to airbrake 5 fixes it for me.

**Comment by kyrylo** [comment]
It's hard to tell without knowing how errbit works. It might be a problem with their API. I haven't seen this error (or similar) among airbrake.io users.

The change we've made to our API and notifier is that now we send the key in the `Authorization` header instead of the query param approach.

/cc @stevecrozz

**Comment by kyrylo** [comment]
I'm inclined to think it might be an issue with Errbit. Closing for now, but ping me if you have more details.

**Comment by stevecrozz** [comment]
Thanks @kyrylo. @akkee please make sure you're using a very recent version of errbit (probably master which includes https://github.com/errbit/errbit/commit/9c09edeeeeecebd90ebd096e1261e46aa26f50b3). If you still have an issue you can raise it over at https://github.com/errbit/errbit
