### ISSUE TITLE
Rails API support

### ISSUE THREAD

**Issue by chaffeqa** [airbrake/airbrake#821]
`ActionController::Metal` doesn't get `Airbrake::Rails::ActionController` injected.

I don't know if you would want to either document that, or change the initializer to inject at that level

**Comment by kyrylo** [comment]
Please help me understand the current situation with Rails API. I know it's been merged with Rails. So shouldn't it get support automatically? Do you still use the Rails API gem?

**Comment by kyrylo** [comment]
Closing for now. Let me know if it's still an issue.

**Comment by chaffeqa** [comment]
Sorry it took so long, super busy 😞 

[`ActionController::Metal`](http://api.rubyonrails.org/classes/ActionController/Metal.html) is part of Rails core, they pretty much implemented Rails API.  My hunch is you guys are hooking into `ActiveSupport.run_load_hooks(:action_controller, self)` but [that is only in `ActionController::Base`](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/base.rb#L274), not in [`ActionController::Metal` anywhere](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal.rb#L274)

I would think its correct to not force your middleware there, rather just document that if using the `::Metal` that you have to manually hook in airbrake.

FYI: Rails < 5 has `::Metal`, but after 5 users are encouraged to use [`ActionController::API` which has hooks again](https://github.com/rails/rails/blob/5.1.3/actionpack/lib/action_controller/api.rb#L144

**Comment by kyrylo** [comment]
Thank you for the clarification. Why do you think it's more correct to not force `Airbrake::Rails::ActionController`? I would expect it to work the same as `ActionController::Base` because our Rack middleware already supports `Metal` out-of-box (it reports unhandled exceptions automatically).

**Comment by chaffeqa** [comment]
I think because I think the best practice is [to rely on hooks like you already are](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails.rb#L46).  This works in `rails < 4 && >= 5` for both `ActionController::Base` and `ActionController::API`.  I think the rails core intention of leaving `ActionController::Metal` without the hooks and therefore "un-sullied" should be the way to go.  Basically it give the power user a guaranteed "clean slate" to build off of, while 99% of the other users get the expected functionality of `ActionController::Base` and `ActionController::API`.

For instance, now you are `include Airbrake::Rails::ActionController`ing **twice** in all rails versions >= 4 with that new fix, since all `ActionController::*` [inherit from `ActionController::Metal`](https://github.com/rails/rails/blob/5.1.3/actionpack/lib/action_controller/api.rb#L87), yet the hooks in `ActionController::Base` and `ActionController::API` are still being invoked, and triggering the `include` a second time.

*IMO* since the previous implementation works with everything **except** rails 4 + `ActionController::Metal` implementations, you can just make a note of the `::Metal` not being touched by Airbrake in the documentation and that should suffice.  Any power users (like ourselves ;) ) should already be doing the diligence of looking these things up when we use something like `::Metal`

**Comment by kyrylo** [comment]
Good point about including the module twice. I hadn't think of it. However, including a module twice has no consequences and adds minimal overhead. The same applies to `require`.

Why not to ease the life of power users, though (especially if the cost is so low)? If you use `Metal`, you still automatically receive exceptions. However, you can't use `notify_airbrake`. I am struggling to see the scenario where you have Airbrake in your project and don't want to use it for `Metal`, but want it for `ActionController::Base`.

**Comment by kyrylo** [comment]
Yeah, I understand your reasoning. It's probably a style choice and both solutions are correct. As for me, I find it more pragmatic to do what we did because it removes the necessity to google and read the docs because it just works. I understand that it may violate some ideas behind Metal, and if it causes more trouble than good, I'm always happy to choose the alternative approach.

Good conversation 👍 Thanks for filing the issue. Feel free to file more 😁
