### ISSUE TITLE
DelayedJob in Rails app not working

### ISSUE THREAD

**Issue by gcstr** [airbrake/airbrake#826]
#### Description

From the docs:
> `require 'airbrake/delayed_job'`
>
>If you required DelayedJob before Airbrake, then you don't even have to require anything manually and it should just work out-of-box.

What does it mean for Rails Apps? Should I define the DelayedJob gem __before__ Airbrake Gem?

**Comment by kyrylo** [comment]
For Rails apps it should just work, however the load order matters. If you don't want to depend on the load order, then you `require 'airbrake/delayed_job'` manually. If you don't want to write that, you can arrange gems in the specific order where the airbrake gem comes prior to the delayed_job gem (I might be wrong about the order here, still couldn't memorise it). Is something not working for you?

**Comment by gcstr** [comment]
@kyrylo, yes.
I have a Rails Application with `DelayedJob` for `ActiveJobs`.
Currently, no job exceptions are being captured, everything else is.

I'll change the order in Gemfile and if it doesn't work I'll add the `require` statement.

**Comment by kyrylo** [comment]
Thank you, I'd be curious to hear from you as soon as possible. I have an open support request from someone who struggles with our Sidekiq integration. They say that all exceptions work as expected, but no exceptions from Sidekiq are getting through. The description is very similar to yours, except they use Sidekiq.

**Comment by fsmanuel** [comment]
@kyrylo For DelayedJob airbrake needed to be AFTER delayed_job:

```rb
gem 'delayed_job_active_record'
gem 'airbrake', '~> 7.2'
```

**Comment by gcstr** [comment]
@kyrylo, thanks for your support!

The Gemfile order was the actual problem.
My suggestion to close this issue, would be to change the docs and README where it describes background jobs integration.

https://github.com/airbrake/airbrake#delayedjob

**Comment by kyrylo** [comment]
I'm going to close this issue as is because the solution is provided in the readme: require the integration manually, if airbrake doesn't work for you for some reason. Adding a mention about the order sounds more like a hack. Besides, I would need to add such a mention to every integration we provide, so it will be a lot of duplication. Ideally, the order shouldn't matter, but we have what we have. Maybe in the future I'll come up with something better than what we currently have.
