### ISSUE TITLE
New release for v7.2.1

### ISSUE THREAD

**Issue by fsmanuel** [airbrake/airbrake#827]
Thanks for the great gem!
The [Changelog](https://github.com/airbrake/airbrake/blob/master/CHANGELOG.md) already mentions `7.2.1` but [rubygems](https://rubygems.org/gems/airbrake) only shows `7.2.0`. Would be great if you can release the `7.2.1` version!

**Comment by kyrylo** [comment]
Oh snap, that was my mishap. Just pushed the gem. https://rubygems.org/gems/airbrake/versions/7.2.1

Happy Airbraking!

**Comment by fsmanuel** [comment]
Thanks!
