### ISSUE TITLE
Ignoring errors from Sidekiq workers with upcoming retries

### ISSUE THREAD

**Issue by lucasmazza** [airbrake/airbrake#830]
We noticed in our app that most of the Sidekiq jobs that failed would eventually succeed in one of the retries attempts that would happen, making the error report feel like noise rather than something we would have to fix right away.  Now we have [a custom filter class](https://gist.github.com/lucasmazza/31a0a3791f9a37da284344b6af3418cc) that would ignore errors from these jobs, leaving only errors from the final attempts to be collected by Airbrake. 

I think this could be useful for other users, and if it makes sense I can send a Pull Request adding the class and documenting how it can be enabled rather than leaving it on by default (which could be too big of a change for those who might not want this). What do you folks think? 😄

**Comment by kyrylo** [comment]
That looks great!
I am not sure why anybody would want to report a failure when a job is going to be retried but I am sure it must exist. For now, it's better to make this optional, just like you suggested. If we were to merge your code with the Sidekiq integration, then this behaviour would be forced. There wouldn't be any way to opt-out. So your approach is sound (feel free to send a PR 👍).
