### ISSUE TITLE
Airbrake 4.1.0, cannot ignore error

### ISSUE THREAD

**Issue by PeaceS** [airbrake/airbrake#854]
* Airbrake version: 4.1.0
* Ruby version: 2.2.10
* Framework name & version: Rails 4.2.1

#### Airbrake config
```
Airbrake.configure do |config|
  config.api_key = ENV['API_KEY'] || 'xxxxxxx' if App.environment.production?
  config.ignore << "SignalException"
  config.ignore << "ThreadError"
  config.ignore << "Resque::DirtyExit"
end
```
#### Description

I know that this is a very old version, but our current project still running on it, and no plan for upgrading it any soon.
Anyways, the question is that I cannot ignore those error that I tried to ignore, is anything wrong on this config? thank you

**Comment by kyrylo** [comment]
You pointed out correctly that it's an old version and unfortunately we don't support it anymore. 

If you don't plan to upgrade to the current version, then you could at least try upgrading to the last 4.x version, which is [`4.3.8`](https://rubygems.org/gems/airbrake/versions/4.3.8). That said, it's also not supported anymore but at least it doesn't break compatibility and may fix your issue.

I'm not sure if the config you use is valid but if it doesn't work with `4.3.8`, perhaps try this API: https://github.com/airbrake/airbrake/tree/v4.3.8#ignored-exceptions

**Comment by kyrylo** [comment]
I also strongly recommend you to upgrade to the modern version because you're missing out features and staying on an old version is risky because we are deprecating TLS 1.0 and 1.1 this month, which may stop error delivery for you.

> If you are running a legacy version of an Airbrake notifier your account may stop receiving errors. We recommend upgrading your notifier before June 30th, 2018.
>
> via https://airbrake.io/blog/airbrake-news/tls-1-0-and-1-1-deprecation

**Comment by PeaceS** [comment]
alright, I'll looking for upgrade it then, just to make sure is it really the problem.

Thank you so much, cheers
