### ISSUE TITLE
Allow providing a custom class for Airbrake::Rack::ContextFilter to use when extracting user from request

### ISSUE THREAD

**Issue by pouellet** [airbrake/airbrake#883]
It would be really useful to have an option to set the class that `Airbrake::Rack::ContextFilter` uses to try to determine which user is performing the request.

In one of our code base, we have some wrapper code surrounding the `current_user` method which may raise an exception under certain conditions. If this happens when the `Airbrake::Rack::User.extract` gets called, the Airbrake rack middleware ends up throwing an error and this results in a 500. 

While we can fix this by monkey patching `Airbrake::Rack::User.extract`, it would be cleaner to be able to specify which class to use to do the extraction. It would also allow the few folks that don't use OmniAuth or Devise to provide an implementation. Or to fix cases like this one #618.

I'm happy to do a PR if there's some interest in adding this.

**Comment by kyrylo** [comment]
Sounds like a great idea. Feel free to submit a PR.

**Comment by pouellet** [comment]
Thanks for the quick response, I'll give it a try.

**Comment by pouellet** [comment]
@kyrylo I've got something going but I would like to get your input on two things:

1 - I would like to change the [`Airbrake::Rack::User.extract`](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/user.rb#L10) method to return either a `Hash` or `nil` instead of a `User` object. The `Airbrake::Rack::ContextFilter` could then take the response directly [instead of having to call `to_json`](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/context_filter.rb#L43) on the object returned. I think it would simplify the interface for people wanting to provide an implementation.

2 - I am not sure on where to allow users to specify the class to use. The only user configurable settings that I've found are all in `Airbrake::Config`, but that doesn't feel right to configure the middleware. Should I just allow configuring it directly on the `Airbrake::Rack::ContextFilter` class or would you rather have a more centralized configuration object?

**Comment by kyrylo** [comment]
Resolved by https://github.com/airbrake/airbrake-ruby/pull/376 & https://github.com/airbrake/airbrake/pull/890.
