### ISSUE TITLE
Airbrake should tap into ActionCable exceptions

### ISSUE THREAD

**Issue by ipepe** [airbrake/airbrake#885]
It is a while since rails is shipping with ActionCable but still Airbrake ignores exceptions that happen on Channels. 

I had to create this monkey patch to notify me about exceptions:
```ruby
module ApplicationCable
  class Channel < ActionCable::Channel::Base
    private

    def dispatch_action(action, data)
      if method(action).arity == 1
        public_send action, data
      else
        public_send action
      end
    rescue StandardError => exception
      Airbrake.notify(exception, parameters: {
                        action: action, data: data,
                        user_id: connection.user&.id,
                        connection: connection.statistics
                      })
      raise exception
    end
end
```
I was wondering if airbrake should tap into ActionCable out of box? Like it does for Controllers?

**Comment by kyrylo** [comment]
Yes, it would be great to support this out of box. Would you mind contributing a patch?

**Comment by ipepe** [comment]
No problem. Is that code snippet a good way to implement this?

**Comment by kyrylo** [comment]
I am not familiar with ActionCable yet but if it doesn't provide a public API for catching exceptions we should do what we do with our Rake integration. So yeah, similar to what you do but we wrap it like this:

https://github.com/airbrake/airbrake/blob/e1d623d2c2c284e0cb4975b2f681850250031080/lib/airbrake/rake.rb#L9-L22

**Comment by ipepe** [comment]
I'm familiar with rails v5.0.x code and I haven't seen public api. I'm not sure about later versions, I will check on that. But even if newer version has public api for exceptions, I will fight to 5.0.x support because of my current project status.

I also found (https://github.com/rails/rails/issues/31924) that appsignal monkey patches `ActionCable::Channel::Base#perform_action` like here:
https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/hooks/action_cable.rb#L23

**Comment by kyrylo** [comment]
Thanks for researching. The Appsignal approach sounds good to me but I don't understand the significance of `class_eval`. It's probably to make sure that the monkey-patch has the precedence but if we are using Rails, it would be loaded before Airbrake anyway, so we can just reopen the class. Perhaps, it serves some other purpose. I would try the Rake approach I linked to first.

**Comment by ipepe** [comment]
I maybe it has something to do with difference how development and production envrioments are loading classes. Or maybe it allows developers for more monkey patching after our monkey patching?

I asked author here: https://github.com/appsignal/appsignal-ruby/pull/275

**Comment by kyrylo** [comment]
@ipepe let me know if you're stuck.

**Comment by ipepe** [comment]
Nah. Just smashed with work ;) But soon I'm going to have some spare time and will give it some time. Thanks for reminding me!

**Comment by ipepe** [comment]
I started drafting pull request but I wonder what information should be passed when exception happens. Because You can see that I'm passing manually:
```ruby
{
                       user_id: connection.user&.id,
                        connection: connection.statistics
}
```
Any idea how to make it proper? In errbit when normal request crashes I have information about user, about browser and stuff. I think we should be able to get same information here...

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake/pull/896.
