### ISSUE TITLE
Issue with airbrake-ruby 3.2

### ISSUE THREAD

**Issue by brchristian** [airbrake/airbrake#895]
As of updating airbrake-ruby 3.2 today, every pageview on our site throws a 500 error:

```
undefined method `notify_request' for #<Airbrake::NoticeNotifier:0x00007ff0ca266520> Did you mean? notify_sync
```

The exception is being thrown from https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/action_controller_subscriber.rb#L20

Seems like something is going wrong here if airbrake and airbrake-ruby don’t play nicely together!

We are rolling back to airbrake-ruby 3.1 in the meantime...

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake-ruby/pull/411 and released in airbrake-ruby v3.2.2.
