### ISSUE TITLE
rspec slowdown after upgrading from v8.1.x to v8.2 or v8.3

### ISSUE THREAD

**Issue by dannyfink** [airbrake/airbrake#938]
I observed that after upgrading from v8.1.2 to any version of v8.2 or v8.3 my RSpec test suite went from taking ~50s to ~1m 15s. Is this a known issue by any chance? Once reverting back to v8.1 the test performance was fine. 

Let me know if there is any logs or anything I can provide that may be helpful. Thanks!

**Comment by kyrylo** [comment]
Never heard of this issue before. Is it in a Rails app? What's your airbrake-ruby version? What kind of tests do you have? Unit? Any chance to narrow down the slow tests?

**Comment by pablogfb** [comment]
I'm not sure if it is related but we have suffered a huge performance impact in our Rails app (5.2.2 and Ruby 2.5.3) after upgrading to 8.2.0. We suffered and increment of the response times near to an 50%-60%. It's very strange but New Relic shows an intense increment of the DB usage which does not make any sense for me...

We have decided to stay in a lower version as we can't afford to put resources to investigate this.

**Comment by dannyfink** [comment]
@kyrylo
1. Rails App v5.2.2
2. Upgraded from Airbrake v8.1.2 to 8.2.1 (also tried 8.3.2)
3. Upgraded from airbrake-ruby 3.2.6 to airbrake-ruby 4.2.0
4. Unit tests were not impacted only the System tests (which truncate the db after each test) were the ones that were impacted

**Comment by kyrylo** [comment]
Does any of you enable `performance_stats` in your config? It's a beta feature, which is disabled by default. This info will help to rule out possible places where issues can arise.

**Comment by varyform** [comment]
@pablogfb it actually increased our DB latency, that's why NR was kinda right.
![image](https://user-images.githubusercontent.com/20039/54622454-47a16f00-4a72-11e9-9e19-845ff20900d1.png)

**Comment by kyrylo** [comment]
@varyform do you configure `performance_stats`? Are you on v8.3?

**Comment by varyform** [comment]
@kyrylo we didn't configure anything, just upgraded from 8.1.2 to 8.3.2.

**Comment by pablogfb** [comment]
Same here, we have decided to stay at 8.1.2 for that reason. I was very confused about the DB latency increment but it's glad to see that we're not the only ones, so there might be a real problem.

How can airbrake increment the interactions with the DB?

**Comment by dannyfink** [comment]
@kyrylo we do not have performance_stats enabled. Is there anything else I may be able to provide that could be helpful for debugging?

**Comment by shaicoleman** [comment]
It seems like the the performance module is always loaded, there's no condition
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails.rb#L10

**Comment by kyrylo** [comment]
@shaicoleman good point. I have a PR that is currently a WIP that does exactly what you say 😄
https://github.com/airbrake/airbrake/pull/942

**Comment by kyrylo** [comment]
I released v9.0.0, and I believe it should fix this issue. Before closing this issue I'd like to confirm it's the case.

@dannyfink could you please try to run it with your tests to see an improvement? Anybody else is welcome, of course, but I figured it'll be easier and faster to test without deploying the new version.

**Comment by dannyfink** [comment]
@kyrylo v9.0.0 performance is great. It's back to the same performance as in 8.1.2! Thank you for following up.

**Comment by kyrylo** [comment]
Glad to hear that.
