### ISSUE TITLE
[REQUEST] Start depending on airbrake-ruby 4.2.2?

### ISSUE THREAD

**Issue by francois-belle** [airbrake/airbrake#941]
* Airbrake version: **8.3.2**
* Ruby version: **2.5.3**
* Framework name & version: **Rails 5.2.2**

#### Airbrake config

```ruby
Airbrake.configure do |c|
  c.project_key         = ENV['AIRBRAKE_PROJECT_KEY']
  c.project_id          = ENV['AIRBRAKE_PROJECT_ID']
  c.host                = ENV['AIRBRAKE_HOST']
  c.root_directory = Rails.root
  c.logger = Rails.logger
  c.environment = Rails.env
  c.ignore_environments = %w[test development]
  c.blacklist_keys = [/password/i, /authorization/i]
end
```

#### Description

Hey guys, first of all, thank you for this amazing gem!  

I did the setup and tried sending some test notifications.  
**The problem** is that my `blacklist_keys` are not taken into account and every password appears in clear in the errors reporting tool (I'm using Errbit).  
I think it's a [known issue](https://github.com/airbrake/airbrake-ruby/issues/460) that was fixed in [this PR](https://github.com/airbrake/airbrake-ruby/pull/461) in **airbrake-ruby** dependency.  
This fix was released in [airbrake-ruby 4.2.2](https://github.com/airbrake/airbrake-ruby/releases/tag/v4.2.2) but [aibrake depends on airbrake-ruby 4.1](https://github.com/airbrake/airbrake/blob/1016975866fe217392258051fca5b8df358a8b22/airbrake.gemspec#L34).

Do you think it's possible to move on to the latest version of airbrake-ruby?

Any help would be greatly appreciated.  
François

**Comment by kyrylo** [comment]
Hi, yeah, that's the plan. Thanks for pinging, I actually forgot that this gem was locked to 4.1. I'll release a new version today.

**Comment by kyrylo** [comment]
Small update. There are some complexities with upgrading, so I need a bit more time. Sorry for the false information.

**Comment by francois-belle** [comment]
Thanks for the update @kyrylo 🙏
