### ISSUE TITLE
Spec logs are included in gem builds

### ISSUE THREAD

**Issue by fwilkens** [airbrake/airbrake#970]
Hi there! I noticed that recent gem versions (at least since 8.2x) include some log files that appear to be generated during the rails specs:
```
airbrake/spec/apps/rails/logs/32.log
airbrake/spec/apps/rails/logs/42.log
airbrake/spec/apps/rails/logs/52.log
```

For version 9.2.1, these end up accounting for >6mb once the gem is unpacked. The total packed gem size is 688K.

Is it possible to exclude these log files from future gem builds?

**Comment by kyrylo** [comment]
That's a good find. Sure, I will make sure they're excluded in the next release.

**Comment by fwilkens** [comment]
👍 Sounds great @kyrylo -- thanks!

**Comment by kyrylo** [comment]
9.2.2 - May 10, 2019 (20.5 KB)
9.2.1 - May 01, 2019 (688 KB)

🎉
