### ISSUE TITLE
URLs are missing in v9.2.2

### ISSUE THREAD

**Issue by stefansundin** [airbrake/airbrake#976]
* Airbrake version: v9.2.2
* Ruby version: 2.6.3
* Framework name & version: Sinatra v2.0.5

#### Airbrake config

https://github.com/stefansundin/rssbox/blob/5afd46095ff78405428c5333e618e3820a81e9af/config/initializers/05-airbrake.rb

#### Description

Hello!

Yesterday I updated the airbrake gem in my app, and all of the URLs are suddenly missing from my exceptions. I rolled back to v9.2.1, and they are now showing up again.

My app is a simple Sinatra application. https://github.com/stefansundin/rssbox

Rollback: https://github.com/stefansundin/rssbox/commit/675b3dc8f629f096ab9da6e3208ddd1ebcd2b8b0

I don't know what is causing it. Hopefully you can figure it out. Thanks!

**Comment by kyrylo** [comment]
Hi @stefansundin! Since this is an open source project, I cloned it and tried to reproduce this scenario.

```diff
diff --git a/Gemfile b/Gemfile
index b302cd7..9b6ff18 100644
--- a/Gemfile
+++ b/Gemfile
@@ -23,7 +23,7 @@ gem "prometheus-client", require: "prometheus/middleware/exporter"
 gem "feedjira"
 gem "opengraph_parser"

-gem "airbrake", "= 9.2.1", require: false
+gem "airbrake", "= 9.2.2", require: false
 gem "newrelic_rpm", require: false

 group :development do
diff --git a/Gemfile.lock b/Gemfile.lock
index bfd99fb..539fa17 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -8,8 +8,8 @@ GEM
       tzinfo (~> 1.1)
     addressable (2.6.0)
       public_suffix (>= 2.0.2, < 4.0)
-    airbrake (9.2.1)
-      airbrake-ruby (~> 4.3)
+    airbrake (9.2.2)
+      airbrake-ruby (~> 4.4)
     airbrake-ruby (4.4.0)
       rbtree3 (~> 0.5)
     backports (3.15.0)
@@ -97,7 +97,7 @@ PLATFORMS
 DEPENDENCIES
   activesupport
   addressable
-  airbrake (= 9.2.1)
+  airbrake (= 9.2.2)
   dotenv
   feedjira
   github-release-party
diff --git a/app.rb b/app.rb
index b7b0163..610eabc 100644
--- a/app.rb
+++ b/app.rb
@@ -24,6 +24,7 @@ after do
 end

 get "/" do
+  raise 'oops'
   SecureHeaders.use_secure_headers_override(request, :index)
   erb :index
 end
```

Then I executed `rackup` and `curl localhost:9292`.

I saw my error in the dashboard and it did contain a URL:

![1](https://user-images.githubusercontent.com/1079123/58940562-67e3ee80-8782-11e9-8d5f-9caffed62983.png)

Do you have a repro case? I'm not sure how you managed to see no URLs.

**Comment by renatolond** [comment]
I have a similar issue, but in my case we don't have any info on the RequestStore. It seems that my exceptions is being sent at the `framework_exception` piece of `middleware.rb`, which means the RequestStore was already cleared by then.

**Comment by kyrylo** [comment]
@renatolond thanks, that's a good catch. I can see how that is an issue. I'm also not sure if that's related here but it would be nice to fix.

**Comment by stefansundin** [comment]
@kyrylo I just did the exact same test as you, and the URL is in the report this time.

I will try to upgrade again and deploy it later today. Maybe there was something else causing this.

**Comment by kyrylo** [comment]
Thanks, a repro case is greatly appreciated. Otherwise, I can't do much because we've had similar reports in the past but they've been fixed already.

**Comment by stefansundin** [comment]
I think https://github.com/airbrake/airbrake/pull/977 resolved this too..

I wasn't able to repro locally, and I have no idea why. I tried getting everything as close to my production app as possible, but I always had the URL attached when running locally.

I upgraded to 9.2.2 again here: https://github.com/stefansundin/rssbox/commit/b6f1c5d1b7569459bbce84e39345e84d2ec3db7a, and then I wasn't getting the URL again.

Then I upgraded to the latest master branch using `git:` here: https://github.com/stefansundin/rssbox/commit/b223d982eb48db3711c278a6b7e04b53576a6761, and things appear to be working now..

I can forward more details, maybe the raw context from the airbrake website, if you want?

**Comment by kyrylo** [comment]
Since this is a Sinatra app, I assume you were receiving your exceptions from the Rack environment (I can see it now). I guess https://github.com/airbrake/airbrake/pull/977 was indeed *the* fix. Thanks for the report, that was quite an oversight!
