### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by janklimo** [airbrake/airbrake#994]
Using `airbrake-ruby` version 4.5.0 or higher, `performance_stats` are enabled by default. This allocates quite a lot of objects for every query that gets executed (processing query backtrace with `activesupport` and `railties`). Because this is now the default setting, I think more consideration should be given to how it impacts memory.

E.g. the action below saw 61% savings by turning the setting off:

![airbrake](https://user-images.githubusercontent.com/7811733/62413422-139da380-b639-11e9-81fe-d0d45ec6eee7.gif)

It looks like backtrace is being processed for every SQL query triggered. I'm not too familiar with this feature, but it looks like we should be more selective about when it gets triggered given how many objects it allocates?

**Comment by kyrylo** [comment]
Thanks for the report. What tool do you use to measure allocations?

**Comment by janklimo** [comment]
I'm using `rack-mini-profiler` together with `memory_profiler`. With that setup you can profile specific actions by navigating to `http://localhost:3000/your_path?pp=profile-memory`.

**Comment by kyrylo** [comment]
I released a fix in airbrake v9.4.1. Could you please take a look?
